### ISSUE TITLE
Switch user media to s3 + CDN

### ISSUE THREAD

**Issue by pmac** [mozilla/kitsune#2899]
Uploaded media needs to go somewhere external to the servers in AWS. S3 is good for this with a CDN (probably CloudFront) in front.

**Comment by jwhitlock** [comment]
We have a similar requirement on Kuma.  I've configured upload to S3 years ago, but we decided to go w/ EFS for the first version (https://github.com/mozmeao/infra/issues/183) for speed of migration.

My dream version is a stand-alone service that takes uploads, performs type detection and security checks, and processes them into display-specific forms (for example shrinking PNG, scaling in-content images, etc.), and uses S3 as an optional backend.  The web app interacts with a REST API to request asset state (processing, ready) and get URLs by format.

But, with limited time, we'll probably just get by w/ django-storages.

**Comment by metadave** [comment]
@glogiotatidis @pmac @jgmize 
Cloudfront, S3 and Route 53 are setup for the following:

[https://dev-cdn.sumo.mozilla.net/](https://dev-cdn.sumo.mozilla.net/)
[https://stage-cdn.sumo.mozilla.net/](https://stage-cdn.sumo.mozilla.net/)
[https://prod-cdn.sumo.mozilla.net/](https://prod-cdn.sumo.mozilla.net/)

Feel free to remove the index.html page from each dev|stage|prod bucket.

**Comment by glogiotatidis** [comment]
Required Settings:
- `AWS_S3_CUSTOM_DOMAIN`
- `AWS_ACCESS_KEY_ID`
- `AWS_SECRET_ACCESS_KEY`
- `AWS_STORAGE_BUCKET_NAME`
- `AWS_S3_HOST`

**Comment by glogiotatidis** [comment]
Wiki documents hold a saved version in `Document.html` which needs to be updated so media point to the new origins.
