### ISSUE TITLE
Use AWS SES to send email

### ISSUE THREAD

**Issue by pmac** [mozilla/kitsune#2900]
This will help consolidate billing and monitoring, as well as potentially help address or debug some email issues we've seen in the past.

**Comment by glogiotatidis** [comment]
FTR we're currently using [SocketLabs](https://www.socketlabs.com/). Let's make sure that we ping WebOps when this is done that we don't need the SocketLabs acc anymore

**Comment by messed-with** [comment]
Once again...someone not allowing to see the things being used on my accounts
Jenn

**Comment by metadave** [comment]
Note: if for some reason we end up sticking with SocketLabs, AWS automatically [throttles port 25 outbound traffic](https://aws.amazon.com/premiumsupport/knowledge-center/ec2-port-25-throttle/). We had a similar issue in MDN, changing the SocketLabs port allowed us to bypass the throttle.

**Comment by glogiotatidis** [comment]
We need to verification `notifications@support.mozilla.org` email on SES. I filed [bug 1428741](https://bugzilla.mozilla.org/show_bug.cgi?id=1428741) to identify the users receiving those emails and then proceed with the verification.

**Comment by glogiotatidis** [comment]
> We need to verify notifications@support.mozilla.org email on SES. I filed bug 1428741 to identify the users receiving those emails and then proceed with the verification.

No MX record for support.m.o thus nobody gets those emails and we can't verify Email in AWS. Ops will create an MX record and point emails to a private Google Group so we can verify. Progress in [bug 1428741](https://bugzilla.mozilla.org/show_bug.cgi?id=1428741)

**Comment by metadave** [comment]
@glogiotatidis is there anything you need me to automate here?

**Comment by glogiotatidis** [comment]
> @glogiotatidis is there anything you need me to automate here?

I understand that we need to verify the address and then we can use SES. I don't see anything to automate. Do I miss something?

**Comment by glogiotatidis** [comment]
We are going to validate the domain in SES which will unlock all email address for sending. 

Bug https://bugzilla.mozilla.org/show_bug.cgi?id=1432747

**Comment by glogiotatidis** [comment]
AWS verified the domain 🥂 

I'll proceed with adding email address and with testing on Monday and plan on switching SCL3 to SES within next week.

**Comment by glogiotatidis** [comment]
1. Created IAM user for scl3
2. Pushed and Verified working on SCL3 staging
3. Pushed and Verified working on SCL3 production
4. Created IAM user for AWS dev 
5. Created issue to track deletion of IAM user created in (1) after SCL3 decom. https://github.com/mozmeao/infra/issues/716

Credentials are in sumo-encrypted

**Comment by glogiotatidis** [comment]
Also created
  - sumo-stage-ses-smtp-user
  - sumo-prod-ses-smtp-user

for AWS stage and prod
