### ISSUE TITLE
Cannot go back to question from email notification

### ISSUE THREAD

**Issue by orschiro** [mozilla/kitsune#2906]
From the below email there is no way to go back to the original question without marking the question as solved or indicating that it doesn't solve the problem. 

![image](https://user-images.githubusercontent.com/170947/28997804-e1146c40-7a1d-11e7-8618-20181b1a3728.png)

**Comment by MikkCZ** [comment]
This link "This doesn't solve my problem" actually just opens the answer on the SUMO page. If this is confusing, we can use a more clear formulation.

@glogiotatidis should we track this here or in Bugzilla? To be honest I do not know why the issues are open here at all.

**Comment by orschiro** [comment]
> If this is confusing, we can use a more clear formulation.

Yes, please use something like "View question in the browser".

**Comment by glogiotatidis** [comment]
> @glogiotatidis should we track this here or in Bugzilla? To be honest I do not know why the issues are open here at all.

We track bugs in Bugzilla. Only activity related to the infrastructure and the upcoming move to AWS should be tracked here.

**Comment by glogiotatidis** [comment]
@orschiro could you please file a bug in bugzilla about this?

https://bugzilla.mozilla.org/enter_bug.cgi?product=support.mozilla.org

**Comment by orschiro** [comment]
@glogiotatidis sure!

https://bugzilla.mozilla.org/show_bug.cgi?id=1410405

**Comment by glogiotatidis** [comment]
And thank you very much! I'll go ahead and close this one.
