### ISSUE TITLE
[Bug 1386808] Closing Army of Awesome and Removing References

### ISSUE THREAD

**Issue by turtleloveshoes** [mozilla/kitsune#2908]
Per this community decision to start the Social Support Program, https://support.mozilla.org/en-US/forums/social-media/712414?last=71489 and https://support.mozilla.org/en-US/forums/social-media/712299?last=70945, AoA is closing :(

However a new program with new materials will be replacing it. See issue [Bug 1385135]
https://support.mozilla.org/en-US/forums/social-media/712533?last=72211

**Comment by fitojb** [comment]
I think you meant to open a pull request instead of an issue? There’s no point on opening issues here, especially if they are already at Bugzilla, which is the canonical issue tracker.

**Comment by glogiotatidis** [comment]
Closing this one in favor of #2916
