### ISSUE TITLE
[Bug 1385135] Adding new material to and links for the Social Support Program

### ISSUE THREAD

**Issue by turtlelovesshoes** [mozilla/kitsune#2909]
Page for get-involved would look like: 
Help people on twitter and Facebook

Step 1: Link to Guidelines
Step 2: Sign up process - sumo account -> redirect to form created (keeping the twitter account and sumo account from army of awesome is ideal here)
Step 3: Link to Training article (includes tweetdeck, filters, contact info and moderators)

Links on other pages would remain the same
Dashboards would be removed. 

Content in progress: 
https://bugzilla.mozilla.org/show_bug.cgi?id=1385135

**Comment by bensternthal** [comment]
As far as I can tell this is no longer valid.
