### ISSUE TITLE
Buggy Filters when upgrading Thunderbird from v45 to v52

### ISSUE THREAD

**Issue by NicSil** [mozilla/kitsune#2925]
Hi,
Don't know where to put this: The "move" action does not work anymore when upgrading Thunderbird from v45 to v52: the target folder is empty. This problem disappears when switching back to v45-8-0.
See screen dump.
![thunderbirdfilter](https://user-images.githubusercontent.com/9283001/31276822-28b6a5d0-aa9e-11e7-8aab-c5a110667464.png)

**Comment by fitojb** [comment]
Thunderbird’s bug tracker is at bugzilla.mozilla.org. This is the wrong place to report this; as you can see, this repository hosts code for _Mozilla’s support website itself_.

**Comment by glogiotatidis** [comment]
@NicSil as @fitojb suggests please file [Thunderbird bugs in Bugzilla](https://bugzilla.mozilla.org/enter_bug.cgi?product=Thunderbird). This is the wrong place and thus I'm going to close this issue.

**Comment by NicSil** [comment]
mmmh... seems very complicated to get an account there. So I think the purpose is to avoid people sending comments and bugs. So I think I will keep my bug in my pocket.

**Comment by NicSil** [comment]
And trying to fit the rules for creating a password is a nightmare. The guy that decided this if fool: its not a banking account...

Your password must be at least 12 characters long, and contain:

multiple uppercase letters, multiple lowercase letters, and multiple numbers

OR multiple symbols, numbers, and letters
OR a phrase with at least 4 words

**Comment by NicSil** [comment]
Give up.
my business is not here. Just wanted to help.

**Comment by glogiotatidis** [comment]
I'm sorry you feel this way NicSil. I'm not claiming the Bugzilla's process if the best but filing bugs in random places just b/c it's under the mozilla github org doesn't help either.

Anyway, I hope that you file that bug to help make the software better for you and others.

**Comment by NicSil** [comment]
Ok. Added to Thunderbird bugs in Bugzilla.
