### ISSUE TITLE
Memory leak on folder repair?

### ISSUE THREAD

**Issue by ambraspace** [mozilla/kitsune#2929]
I have some issues with my emails, so I have to manually (by using OS commands) move messages from one folder to another. My Inbox folder has 11000+ messages in Maildir format.

When I move approx. 200 messages from Inbox to Inbox/BAD, and start folder repair of Inbox folder, memory usage of Thunderbird increases several GB and remains that high even after operation finishes.
It is always reproducible.
I'm using Thunderbird 52.4.0 (64bit) on Linux Gentoo.

**Comment by glogiotatidis** [comment]
Hi @ambraspace 

This is an issue tracker for the Django project that https://support.mozilla.org is based on.

Please file Thunderbird support questions here: https://support.mozilla.org/questions/new
