### ISSUE TITLE
Create CloudFront distributions for User Media

### ISSUE THREAD

**Issue by glogiotatidis** [mozilla/kitsune#2934]
Create two CloudFront distributions for User Media

 - [x] One for production use with origin the production S3 bucket created in #2933 
 - [x] One for stage use with origin the stage S3 bucket created in #2933 

Part of #2899

**Comment by metadave** [comment]
See also: 
https://github.com/mozmeao/infra/pull/626
https://bugzilla.mozilla.org/show_bug.cgi?id=1413279

**Comment by metadave** [comment]
provisioned in https://github.com/mozmeao/infra/pull/626
