### ISSUE TITLE
Confirm that django-axes gets client's ip

### ISSUE THREAD

**Issue by glogiotatidis** [mozilla/kitsune#2944]
django-axes needs to now the client ip. Now it's configurated to `HTTP_X_CLUSTER_CLIENT_IP`. 

Does this header work in k8s?

**Comment by jwhitlock** [comment]
MDN gets ``X-Forwarded-For`` with the IP address, according to a Sentry backtrace.  We don't use CloudFront in front of the ELB. I'm not sure how to get other header information without shipping ``DEBUG=True`` code.

**Comment by glogiotatidis** [comment]
Thanks for you feedback @jwhitlock. AFAIK `x-forwarded-for` is the same as `HTTP_X_CLUSTER_CLIENT_IP` so that should be good enough. 

> I'm not sure how to get other header information without shipping DEBUG=True code.

Can you please elaborate on which other headers are you talking about and why you need to set DEBUG to get them?

**Comment by jwhitlock** [comment]
Sentry shows these headers:

```
Connection: keep-alive
Host: developer.mozilla.org
X-Forwarded-For: (user's IP)
X-Forwarded-Port: 443
X-Forwarded-Proto: https
```

I'd also expect a ``User-Agent`` and an ``Accept`` header, and I assume Sentry is filtering them out. I'd need to create an endpoint that displays the user's headers (unsafe to leave on in production for long), or enable something like the [django-debug-toolbar](https://github.com/jazzband/django-debug-toolbar) to get more detail (which requires ``DEBUG=True`` and is unsafe to leave on in producton).

**Comment by glogiotatidis** [comment]
Oh get more headers in sentry, I get it. If it's of any help Sentry for SUMO returns a full list of headers including Accept and User-Agent. I haven't changed anything from the default conf. Maybe it's something in raven's conf?

**Comment by glogiotatidis** [comment]
See also #3018

**Comment by glogiotatidis** [comment]
Since Axes is currently disabled I'll remove this from the AWS dashboard

**Comment by akatsoulas** [comment]
This issue is too old and probably resolved by now. Please open a new issue if this is not the case.
