### ISSUE TITLE
Create IAM users for dev, stage, prod with S3 access

### ISSUE THREAD

**Issue by glogiotatidis** [mozilla/kitsune#2954]
Created:
 - sumo_dev
 - sumo_stage
 - sumo_prod

with the needed policies to access S3 user media buckets.

Do we want to create different users for user media and for static media? /cc @pmac @metadave

**Comment by metadave** [comment]
If we're concerned about security, then we should split the users out. Otherwise, fewer users is easier to manage. I don't have a strong opinion either way
