### ISSUE TITLE
Fix search related tests

### ISSUE THREAD

**Issue by glogiotatidis** [mozilla/kitsune#2962]
The ElasticSearch upgrade to V2 broke a number of tests.

Currently all search related tests are marked as `search_tests` and get skipped in the test runs with `-a '!search_tests'`.

This issue tracks the update / re-write of those tests to work with current infra.

See also #2931

**Comment by akatsoulas** [comment]
This issue is too old and probably resolved by now. Please open a new issue if this is not the case.
