### ISSUE TITLE
Improve Travis Build Time

### ISSUE THREAD

**Issue by glogiotatidis** [mozilla/kitsune#2966]
Travis needs 15-20 minutes to complete testing a pull request. We need to improve this time to iterate faster.

Half of the time is spend re-building the image. Current docker version in Travis (17.03) does not support the `cache_from` directive in `docker-compose.yml` so we need to find another way to use pre-built docker images

**Comment by metadave** [comment]
https://cloud.google.com/container-registry/

**Comment by metadave** [comment]
We'll use Jenkins to build and deploy, and Travis to run PR tests.

**Comment by akatsoulas** [comment]
This issue is too old and probably resolved by now. Please open a new issue if this is not the case.
