### ISSUE TITLE
Dev app does not redirect correctly

### ISSUE THREAD

**Issue by glogiotatidis** [mozilla/kitsune#2984]
The dev instance deployed at http://sumo-dev.frankfurt.moz.works does not redirect correctly.

STR:
 - Go to http://sumo-dev.frankfurt.moz.works
 - Page loads
 - Click on 'Ask a question' (or this link http://sumo-dev.frankfurt.moz.works/en-US/questions/new)
 - Redirect error

This should be related to https://github.com/mozmeao/infra/issues/540 

My preference would be to have https://github.com/mozmeao/infra/issues/540 fixed which will benefit all apps (and also has to be done for the new portland k8s cluster) but I'm open to other suggestions to unblock this.

/cc @pmac @jgmize @metadave

**Comment by metadave** [comment]
@glogiotatidis do you mean http->https redirection?

Most of our apps have been using the [redirector service](https://github.com/mozmeao/infra/tree/master/k8s/install/services/http_to_https_redirector), which can be easily enabled by adding the NodePort to the ELB listener (although we typically set it up w/ automation).

**Comment by glogiotatidis** [comment]
> Most of our apps have been using the redirector service, which can be easily enabled by adding the NodePort to the ELB listener (although we typically set it up w/ automation).

I mean that the Django app does not get the required `X-Forwarded-*` headers which causes a redirect loop

**Comment by pmac** [comment]
@glogiotatidis I'm happy to do the same hack we're using in bedrock, basket, etc. for now, but I agree that I'd rather get the headers.

**Comment by pmac** [comment]
Filed #2986 to address this the hack way if we want it for now.

**Comment by glogiotatidis** [comment]
See also #3043

**Comment by glogiotatidis** [comment]
https://github.com/mozilla/kitsune/pull/3055
