### ISSUE TITLE
Meta Issue For Docker Install On Mac

### ISSUE THREAD

**Issue by bensternthal** [mozilla/kitsune#2989]
Parking lot for issues I am having getting the install running on mac.

### docker-compose Version Not Supported
3.4 does not appear to be supported by the version of docker I have installed (Version 17.09.0-ce-mac35, no update available). 3.3 does work

### Missing Install Docs
We don't have install docs for docker.

### What I have done thus far...
1. Change version in docker-compose file to 3.3
2. Run ```docker-compose up``` 
3. Made and drank a cup of tea.
4. Copy ```.env-dist``` to ```.env```
5. docker exec into kitsune container and run the following:
    - ```./manage.py migrate```
    - ```./manage.py createsuperuser```
    - ```./manage.py generatedata```

After the above got errors for all static content, example ```web_1            | ValueError: The file 'build/common-min.js' could not be found with <kitsune.sumo.storage.SumoFilesStorage object at 0x7f3471785fd0>.```

Tried running collect static within container.. generates error ```AttributeError: 'NoneType' object has no attribute 'strip'```

Stuck here for now, also tried this on my linode Linux machine..ran into the same problems.

**Comment by glogiotatidis** [comment]
See also #2992

**Comment by bensternthal** [comment]
Will run through the updated instructions and see if I can get it working. Much thanks.

**Comment by bensternthal** [comment]
OK  a few issues running through the new instructions.

**Docker Compose Version**
All docker compose files specify version: '3.4' which i have to set to '3.3' to get working.

**Error Building Dev**
running ```docker-compose -f docker-compose.yml -f docker/composefiles/build.yml build dev```

Results in:
```
Building dev
Step 1/2 : FROM kitsune:base-latest
ERROR: Service 'dev' failed to build: pull access denied for kitsune, repository does not exist or may require 'docker login'
```

**Create DB Specified Before Running Docker Compose Up**
Step 3 specifies running the migrate command but at this point the containers are not running. So if you run this command you get the following error.

```django.db.utils.OperationalError: (2003, 'Can\'t connect to MySQL server on \'mariadb\' (111 "Connection refused")')```

**Docker-compose up Error**
Unsure if related to not being able to build dev but if i run docker compose after building base I get a 
```kitsune_web_1 exited with code 127```

**Comment by pmac** [comment]
For the docker-compose version it looks like the best way to stay up-to-date is to install via `pip`. [Latest on pypi](https://pypi.python.org/pypi/docker-compose) is 1.17.1.

**Comment by bensternthal** [comment]
OK upgraded docker-compose.. still an issue building dev:

```
K-9:kitsune benjaminsternthal$ docker-compose -f docker-compose.yml -f docker/composefiles/build.yml build dev
Building dev
Step 1/2 : FROM kitsune:base-latest
ERROR: Service 'dev' failed to build: pull access denied for kitsune, repository does not exist or may require 'docker login'
```

**Comment by bensternthal** [comment]
@glogiotatidis would you prefer i shut this issue down and make comments in this PR:

https://github.com/mozilla/kitsune/pull/2992

**Comment by glogiotatidis** [comment]
> @glogiotatidis would you prefer i shut this issue down and make comments in this PR:
> 
> #2992

No since this is merged lets keep the discussion here
