### ISSUE TITLE
Calculate time needed to restore production database

### ISSUE THREAD

**Issue by glogiotatidis** [mozilla/kitsune#2993]
The production database is a large (~100Gb). We need to calculate the time needed to restore it in the real database engine that's going to be used in AWS.

If the time needed is above the threshold considered acceptable to do the move we should investigate other options, like incremental import of data. 

A dev import into a `db.t2.small` instance took about 30 hours. FTR the complete lithium migration took about 48 hours.

**Comment by jgmize** [comment]
We can resize the DB to a larger size prior to the restore and then back down afterwards for cost savings, but I also think the incremental import of data is worth exploring.

**Comment by jgmize** [comment]
@glogiotatidis are all of the tables InnoDB? According to https://dev.mysql.com/doc/mysql-enterprise-backup/4.1/en/mysqlbackup.incremental.html we wouldn't gain much from incrementals if not.

**Comment by metadave** [comment]
@glogiotatidis let me know when you'd like try try a new import with a resized dev node. It takes ~10-15 minutes to resize an RDS instance for the MDN DB, guessing it will take the same amount of time for SUMO.

**Comment by glogiotatidis** [comment]
Yes I'd like to try a new import. `db.m4.xlarge` sounds good.

**Comment by glogiotatidis** [comment]
We're already 20 hours in and the db import in the `db.m4.xlarge` instance is at 84%. 
 - CPU use is < 20% 
 - IO averages at ~750 Write IOPS, with a spike at ~1250 for two hours when the import began.
 - We have about 2.5G of free memory, steady since the import began
 
It seems that this is IO bounded. We discussed that maybe the attached ELB was not upgraded when we upgraded the instance to `xlarge` from `small`. 

I suggest
 1. that we spawn a new instance with the best IO we can get and measure that. This can wait (until after) Austin
 2. investigate what makes the database so big and explore potential size (and thus import) savings by skipping dumping tables that are not to be used (if any) 

@metadave feel free to downscale the instance back to its original size.

**Comment by metadave** [comment]
- dev instance has been scaled from `db.m4.xlarge` back down to `db.t2.small`.
- correction for comment above: 'ELB' -> 'EBS volume'
- we can try [Provisioned IOPS](http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Storage.html)

**Comment by jwhitlock** [comment]
Flags like ``--opt`` on the dump command can significantly speed up the restore.

https://dev.mysql.com/doc/refman/5.5/en/optimizing-innodb-bulk-data-loading.html

**Comment by glogiotatidis** [comment]
We received info from our DBAs that the `django_sessions` table is huge (~65gb) and it's unused b/c we switched to `cache` only sessions from `cache_db`  at some point this year. This table we can truncate and it will save us a lot of time.

Also the `wiki_helpfulvote` and `wiki_helpfulvotemetadata` tables weight another 24gb and it's worth investigating whether we can import the latest data from those tables initially (e.g. the last 6 months) and import the rest right after the first import has ended.

**Comment by glogiotatidis** [comment]
See also #3009
