### ISSUE TITLE
no file called "settings_local.py.dist"  in kitsune/ directory

### ISSUE THREAD

**Issue by jestemkamil** [mozilla/kitsune#3001]
Or i'm really blind, but i tried searching whole repo, although
there is actually file "settings.py" but there isn't any line of code referring to <YOUR_PASSWORD> as written in doc, I tried modifying it
and saving as settings_local.py but i failed. 

Whole problem is related to setting up env correctly according to documentation at: 
https://kitsune.readthedocs.io/en/latest/hacking_howto.html#hacking-howto-chapter

**Comment by safwanrahman** [comment]
We are using docker at this moment but the documentation has not been updated yet.

**Comment by jestemkamil** [comment]
Well, i think it should be updated ASAP, it would be helpful, especially for newcomers

-

**Comment by glogiotatidis** [comment]
Instructions on how to setup the docker dev environment are in the [README](https://github.com/mozilla/kitsune/blob/master/README.md). 

We should also update the instructions on RTFD. I filed #3004 to track this. 

btw @jestemkamil please note that currently Kitsune is under feature freeze. If you want to work on something please file an issue first so we can discuss.
