### ISSUE TITLE
I need help with account

### ISSUE THREAD

**Issue by messed-with** [mozilla/kitsune#3002]
I don't know where to leave this message. I still have hackers using my acct or making in my name. It's going on a year now. I need help. They have overlays for everything including here. By the looks of me writing this won't be seen.  
Jenn Cook

**Comment by bensternthal** [comment]
Are you having a problem with your account on the support.mozilla.org website?

If so please file a confidential bug [here](https://bugzilla.mozilla.org/enter_bug.cgi?product=support.mozilla.org&component=Users%20and%20Groups).

Github issues are for tracking work on the code base.

**Comment by messed-with** [comment]
I'm having problems with a team of hackers. I'm at the point where I guess
I'm asking where do I go? The authorities move slow, I just want my life
back...although it will never be the same after the perm embedded threat.
Can you help? Do you know someone? Forgive me for sounding so desperate,
but I am tired of fighting an entire group. Call if you can. I wish it were
as simple as one browser...that they use. I just got it yesterday to see
how it worked.

661.800.3964
Jenn
