### ISSUE TITLE
Switch user media to s3 + CDN on SCL3

### ISSUE THREAD

**Issue by glogiotatidis** [mozilla/kitsune#3003]
We want to convert legacy codebase running on SCL3 to use S3.

See also #2899 

Deployment for staging
- [x] Rsync user media to S3 (see #2948)
- [x] Backup virtualenv and settings_local.py
- [x] Update settings_local.py
- [x] Chief push
- [x] Verify that uploads and resizing work by uploading to https://support.allizom.org/en-US/gallery/images
- [x] Verify that media CDN works
- [x] Update `Document.html` (see snippet bellow) to get the new cdn urls.
- [x] Re-run rsync to make sure that we didn't miss any uploads meanwhile

Deployment for prod
- [x] Rsync user media to S3 (see #2948)
- [x] Backup virtualenv and settings_local.py
- [x] Update settings_local.py
- [x] Chief push
- [x] Verify that uploads and resizing work by uploading to https://support.allizom.org/en-US/gallery/images
- [x] Verify that media CDN works
- [x] Update `Document.html` (see snippet bellow) to get the new cdn urls.
- [x] Re-run rsync to make sure that we didn't miss any uploads meanwhile

Note that the current CDN (support.cdn.mozilla.net) serves both user media and static media and should remain active until we complete the prod migration. We *must not* make any changes to the current CDN meanwhile.

Env Variables to update
```
    AWS_S3_CUSTOM_DOMAIN
    AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY
    AWS_STORAGE_BUCKET_NAME
    AWS_S3_HOST
    MEDIA_URL
```

**Comment by glogiotatidis** [comment]
To update `Document.html`

```python 
for doc in Document.objects.exclude(html=''):
    doc.html = doc.content_parsed
    doc.save()
```

**Comment by glogiotatidis** [comment]
See #2983

**Comment by safwanrahman** [comment]
I think it would be better to take SUMO to readonly mode for while.

Moreover, run a custom migration inorder to update the html of the documentation

**Comment by glogiotatidis** [comment]
Thank you for your input @safwanrahman. I prefer to trigger the html regeneration myself instead of during the push.

**Comment by glogiotatidis** [comment]
This is live to as of today 2017-01-17 14:14 UTC

Currently running a rsync to S3 to make sure we didn't leave anything behind. Uploads appear to be working fine. Initial tests to show any missing images.

**Comment by glogiotatidis** [comment]
A week in production and everything operates smoothly. thanks everyone!
