### ISSUE TITLE
Establish MySQL replication from SCL3 -> RDS

### ISSUE THREAD

**Issue by metadave** [mozilla/kitsune#3006]
https://bugzilla.mozilla.org/show_bug.cgi?id=1429466
https://bugzilla.mozilla.org/show_bug.cgi?id=1429911

**Comment by glogiotatidis** [comment]
See also #3009

**Comment by metadave** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1429466#c8:

> Request an IP Allocation - we usually give a /24 for typical VPCs or /16 for larger ones... this is to avoid IP overlap
> Request IPSec/BGP peering (specifying which DC[s]) - we will give you IP(s) to terminate tunnels to, and IP(s) to BGP peer with... you will send us the AWS generated config
> Request firewall ACLs - From (hostname & IP) -> To (hostname & IP) @ App (ports/protocols) (ie: aws-sql01.eus-west.mozilla.com/10.191.10.10 -> some-mysql01.db.scl3.mozilla.com/10.22.xx.xx @ MySQL (TCP & UDP 3306)

See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1431493

**Comment by glogiotatidis** [comment]
Also https://bugzilla.mozilla.org/show_bug.cgi?id=1436796
