### ISSUE TITLE
Test READ_ONLY Mode of Kitsune in SCL3 and AWS

### ISSUE THREAD

**Issue by glogiotatidis** [mozilla/kitsune#3011]
Kitsune sports a READ_ONLY mode. Test and verify that it's working as advertised. 

This will be used during the migration:

 - Both SCL3 and AWS will be switched to READ_ONLY
 - Gradually we'll shift the traffic to AWS.
 - After AWS stabilizes we'll enable writes again

- [ ] Verify that READ_ONLY in SCL3 works
- [ ] Verify that READ_ONLY in AWS works

**Comment by glogiotatidis** [comment]
See https://github.com/mozilla/kitsune/pull/3019

**Comment by metadave** [comment]
Should this be titled `Test READ_ONLY Mode of Kitsune in SCL3`?

**Comment by glogiotatidis** [comment]
> Should this be titled Test READ_ONLY Mode of Kitsune in SCL3?

The original idea was to test if the READ_ONLY mode is a thing and if it works with the 12factorized settings. Now that we did that in #3019, I'll rename this issue to `... in SCL3 and AWS` as you correct suggest and move it to the backlog to make it happen

**Comment by metadave** [comment]
before migration, do we need a traffic policy to control percentages of traffic to SCL3/AWS for READ_ONLY mode testing, or will we just test SCL3 followed by AWS?

**Comment by glogiotatidis** [comment]
Yes a traffic policy is what we need. I'm drafting a migration plan for discussion which will surface other infra needs as well. Thanks!
