### ISSUE TITLE
Database Architecture

### ISSUE THREAD

**Issue by glogiotatidis** [mozilla/kitsune#3012]
- Kitsune uses MySQL (See #2937) on SCL3.
 - On AWS Kitsune will running in multiple regions
 - Since all visitors can potentially write on the database (from the simple task to subscribe to a question to the more complex editing and managing of KB articles), we can't have an admin only domain as we do with other apps. We want visitors on `support.mozilla.org` to be able to write to database and thus we need a database solution which supports writes from multiple locations. 
 - Recently AWS announced Aurora Multi Master support. Aurora is MySQL compatible so we could "just switch" with the downside of getting more locked-in into AWS.  Either way Aurora only supports multi-AZ Multi Master at the moment (2018-01-15) with a plan to support multi-Region in the future. We can re-eval when multi-Region becomes available but for the time being we need an alternative plan.

## Suggested Database Architecture (2nd iteration)

 - One Multi-AZ RDS Database in Oregon running MySQL
 - One Multi-AZ RDS Database in Frankfurt, replicating Oregon's DB
 - Replication from SCL3 to AWS
   - RDS will be promoted to master and the replication will stop when we flip the switch to AWS
 - SUMO will run on two different k8s clusters, in two different AZs but in the same AWS region
   - This will allow having the same RDS instance, while protecting as from cluster level and AZ level catastrophic failures
   - In the case of a AWS Region failure, an automatic failover (using Route 53 Traffic Policies) will route traffic to an App instance running on Frankfurt based k8s cluster. This cluster will read from the Frankfurt based RDS database replica.
   - We can manually upgrade the replica to master and make Frankfurt a r/w instance.

 

![image](https://user-images.githubusercontent.com/584352/35628242-f4289d20-06a3-11e8-86de-e6b6659cd314.png)

**Comment by glogiotatidis** [comment]
In yesterday's DB mtg the following happened:

 - We agreed continue fwd with the plan to establish replication between SCL3 and AWS
 - We agreed to develop and deploy the infra needed to replicate RDS from Oregon to other regions
 - We agreed to develop and deploy Kitsune backing services (ElasticSearch, ElasticCache) in more than one regions
 - We agreed to deploy Kitsune in more than one regions

 - There were concerns expressed about the stability and performance of the of the link to the Master database from other regions. It's suggested the we initially we keep other regions as hot spares and focus on developing a automatic fail-over to a hot spare in case Oregon dies.
 - It's mentioned that the code already has and uses Pinning MultiDB router in SCL3 and it's ready to be tested with a Master DB in other region. The missing piece is the DB tunnel across the regions.
 - How we will open the tunnel between the different regions remains an open question. We briefly discussed about either:
   a. Creating a VPN tunnel between the regions. 
   b. Exposing the Master DB to the Internet with TLS and accepting connections from specific IPs only.
 - It's suggested that we test Kitsune to see how the app behaves if the write database disappears.

@mozilla/sumo I believe I captured our discussion fully. Please correct / append my sayings as required.

**Comment by metadave** [comment]
> Can we use MariaDB over MySQL and still get replication from SCL3 to AWS to work?
https://bugzilla.mozilla.org/show_bug.cgi?id=1429466#c9

It might be best to stick with MySQL for the initial migration.

--- 
> How we setup the tunnel between the Regions?

- [inter-region VPC peering](https://aws.amazon.com/about-aws/whats-new/2017/11/announcing-support-for-inter-region-vpc-peering/) is too limited for us to use, as it is only available in Virginia, Oregon, Ireland and Ohio regions.

- We have to keep in mind any extra costs with inter-region communications:
https://aws.amazon.com/answers/networking/aws-multiple-region-multi-vpc-connectivity/

- [AWS VPN connections](https://docs.aws.amazon.com/AmazonVPC/latest/NetworkAdminGuide/Introduction.html) appear to require software/hardware on the "customer side". There isn't an out of the box AWS VPN service that we can use, or I can't find it in all the VPC/VPN docs.

Here's a way to run EC2 instances with Openswan that connect VPCs:
- https://aws.amazon.com/articles/connecting-multiple-vpcs-with-ec2-instances-ipsec/

**Comment by metadave** [comment]
also, I ❤️ your diagrams above

**Comment by glogiotatidis** [comment]
> Can we use MariaDB over MySQL and still get replication from SCL3 to AWS to work?
>     https://bugzilla.mozilla.org/show_bug.cgi?id=1429466#c9
> 
> It might be best to stick with MySQL for the initial migration.

Agree

**Comment by glogiotatidis** [comment]
Thank you for your research on potential tunnel solutions @metadave.

Given the complexity of the setting up a VPN tunnel, the needs for HA with multiple EC2 instances and the fact the we only need to access one host (the RDS db) I suggest we focus on IP limiting the access.

Here's an idea:
 - Assign a Public IP to the Master RDS instance
 - Limit the access to the MySQL Port to specific IPs with a Security Group
 - A lambda function listens for HTTP requests with a specific key and -if key valid- adds the requesting IP to the above Security Group
 - On start up kitsune curls the Lambda's URL and thus gets its IP to the Security Group 
 - Kitsune can use pmac's [`urlwait`](https://github.com/pmclanahan/urlwait/) to wait for the DB to become available. In most cases since we're not changing IPs that often the instance would launch instantly.
 - We can manually trigger cleanup old IPs from the Security Group with a script.

Thoughts?

**Comment by metadave** [comment]
I'd skip Lambda and just use boto3 from Python to update security groups.

**Comment by metadave** [comment]
I want to propose an alternate architecture for consideration.

We can run 2 K8s clusters in the same region (us-west-2) in different availability zones as the "primary clusters". Both K8s clusters would use the same RDS multi-AZ instance: there would be no changes required to Kitsune to get this to work. If we lose K8s or 1 AZ in us-west-2, the other AZ can scale up to take additional load automatically (via traffic policy/health checks/autoscaler). MySQL in RDS will automatically failover to a different AZ (in the same region) should an error occur. It's also easy to manually initiate an RDS failover to a different AZ for testing, but in general, AWS takes care of RDS failover for us.

Next would be a standy cluster in Frankfurt or Ireland. We'd setup RDS replication to this cluster, and should both clusters in us-west-2 fail, the traffic policy (using health checks) could automatically route traffic to this read-only region. In the event of a catastrophic failure in us-west-2, the standby region read-replica can be promoted to a master and we could continue running until one or both us-west-2 clusters are back online.

I like this approach because it gives us multi-AZ failover with minimial effort, it reduces complexity at the application level, and we even get a standby region if us-west-2 dies. The same approach could be used for MDN.

![2018_10_22_sumo_db](https://user-images.githubusercontent.com/58244/35255262-32f8c92e-ffbc-11e7-98e8-3ceefad6df39.png)

**Comment by glogiotatidis** [comment]
> I'd skip Lambda and just use boto3 from Python to update security groups.

Yes, we can totally do that and it's simpler.

**Comment by glogiotatidis** [comment]
We discussed @metadave's [suggestion](https://github.com/mozilla/kitsune/issues/3012#issuecomment-359654680) we concluded that's a good architecture that

 - Allows Multi Homing Kitsune, in two different kubernetes clusters in two different AZs albeit in the same region
 - Allows for automatic fail-over to a hot spare in a different region, which we can manually promote to r/w
 - Takes inter region peering and database connections out of the picture along with associated concerns.

I'll update the original post with this architecture with more details, to keep it on the top.

Thanks @metadave and @mozilla/sumo for this work. 🍻

**Comment by glogiotatidis** [comment]
**This is not the final architecture. It's saved here for historical reason. See top post for 2nd iteration.**

## Suggested Database Architecture (1st iteration).

 - Replication in RDS using MariaDB is known to work well. 
 - The Arch defines:
   - A DB in **Oregon** as the **Master** database
   - Databases in  **other regions** (currently Frankfurt and Tokyo) as **Read Replicants** of the Master database
 - Kitsune instances in **all regions** use [django-multidb-router](https://github.com/jbalogh/django-multidb-router) in **Pinning Mode** to route write db operations to **Oregon** while read operations get routed to the nearest Read Replica.
 - We need a secure tunnel between Oregon and other regions, using Inter-Region VPC Peering where supported or other method where not supported.

![prod after](https://user-images.githubusercontent.com/584352/34943770-bc5a3e8a-fa05-11e7-9ed8-1b8667413846.jpg)


### Pre AWS Migration - Development Architecture

 - To develop and test the architecture we want to setup a minimal version with a Master Database in Oregon and a Read Replica in Frankfurt.
 - The Master Database will get populated with a recent anonymized SQL dump. Ideally we want to copy what we have now in `sumo-dev` database in Frankfurt.
 - The secure tunnel between Frankfurt and Oregon needs to be established
 - After completing AWS migration this infra will be shutdown and Kitsune dev instances will switch to using the RDS instances defined in the next section.

![dev](https://user-images.githubusercontent.com/584352/34943422-42843f12-fa04-11e7-9a40-f2b71efa877a.jpg)
 

### Pre AWS Migration - Production and Staging Architecture
 
 - SUMO database in big and takes some time to get imported #2993 
 - To reduce the time needed to migrate from SCL3 to AWS we're working on getting Data Replication going between the two datacenters #3006 
 - The Arch defines:
   - An RDS instance in Oregon which acts as Read Replica of SCL3
   - Two RDS instances in Frankfurt and Tokyo that act as Read Replicas of Oregon Read Replica
 - When it's time to flip the switch to AWS, Oregon will become Master and the other DBs will remain Read Replicas
 - Bonus points if we setup SCL3 to become Read Replica of AWS,  as a fallback plan.
 - We want to setup all three DBs (Oregon, Fra, Tokyo) from now so we can host a Read Only version of the site as soon as possible.
 - We also want to setup the tunnel  between Fra, Tokyo and Oregon asap, so it's ready to accept connections when Oregon becomes master.

![prod](https://user-images.githubusercontent.com/584352/34944035-b0388296-fa06-11e7-81e3-71445bf850a3.jpg)

Questions:
 - Can we use MariaDB over MySQL and still get replication from SCL3 to AWS to work?
We agreed to keep MySQL

 - How we setup the tunnel between the Regions?
There're ways to do so (see comments in this issue) but also serious concerns where expressed.
