### ISSUE TITLE
Search Architecture

### ISSUE THREAD

**Issue by glogiotatidis** [mozilla/kitsune#3013]
* Kitsune uses ElasticSearch v2.4
* On AWS Kitsune will run on multiple regions
* ElasticSearch data don't have to be persistent and can be regenerated completely from database.

## Architecture (3rd iteration)

 - One Multi-AZ ElasticSearch cluster in Oregon which will be used by both k8s clusters in Oregon running Kitsune
   - Documents in this cluster will be live indexed as changes happen using django signals. This may change in the future as suggested in #3031 
 - One Multi-AZ ElasticSearch cluster in Frankfurt
   - Documents in this cluster will be updated in regular intervals with jobs scheduled by a locally running APScheduler instance and therefore keeping the index ready to be used in the case of a failover. This work is tracked in #3030

**Comment by glogiotatidis** [comment]
Our elastic search provider (elastic.co) creates instances with public IPs. Therefore instead of having the region local App instances update only the region local ES instance and signal the other App regions to do the same, each App instance can directly update all ES instances.

The update of ES each triggered by Django's `post_save` signals, so for example 

**when a new Document gets saved in Frankfurt**
 1. Kitsune Fra connects to RDS Oregon and saves the doc in database
 2. Kitsune Fra creates 3 Celery jobs to update that document in ES index, one for ES running in Fra, one for ES in Oregon and one for ES in Tokyo.

**Comment by glogiotatidis** [comment]
@mozilla/sumo can you please provide comments on the [second iteration of the architecture](https://github.com/mozilla/kitsune/issues/3013#issue-288945169)?

**Comment by pmac** [comment]
I have a couple thoughts:

1. I initially thought that option 1 (HTTP pings from Oregon) would be too unreliable. But I'm now thinking that it's possible that it'll be okay since I'd expect said pings to happen quite frequently, and if one or two were missed then it'd be okay; especially if we develop the view that returns the updated docs that the other regions can query. In that case missing a ping would just mean that it'd get it on the next one. We might need an ACK ping back to Oregon though to clear what it got and reset for the next one.
2. Keeping all of the machinery local to the non-Oregon regions seems most reliable and simple. We'd just have to store the `last_updated` timestamps somewhere (Redis probably) and have a periodic task look for new stuff and update the indexes. That seems the most straight-forward and therefore most reliable IMHO.

**Comment by metadave** [comment]
> Elasticsearch 2.4 reaches end of life (EOL) on February 28, 2018

https://github.com/mozmeao/infra/issues/666#issue-278545959

**Comment by metadave** [comment]
1. > Each region running Kitsune runs its own ES cluster, provided by elasti.co

There may not be a direct mapping of elastic.co supported regions with regions we'll be deploying Kitsune to. From the "create cluster" screen of elastic.co:

![elastic_cloud](https://user-images.githubusercontent.com/58244/35162435-5ce2fb90-fd11-11e7-871d-b444b334e149.png)

2. Operationally, I'd be interested in something that shows last sync time for each ES cluster. Would we alert if an ES cluster is "too old"?

**Comment by glogiotatidis** [comment]
> Elasticsearch 2.4 reaches end of life (EOL) on February 28, 2018
> 
> mozmeao/infra#666 (comment)
> 
> edit: of course, the linked github issue # is evil.

of course. And yes, good point. We'll take advantage of the extended elasti.co support and upgrade libs and ES version after the migration.

**Comment by glogiotatidis** [comment]
> Each region running Kitsune runs its own ES cluster, provided by elasti.co
> 
> There may not be a direct mapping of elastic.co supported regions with regions we'll be deploying Kitsune to. From the "create cluster" screen of elastic.co:

Interesting. Do you think it's still worth getting ES clusters closer to the App instances, like Ireland ES for Frankfurt App instances? I believe so and if we agree I'll update the wording to 

`Each region running Kitsune runs its own ES cluster in the same or another geographically close, provided by elasti.co`

**Comment by glogiotatidis** [comment]
FTR we index the following Kitsune objects:
 1. User Profiles
 2. Questions and Answers
 3. Wiki documents 
 - ~~Customer Care replies~~ (we don't care about this since we're shutting down AoA #2916)

**Comment by pmac** [comment]
Thanks so much for this excellent description and illustration! I totally get it and am on board! 🚂 Let’s do it.

Also: color illustrations FTW 🎉

**Comment by metadave** [comment]
Are we still planning on a Tokyo ES cluster?

**Comment by glogiotatidis** [comment]
> Are we still planning on a Tokyo ES cluster?

No

**Comment by glogiotatidis** [comment]
This is not the final architecture. It's saved here for historical reasons. See top post for 3nd iteration.

## Architecture (second iteration)

Our elastic search provider (elastic.co) creates instances with public IPs. Therefore instead of having the region local App instances update only the region local ES instance and signal the other App regions to do the same, each App instance can directly update all ES instances.

The update of ES each triggered by Django's `post_save` signals, so for example 

**when a new Document gets saved in Frankfurt**
 1. Kitsune Fra connects to RDS Oregon and saves the doc in database
 2. Kitsune Fra creates 3 Celery jobs to update that document in ES indices, one for ES running in Fra, one for ES in Oregon and one for ES in Tokyo.

**Comment by glogiotatidis** [comment]
@metadave can you please confirm that elasti.co provides MultiAZ ElasticSearch clusters?

**Comment by metadave** [comment]
elastic.co allows us to select 1, 2 or 3 "data centers", but there isn't a description of what a DC is in this case. Since we're allowed to pick only 1 primary region, my guess is that 1-3 DC's == 1-3 AZs in a given region. Would you like me to contact elastic support to clarify?

https://www.elastic.co/cloud/as-a-service/pricing

**Comment by glogiotatidis** [comment]
> elastic.co allows us to select 1, 2 or 3 "data centers", but there isn't a description of what a DC is in this case. Since we're allowed to pick only 1 primary region, my guess is that 1-3 DC's == 1-3 AZs in a given region. Would you like me to contact elastic support to clarify?
> 
> https://www.elastic.co/cloud/as-a-service/pricing

we practically want HA and their page clearly says that 2 and 3 datacenters are for HA with automatic failover. That's good enough for me, thanks
