### ISSUE TITLE
Deploy to vanilla k8s

### ISSUE THREAD

**Issue by glogiotatidis** [mozilla/kitsune#3014]
Convert Kitsune from Deis v2 to vanilla Kubernetes deployment.

**Comment by glogiotatidis** [comment]
@metadave @jgmize do you have time to PR with a basic deployment and service for k8s to kickstart this process?

**Comment by metadave** [comment]
Do you have something working in Deis yet? If so, I can extract out the deployment and tweak it. Otherwise, it's mostly just filling in the image and environment variables/secrets.

**Comment by jgmize** [comment]
@metadave https://sumo-dev.frankfurt.moz.works/en-US/ appears to be working :)

@glogiotatidis FYI you can get dump of the deployments and svc yaml with the steps in https://github.com/mozmeao/infra/pull/688#issuecomment-356761908 (s/bedrock-prod/sumo-dev/) to see what it looks like before @metadave's forthcoming tweaks :)

**Comment by glogiotatidis** [comment]
Useful, i'll try this. thanks!

**Comment by metadave** [comment]
You'll also need the correct version of the secrets that are referenced in the deployment:

```
kubectl -n sumo-dev get secrets
# pick the correct version #
kubectl -n sumo-dev get secret <secret_name> -o yaml > sumo-secrets.yaml
```

Don't post the results on Github!

**Comment by metadave** [comment]
actually, I'm working on this right now, I'll post a PR in an hour or so.

**Comment by metadave** [comment]
https://github.com/mozmeao/infra/pull/713

**Comment by glogiotatidis** [comment]
https://github.com/mozilla/kitsune/pull/3034
