### ISSUE TITLE
SUMO AWS monitoring setup

### ISSUE THREAD

**Issue by metadave** [mozilla/kitsune#3015]
We'll need to setup dashboards in New Relic/Datadog/etc.

**Comment by metadave** [comment]
>New Relic Servers and the legacy alerting features will reach End-Of Life (EOL) on May 15th, 2018 >for those customers who have a paid subscription to one or more of our products. For customers >who do not have a paid subscription to one or more of our products, the EOL date will be >November 14, 2017. Also, New Relic Alerts will be removed on November 14, 2017 from accounts >that do not have a paid subscription.

https://discuss.newrelic.com/t/important-upcoming-changes-for-new-relic-servers-and-legacy-alerting-features/49474

**Comment by akatsoulas** [comment]
Probably this is no longer relevant. Please re-open if this is not the case.
