### ISSUE TITLE
[Bug 396792] Intermittant RSS Issue

### ISSUE THREAD

**Issue by bensternthal** [mozilla/kitsune#3017]
Intermittent issue with RSS:

https://bugzilla.mozilla.org/show_bug.cgi?id=1396792

**Comment by bensternthal** [comment]
@pmac any chance you can take a look at this sometime this week?

**Comment by pmac** [comment]
Sure.

**Comment by pmac** [comment]
Progress: I've narrowed it down to something to do with the Meinheld Gunicorn worker we're using. The feeds work fine using both Django's development server and the default `sync` Gunicorn worker. Investigation continues.

**Comment by pmac** [comment]
Feeds also work fine with the officially supported `gevent` worker (which uses `greenlet` like Meinheld). I'm not sure how the rest of the site would work with the `gevent` worker, but it might be worth a shot. Meinheld's maintenance is slow-to-none as well (last release in Nov 2016), so that's another reason to try something else.

Thoughts @jgmize @metadave @glogiotatidis @jpetto ?

**Comment by pmac** [comment]
I could put my changes in a branch, deploy that to one of the stage instances (maybe frankfurt) and we could test if you think it's worth it. I'm also still looking for issues in Meinheld to see if I can explain the behavior. I'm still not sure what makes the feed views special in this way.

**Comment by pmac** [comment]
PR above added for experiment with `gevent` Gunicorn worker class.

**Comment by jgmize** [comment]
While we may not have tested gevent with kitsune, we did with snippets-service and ran into errors. If a different gunicorn worker resolves the rss issue but introduces other errors on other urls, then we could put a path based ingress that directs just the rss urls to a new service backed by a separate deployment if needed.

**Comment by pmac** [comment]
> It might be worth building a release of our own from the master branch, which has commits from this year.

I considered that, but I'm really quite uncomfortable with it. I don't think the changes are related to our issues, and that would mean running an unreleased version of a beta server... I just don't think it's a good idea.

**Comment by jgmize** [comment]
meinheld  is far from perfect, but it's been more performant and reliable than any of the other gunicorn workers I've tried, including gevent. I've tested gevent with several projects over the years, and each time it created more problems than it solved, often due to its monkeypatching of the standard library. Feel free to test it again though, it's been a while since I tried it last and things might be better now.

**Comment by pmac** [comment]
I've played with uWSGI a bit today. It's another great WSGI server and has more options than Gunicorn, many of which could be useful to us. I got it working great locally, but every time I try to deploy it (in sync or async mode) all I get is:

```
$ curl -I https://stage-frankfurt.sumo.moz.works/en-US/
HTTP/1.1 503 Service Unavailable: Back-end server is at capacity
```

Only running 2 workers. I don't know what the deal is. Papertrail for the stage app in frankfurt is so full of health checks that it's not of much use. I'll play with it some more next week.

**Comment by metadave** [comment]
```
curl -I https://stage-frankfurt.sumo.moz.works/en-US/
```
returns an `HTTP/1.1 200 OK` for me

**Comment by metadave** [comment]
I think we would need a load test/benchmark between current and future worker implementations.

**Comment by pmac** [comment]
> returns an HTTP/1.1 200 OK for me

I re-deployed the default image before posting here since it was basically down.

**Comment by pmac** [comment]
> I think we would need a load test/benchmark between current and future worker implementations.

Agreed. I'm just looking for a configuration that works for now. Then we'll need a lot of testing for both accuracy and performance.

**Comment by metadave** [comment]
if you see `Back-end server is at capacity` again, wait ~10 minutes to see if the cluster automatically scales up.

**Comment by pmac** [comment]
> if you see Back-end server is at capacity again, wait ~10 minutes to see if the cluster automatically scales up.

It happened so immediately I was guessing it had something to do with processing or memory limits. I no longer had the time nor patience to work on it today so I reverted. I'll ping you next week to see if we can figure something out. I'm also planning on doing some more research into the current state-of-the-art for I/O heavy Python/Django web app deployment.

**Comment by pmac** [comment]
I think I'm also going to give [mod_wsgi-express](https://pypi.org/project/mod_wsgi/) a try.

**Comment by jgmize** [comment]
![screenshot_2018-07-07 a million requests per second with python freecodecamp](https://user-images.githubusercontent.com/161718/42412236-e3944464-81cd-11e8-8f47-05dbf2a50c93.png)


from https://medium.freecodecamp.org/million-requests-per-second-with-python-95c137af319

**Comment by pmac** [comment]
Also that article is 1.5 years old and Meinheld has seen 0 releases since.

**Comment by pmac** [comment]
As you can see in the PR that closed this, we figured out what was causing the issues with Feeds + Meinheld. I'm still not sure why exactly this was an issue, but we've resolved it for now without having to switch WSGI servers. This situation could turn up again however, so we should continue investigating WSGI servers after we're done with #3177.
