### ISSUE TITLE
Search as you type is too aggresive

### ISSUE THREAD

**Issue by glogiotatidis** [mozilla/kitsune#3024]
Search as you type in the default search box starts searching for documents from the first character which results in higher App and ElasticSearch use with questionable gains. 

Change the code so that it requires at least X number of characters to be typed and/or increase the wait time between the last pressed key to start of the search. Ideally make those variables configurable in the settings so we can experiment to find the best UX / Infra cost fraction.

**Comment by akatsoulas** [comment]
The search is being redesigned as part of  the responsive redesign milestone.
