### ISSUE TITLE
Traffic Log Analysis

### ISSUE THREAD

**Issue by glogiotatidis** [mozilla/kitsune#3025]
## Traffic analysis of 24 hours on 2017-05-11

```
$ zcat support.mozilla.org.access_2017-05-11-*.gz | grep -c '"GET /'
23013921

$ zcat support.mozilla.org.access_2017-05-11-*.gz | grep -c '"POST /'
1215420

$ zcat support.mozilla.org.access_2017-05-11-*.gz | grep -c '"PUT /'
24

$ zcat support.mozilla.org.access_2017-05-11-*.gz | grep -c '"DELETE /'
0

$ zcat support.mozilla.org.access_2017-05-11-*.gz | grep -c '"HEAD /'
23405

$ zcat support.mozilla.org.access_2017-05-11-*.gz | grep  -c '"GET /1/'
1320366

$ zcat support.mozilla.org.access_2017-05-11-*.gz | grep -c '"GET /static/'
208021

$ zcat support.mozilla.org.access_2017-05-11-*.gz | grep -c '"GET /media/'
18140
```

**Total requests:** 24,252,746
**Requests Per Minute:** 16.8k

**Percentage of POST Operations:** 5.01% 
Requests Per Minute: 0.84k

**Percentage of /1/ Requests:** 5.44%
Requests Per Minute: 0.92k

**Percentage of /static/ Requests:** 0.86%
Requests Per Minute: 0.14k

**Percentage of /media/ Requests:** 0.07%
Requests Per Minute: 0.01k

Both `/static/` and `/media` are behind a CDN.

Note that these number are before the migration to the third party. Today we are experiencing noticeable reduction in traffic due to the migration and rollback. I filed [bug 1431635](https://bugzilla.mozilla.org/show_bug.cgi?id=1431635) to get more recent logs to analyze

**Most used URLs:**
```
$ zcat support.mozilla.org.access_2017-05-11-*gz |  grep  '"GET /'  | cut -d ' ' -f 7 | sort | uniq -c | sort -rn | head
7214959 /en-US/
6414456 /
 319186 /kb/get-started-firefox-overview-main-features
 247005 /en-US/kb/insecure-password-warning-firefox?as=u&utm_source=inproduct
 144351 /1/firefox/53.0.2/WINNT/en-US/insecure-password
 131593 /en-US/kb/get-started-firefox-overview-main-features
 128656 /kb/what-does-your-connection-is-not-secure-mean
 107319 /en-US/products/thunderbird
  90408 /zh-CN/kb/insecure-password-warning-firefox?as=u&utm_source=inproduct
  77046 /static/sumo/fonts/MetaWebPro-Bold.ff98af2fcd50.ttf?v=1

```

**Comment by messed-with** [comment]
What is it about my accounts that you want? Cant i just have some peace? Please. Let me do what i want without redirects, 20 p/w CHANGES a day, the fake web sites, the threats (3 now), claiming to devs and app owners that you had my permission when you do not. I've been messed with for almost a year. Move on please. You achieved one of your goals...my life will never be the same. As far as the notoriety you told me was the reason you guys chose me, I'm easy mark. Old & dying. I wish we could've co-existed like I asked. You're no hacker. Hacker are here to help folks like me, not tear lives apart one code at a time. Forgive all the intrusions...at least you had to work harder. Just please go away.

**Comment by metadave** [comment]
Nice, do we have any idea as to how many bytes on average we're transferring for each type of request?

**Comment by glogiotatidis** [comment]
> Nice, do we have any idea as to how many bytes on average we're transferring for each type of request?

I started this issue as part of the database discussions to identify the number of POSTs (i.e. number of db writes). Since we concluded the DB discussion my questions have been answered.

If we want to further process the logs to find bytes per request, I'll keep this issue open and get the more recent logs. What do you think @metadave?

**Comment by metadave** [comment]
If it's not too much trouble, the more data we have to help us make architectural decisions, the better.

**Comment by glogiotatidis** [comment]
fiy I've fresh traffic logs from SCL3 in my hands.
