### ISSUE TITLE
Bring Celery to AWS

### ISSUE THREAD

**Issue by glogiotatidis** [mozilla/kitsune#3026]
Kitsune executes many tasks using celery. Create whatever is needed (bash scripts, procfile entries, monitors etc) to bring it to AWS.

**Comment by metadave** [comment]
Do you need additional Redis support for a Celery backend?

**Comment by glogiotatidis** [comment]
> Do you need additional Redis support for a Celery backend?

nope we just use a different db in the current redis. thanks!
