### ISSUE TITLE
Use modified timestamps for updating search indexes

### ISSUE THREAD

**Issue by pmac** [mozilla/kitsune#3031]
We should store and use modified timestamps to decide what to add/update in the search indexes instead of ORM signals. In #3030 I suggested we work around said signals not working across regions by simply indexing the latest 2 days worth of modifications every night. This issue represents a plan for better handling of search indexing that should work in both read-only and read-write regions.

I propose that we store the timestamp of the latest modified document (Article, Question, etc.) in the cache (Redis) per index. In this way we can run a job as frequently (or infrequently in the case of the hot-spare region) as we'd like, and it will be able to query for modifications that have occurred since the last modification, update the index, and store the new timestamp. This job can be run via celery or a container running a cron-like system (APScheduler e.g.) as often as we'd like, and it will work regardless of that region's ability to write to the primary database.

This should not block our move to AWS, but I think it would make our AWS infra more reliable if we were to get it done as soon as we're able after the migration.

**Comment by glogiotatidis** [comment]
https://github.com/mozilla/kitsune/pull/3088
https://github.com/mozilla/kitsune/pull/3103
