### ISSUE TITLE
Improve email sending

### ISSUE THREAD

**Issue by glogiotatidis** [mozilla/kitsune#3038]
It's known that some emails sent from Kitsune get missing (bug [1204515](https://bugzilla.mozilla.org/show_bug.cgi?id=1204515) and others).

This is a tracker issue to:

 - [ ] Upgrade [django-tidings](https://github.com/mozilla/django-tidings) and other email sending related libraries
 - [ ] Verify that we send one email per recipient as suggested by SES docs
 - [ ] Verify that current SES limits (50k emails per 24 hours and 14 emails / seconds) are good
 - [ ] Add DKIM verification in SES
 - [ ] Develop ways to track and remove bouncing emails
    - SES supports sending notifications to SNS about bounces, complains and deliveries.
 - [ ] Develop ways for users to completely unsubscribe from Kitsune emails from the website and from inside the email (link clicking, gmail integration, etc)

Before taking on a task please file a separate issue for the task and link it here.

**Comment by glogiotatidis** [comment]
DKIM bug https://bugzilla.mozilla.org/show_bug.cgi?id=1434862

**Comment by akatsoulas** [comment]
this is no longer relevant
