### ISSUE TITLE
Remove all references to troubleshooter addon

### ISSUE THREAD

**Issue by glogiotatidis** [mozilla/kitsune#3042]
In settings.py we have a url pointing to a Troubleshooter addon ([source code](https://github.com/mozilla/kitsune/blob/bd0db60e4394619f1e1843bdb4bc7f4b69349ef1/kitsune/settings.py#L931-L934)) which currently returns 404.

This Troubleshooter addon still a thing? If so we need to point this URL somewhere valid, otherwise remove all code references.

**Comment by glogiotatidis** [comment]
@madasan maybe can you shed some light maybe?

**Comment by NoahSUMO** [comment]
Hey Giorgos! I know about this Troubleshooter addon. I should really be checking the Kitsune issues filed here but didn't realize how active your team was here. Apologies!

This Troubleshooter addon was added a few years ago into our forum product to collect data from Firefox's about:support & insert it into questions posted by the user. Users were required to install the experimental addon back then in order for us to receive their data. But now we use a [in-product about:support API](https://bugzilla.mozilla.org/show_bug.cgi?id=1079563) in Firefox that allows us to retrieve the about:support data in a JSON form. So it should be safe to remove all references to this addon. @philipp-sumo Does this sound correct to you?

**Comment by philipp-sumo** [comment]
yes, that's correct - the troubleshooter addon was/is only needed for users below firefox 36 wanting to provide their system details during the ask-a-question-flow in the forum.

**Comment by glogiotatidis** [comment]
Thanks for the extra info! we shall remove then.

**Comment by akatsoulas** [comment]
This has been tackled in this issue.
https://github.com/mozilla/sumo-project/issues/221
