### ISSUE TITLE
Setup weighted traffic policies for read-only prod test

### ISSUE THREAD

**Issue by metadave** [mozilla/kitsune#3125]

**Comment by jgmize** [comment]
Proposed policies, to be tested in descending order:
- SCL3
  - 63.245.213.32
    - sumo.external.zlb.scl3.mozilla.com
    - use IP to reduce latency
    - confirmed dedicated IP not expected to change without notice
  - no health check
- SCL3/Oregon
  - 95/5 SCL3/Oregon
    - 5% of total traffic split 50/50 between oregon-{a,b}
      - 95/2.5/2.5
    - health check fall back to SCL3
  - 90/10 SCL3/Oregon
    - 10% of total traffic split 50/50 between oregon-{a,b}
      - 90/5/5
    - health check fall back to SCL3
  - 80/20 SCL3/Oregon
    - 20% of total traffic split 50/50 between oregon-{a,b}
      - 80/10/10
    - health check fall back to SCL3
  - 50/50 SCL3/Oregon
    - 50% of total traffic split 50/50 between oregon-{a,b}
      - 50/25/25
    - health check fall back to SCL3
  - 20/80 SCL3/Oregon
    - 20/40/40
    - health check fall back to SCL3
  - Oregon / SCL3 failover
    - 100% traffic routed to oregon, split 50/50 between oregon-{a,b}
    - health check fall back to SCL3
- Oregon/Frankfurt
  - Oregon/Frankfurt failover
    - 100% traffic routed to oregon, split 50/50 between oregon-{a,b}
    - health check fallover to Frankfurt
  - 95/5 Oregon/Frankfurt
  - 90/10 Oregon/Frankfurt
    - 45/45/10 oregion-{a,b}/frankfurt
  - 80/20 Oregon/Frankfurt
    - 40/40/20 oregion-{a,b}/frankfurt
  - 50/50 Oregon/Frankfurt
    - 25/25/50 oregion-{a,b}/frankfurt
  - 80/20 Frankfurt/Oregon
    - 80% of traffic to Frankfurt
  - Frankfurt/Oregon failover
    - 100% traffic to Frankfurt
    - failover to Oregon clusters

**Comment by metadave** [comment]
I took a shot at creating new policy versions 11-15 for SCL3/Oregon testing. @jgmize can you take a look when you have a chance.
