### ISSUE TITLE
No e-mail confirmation link for new account (dev instance)

### ISSUE THREAD

**Issue by madasan** [mozilla/kitsune#3128]
Steps to reproduce
Go to https://dev.sumo.moz.works/ and try to create new account.
I get message that account has been created and need to check my email for confirmation link.

Expected behaviour
Confirmation link should be received via email

Actual behaviour
No confirmation link is received (inbox or spam folder). If I try to create another account with the same email address I get the message "This email address i already in use"

**Comment by glogiotatidis** [comment]
Thanks for filing the issue @madasan .

I've changed the email settings and it should be working now. Can you please confirm?

**Comment by madasan** [comment]
Looks like it is working now, thanks!
