### ISSUE TITLE
No reset password link (dev instance)

### ISSUE THREAD

**Issue by madasan** [mozilla/kitsune#3129]
**Steps to reproduce**
Go to https://dev.sumo.moz.works/ and try to login. I get the message "incorrect password". I click on the "My password isn't working" link and enter email address. I get confirmation that a new password has been sent.
 
**Expected behaviour**
Reset password link should be received via email

**Actual behaviour**
No reset password link is received (inbox or spam folder).

**Comment by glogiotatidis** [comment]
Thanks for filing the issue @madasan .

I've changed the email settings and it should be working now. Can you please confirm?

**Comment by madasan** [comment]
It works, thanks!
