### ISSUE TITLE
Remove all references to  ethn.io and Treejack

### ISSUE THREAD

**Issue by glogiotatidis** [mozilla/kitsune#3139]
Confirm is ethn.io is something we still use, remove otherwise

https://github.com/mozilla/kitsune/blob/master/kitsune/products/jinja2/products/product.html#L92

- [ ] remove treejack waffle.switch
- [ ] remove waffle.flag('ethnio-all')

**Comment by bensternthal** [comment]
Per Joni via email "We no longer need ethnio or Treejack. They were from past experiments."

**Comment by glogiotatidis** [comment]
Thanks Ben!
