### ISSUE TITLE
Update CDN Failover Header Whitelist

### ISSUE THREAD

**Issue by glogiotatidis** [mozilla/kitsune#3141]
After #3140 gets merged, update CDN Failover Header Whitelist to only very on accept-language.

https://github.com/mozmeao/infra/blob/master/apps/sumo/infra/shared/cloudfront_failover/cloudfront_failover.tf#L35

**Comment by metadave** [comment]
CDN whitelist updated: https://github.com/mozmeao/infra/pull/755
