### ISSUE TITLE
all products icons are identical on mobile site in Firefox for Android 59.0.1

### ISSUE THREAD

**Issue by rtanglao** [mozilla/kitsune#3144]
All the icons at:
https://dev.sumo.moz.works/en-US/products
are the firefox desktop logo in Firefox for Android 59.0.1
Please see the following screenshot:
![40242305284_d296c2bc5c_o 1](https://user-images.githubusercontent.com/45195/37755341-575e58fa-2d62-11e8-98b6-aed90485f423.jpg)
this is the same as desktop but filing this issue just in case it's a real issue (my guess is it is not a real issue)

**Comment by glogiotatidis** [comment]
This is a side effect of the data anonymization script run on dev and it's not a bug or plaform issue. 

Thanks for reporting Roland.
