### ISSUE TITLE
Site banner obscures submit button for support forum replies on Fennec 59.0.1

### ISSUE THREAD

**Issue by rtanglao** [mozilla/kitsune#3150]
March 26 banner obscures submit button for support forum replies on Fennec (Firefox for Android 59.0.1), see following screenshot from Note 8, Android 7.1.1 Nougat:
![40139235415_141e43fa55_o](https://user-images.githubusercontent.com/45195/37923539-375e72f8-30e4-11e8-9ef6-b378d8f69a8f.jpg)
This makes it impossible to reply to support forum questions from Firefox for Android.
There should be an "X" to dismiss the banner or some way of showing the "submit reply" button on Android

**Comment by LuciferAJ** [comment]
I'm trying to add this button, but unable to find the file, Can anyone help me?

**Comment by akatsoulas** [comment]
Closing as stale.
