### ISSUE TITLE
[Investigate] A old user swap bug resurfaced during the AWS migration leading to some wacky side effects

### ISSUE THREAD

**Issue by NoahSUMO** [mozilla/kitsune#3153]
Hi guys! Just want to start by saying thank you for an awesome migration! It went as well as one could expect. :) I'm just going to mention the following issue in case it reappears or has somehow left some lasting side effects.

Back in 2013, we encountered a mysterious bug that made random users swap usernames & when they posted, they would post under that wrongly assigned username. There also was some DB data loss in the form of forum posts, KB edits & possible media uploads done during & around that maintenance time frame. Back then we were doing asynchronous db maintenance & didn't have a problem until that day. Look here for the full story of the craziness (it's ok to skim it, it's a little long :P):
https://support.mozilla.org/en-US/forums/contributors/708998

I believe that same bug resurfaced during our AWS migration but I don't think it resulted in any data loss but the username swap bug did definitely happen for some users. Jscher suspects it may have had something to do with cookies saying: "Perhaps when the site was moved to the new hosting all of the old cookies should have been treated as invalid." But giorgos said all the cookies are invalid b/c there are no matching sessions anyway. So the mystery deepens. :P

Here's the very short bug we filed back when this happened:
https://bugzil.la/842727 - Forum posts displayed from wrong users after database issues

Ironically as a result of this, my suggestion of implementing a Read-only mode was accepted & done on every scheduled maintenance since then to avoid any dataloss. :)

Username Swap reports from AWS migration day:
https://support.mozilla.org/en-US/questions/1211097
https://support.mozilla.org/en-US/questions/1211080#answer-1093499
^"This is very bad. I was logged in as MSEL and had access to his profile. -Zenos"

Things to do b/c of this:
- Poke around & see if any users are still reporting a "Freaky-Friday" situation ;) [inside the wrong username; appears more than just cosmetic & the user has access to the incorrectly assigned account]
- See if any users are getting the wrong email notifications delivered to them [most likely b/c they're in the wrong username]
- See if there was any data loss [if that's possible by comparing the DBs somehow?]
- See if a more serious, deeper issue has been uncovered that can possibly be fixed

Thanks in advance for the work you do on this!

**Comment by NoahSUMO** [comment]
If we're able to investigate specific users, I'd take a look at these 2 accounts: https://support.mozilla.org/en-US/user/Zenos & https://support.mozilla.org/en-US/user/MSEL

They seem to be swapping between each other. And it looks like it happened only a hour & a half ago :X Waiting for confirmation from the user but according to the timestamp it looks like it happened today.
From looking at this post & the one above it:
https://support.mozilla.org/en-US/questions/1211080#answer-1093498
https://support.mozilla.org/en-US/questions/1211080#answer-1093496

**Comment by MadMattAu** [comment]
I think you will find it was me and MSEL that were going in Circles.  I do not recall Zenos have any issues at all. 

I became MSEL and MSEL became Lunaea.  I found signing in and out of the forum cleared the issue for me, so I assume some corruption in the cookie that was set.  Having said that,  it is a serious security issue if modifying the cookie can lead to changed of identity like that.  What I did notice is I appeared to retain the moderator functions even though the forum was determined I was not me.

**Comment by glogiotatidis** [comment]
> I think you will find it was me and MSEL that were going in Circles. I do not recall Zenos have any issues at all.
> 
> I became MSEL and MSEL became Lunaea. I found signing in and out of the forum cleared the issue for me, so I assume some corruption in the cookie that was set. Having said that, it is a serious security issue if modifying the cookie can lead to changed of identity like that. What I did notice is I appeared to retain the moderator functions even though the forum was determined I was not me.

@MadMattAu did those happened during the AWS migration (i.e. this week) or are you talking about what happened in the past?

**Comment by NoahSUMO** [comment]
MadMattAu's case happened during the AWS migration.

We have a little more information from AliceWyman, who was also affected:
"I made the post as the other user a few minutes before [my last reply in the thread](https://support.mozilla.org/en-US/questions/1210357#answer-1093185), ... so it would have been around 3:05 pm EDT on March 26.

Yes, I stay logged into the forum as AliceWyman. When I replied to the email, I got to the thread by hitting the "Reply" button on the email notifying me that the user had solved the issue. Odd that, when it took me to the thread it logged me in as that user [[wdrapkin](https://support.mozilla.org/user/wdrapkin)]."

Another observation by [James](https://support.mozilla.org/en-US/user/james), who was not signed in & not affected by this:
"I remember I could access the SIGN IN page https://support.mozilla.org/en-US/users/auth (as I was logged out by the move) but could not log in. I decided to come back later. Forty minutes later I noticed there were new posts as recent as a few minutes after I tried logging in and was able to login then."

**Comment by AliceWyman** [comment]
**@MadMattAu** you wrote above,

> What I did notice is I appeared to retain the moderator functions even though the forum was determined I was not me.

??? I know that I did NOT retain moderator functions while signed in as user wdrapkin because I was not able to delete posts as that user.  I had to sign out and sign back in as AliceWyman to delete the post I made as that user.

**Comment by philipp-sumo** [comment]
i have also seen the issue once now. i was logged out of the site and clicked on the "post a reply" button in a notification mail: https://support.mozilla.org/questions/1211145?utm_campaign=questions-reply&utm_medium=email&utm_source=notification&auth=XXX#answer-1093685 
after that, i was signed in as the OP with all of their settings (site displayed in french)...

**Comment by glogiotatidis** [comment]
Thank you all for your input, it was really helpful. I'm going to copy/paste contents and remove this issue and continue discussion in https://bugzilla.mozilla.org/show_bug.cgi?id=1449599

**Comment by AliceWyman** [comment]
**@ glogiotatidis** You wrote:
> Thank you all for your input, it was really helpful. I'm going to copy/paste contents and remove this issue and continue discussion in https://bugzilla.mozilla.org/show_bug.cgi?id=1449599

That bug is restricted (Access Denied for me)

**Comment by NoahSUMO** [comment]
Yes, restricted for me as well. That is undoubtedly a security bug where the work is taking place to fix the user swapping issue. Pretty sure they will beef up security to all the related components like user sessions & their cookies so that it is next to impossible for this to happen again.

Once they are confident the problem is fixed, I'm sure they'll drop the security flag as per Mozilla's transparency policy once the threat is confirmed fixed & tested. But we'll need to test this thoroughly for a while to make sure it really is fixed. ;)

**Comment by AliceWyman** [comment]
@NoahSUMO you wrote,

> Once they are confident the problem is fixed, I'm sure they'll drop the security flag as per Mozilla's transparency policy once the threat is confirmed fixed & tested.

It doesn't look as though [bug 1449599]( https://bugzilla.mozilla.org/show_bug.cgi?id=1449599) will be made public, even though the bug is fixed. See this discussion for more information:
https://support.mozilla.org/en-US/forums/contributors/712956 SUMO Security Incident
