### ISSUE TITLE
Clean out all references to Firefox OS

### ISSUE THREAD

**Issue by MkllTech** [mozilla/kitsune#3154]
Since Firefox OS is no longer maintained, the support section/forum for it should be removed.

**Comment by glogiotatidis** [comment]
Firefox OS is no longer developed but I'm not if we don't longer support it. @madasan can you please advise?

**Comment by MkllTech** [comment]
The Marketplace on Firefox OS was also closed, not sure if theres any benefit to providing support for a dead end.

**Comment by madasan** [comment]
There might be some legal implications, we're checking and will update.

**Comment by glogiotatidis** [comment]
OK So Legal gave us the green light to go forward and clean out Firefox OS references. SUMO team will place a banner for 60 days on KB articles saying that we're going to clean them up.

AFAIK we have a) KB articles b) Questions

The open questions is now: "Do we completely remove all of them or do we archive them somehow?"

**Comment by jonisavage** [comment]
Ideally we'd archive all the Firefox OS articles so contributors who've worked on them still have a record of their contribution. 

As far as the banner goes, can we display it on the Firefox OS category and all its child pages?
