### ISSUE TITLE
On the get started article I get a notification to try Sync

### ISSUE THREAD

**Issue by MkllTech** [mozilla/kitsune#3157]
Is this the expected behavior?

**Comment by NoahSUMO** [comment]
Can you link us to the exact article? Maybe even throw in a screenshot? :P I couldn't find this article you were talking about :)

**Comment by MkllTech** [comment]
Here is the article in question: https://support.mozilla.org/en-US/kb/get-started-firefox-overview-main-features

**Comment by MkllTech** [comment]
Relevant screenshot here: https://screenshots.firefox.com/22FVu6EOPFGooAEI/support.mozilla.org

**Comment by MkllTech** [comment]
This is a confirmed SUMO promotion as noted by NoahSUMO - Closing issue!
