### ISSUE TITLE
POST vs GET Autofill for Localizing does not show changes

### ISSUE THREAD

**Issue by turtlelovesshoes** [mozilla/kitsune#3161]
iRC: March 27, 2018 #sumo
Artist: does anyone have the same issue when localizing an article: edit text in the locale text box, klick on "preview" and then click on a link in the "preview" view. When I return to the article textbox (using the return arrow) all the edits I had made before in the textbox are gone and I only get the text from the current version. If I'm not completely mistaken the edited text was still there before the move
...
guigs and Noah: also the diff toggle has disappeared when returning. I mean the line numbers and highlighted text is gone and I have to click toggle diff again to get it back
3:56 PM also toggle diff and toggle syntax highlighting is in English language, not in locale language

The first issue was confirmed from Noah on Windows and Rachel on Mac - may need one more test, however further investigation is being done by Tonnes.

**Comment by TonnesM** [comment]
Can confirm "losing" post data.. preview causes POST, then GET when fetching external link, then GET for (original) edit page. Not sure if last GET should cause cached postdata to be refilled, or if aws changed any of this. (I never clicked external links anyway when editing other than by right-click -> new tab, just to be safe.) Clicking internal page links should cause no loss and still don't, but they use POST only.

Frankly I'm not sure how it's support to work, i.e. whether GET should always bypass / ignore cache and cause original data to load.

**Comment by akatsoulas** [comment]
Closing as stale.
