### ISSUE TITLE
unable to reset password via email

### ISSUE THREAD

**Issue by Costenslayer** [mozilla/kitsune#3162]
hey I'm unable to reset my user password via email i get the following error below, I have now tried this several time 
![sumo-pw-reset](https://user-images.githubusercontent.com/10689279/38062960-b0ce7d7a-32ee-11e8-8184-773a57233284.png)

**Comment by bensternthal** [comment]
Hi, we are currently doing some work that could cause some intermittent errors (apologies), please try back in an hour or so.

Again, apologies for the inconvenience.

**Comment by bensternthal** [comment]
Should be resolved.

**Comment by Costenslayer** [comment]
thanks users can login but I'm no longer getting a password reset email through

**Comment by bensternthal** [comment]
Issue here was that costenslayer was using the wrong email. Emails are working.
