### ISSUE TITLE
Force /admin to always use en-us

### ISSUE THREAD

**Issue by glogiotatidis** [mozilla/kitsune#3168]
/admin the last locale used by the python threads b/c it's in `SUPPORTED_NONLOCALES`. Force en-us when this happens.

See also how mozillians fixes this
  https://github.com/mozilla/mozillians/blob/master/mozillians/settings.py#L171
  https://github.com/mozilla/mozillians/blob/production/mozillians/common/middleware.py#L102

**Comment by akatsoulas** [comment]
this no longer happens.
