### ISSUE TITLE
Audit And Evaluate Usage of Token Based Logins Via Email

### ISSUE THREAD

**Issue by bensternthal** [mozilla/kitsune#3170]
See original request for this feature:

https://github.com/mozilla/kitsune/pull/1757

My understanding of the actual usage of this feature is.. it aint very useful. In almost all cases the user was already logged in and the magic link did nothing. Will confirm it's usage and ideally get sign off on total removal

**Comment by glogiotatidis** [comment]
@bensternthal i believe this is still valid? We probably want to remove email based login middleware altogether and we filed this issue to spend some time on that. Something changed?

**Comment by bensternthal** [comment]
Apologies I saw the reference "Remove TokenLogin Backend and Middleware" and thought that was removing it altogether.
