### ISSUE TITLE
Create process and process enforcement tools for Secrets Management

### ISSUE THREAD

**Issue by glogiotatidis** [mozilla/kitsune#3172]
Current situation:
 - Secrets live in a separate encrypted repo
 - We want to push application secrets from developer laptops.
 - We want ensure that all devs have the latest secrets
 - We want to ensure that we don't override settings with an older version

Work:
 - Document the process of updating the secrets 
 - Write a cli tool for this process which will ensure
   - that there're no uncommited changes in encrypted repo
   - encrypted repo is in master branch and
   - both origin/master and master are in sync 
   - bonus points: 
     - diff the changes against the k8s deployed version (not sure if possible)

**Comment by akatsoulas** [comment]
This is no longer relevant
