### ISSUE TITLE
Improve performance of _get_creator_counts util function

### ISSUE THREAD

**Issue by glogiotatidis** [mozilla/kitsune#3174]
`kitsune.community.utils._get_creator_counts` until function is DB heavy and takes a lot of time to execute. Evaluate its usefulness and provide a way to optimize the query and/or cache the results.  

This issue is related to the degraded performance SUMO experienced on Fri March 30th ([NR Error](https://rpm.newrelic.com/accounts/1299394/applications/45097089/downtime/34422892))

**Comment by jgmize** [comment]
There was another degraded performance issue just now related to DB slowness that is related to this.
