### ISSUE TITLE
Automate Stage update with fresh L10n strings

### ISSUE THREAD

**Issue by glogiotatidis** [mozilla/kitsune#3186]
We need to provide a way for the translators to check their work before hitting production. Historically I've been manually pushing every Thursday to Stage which updates the strings. This gave a few days until Monday when I manually merged string repo from `master` to `production`.

While this process was not ideal kept things moving. We need to provide a solution for the AWS era.

1. Let's start with making stage deploy images with locales from `master` branch
2. Make this a single click procedure
3. In the future we can switch to daily automatic builds and pushes to stage.

Steps 1 and 2 will gets to base one from where we can discuss with the localization team how we can improve the situation. Maybe we can create a `sumo-l10n.moz.works` instance and make it auto-deploy on every merge in `sumo-l10n` repo. Maybe there are other better ideas.

**Comment by akatsoulas** [comment]
This is no longer relevant
