### ISSUE TITLE
[Investigate] Top Contributor Behavior seems off

### ISSUE THREAD

**Issue by turtleloveshoes** [mozilla/kitsune#3200]
Two quick sanity checks were that the top contributors showing today are not largely participating in the forums, they participate in other programs. 

So this draws three questions: 
1. Does the formula take into consideration the old #fxhelp tag from the social program? This would explain Mkll being 1
2. Does the formula take into consideration the support forum thread posts or the moderation queue?
3. Was there a decline in participation recently compared to the top 5 to the second teir 5 top contributors that may have caused the shift? 

Thank you for the investigation.

**Comment by NoahSUMO** [comment]
Hope I can offer some insight. On 4/19, @safwanrahman let me know he was working on optimizations for the Top Contributors list & apologized in advance if it caused any issues. So this should be a temporary hiccup until he's done. Safwan, I tagged you here so maybe you can explain more about what you did & we can help you get it more accurate. And thanks again for working on this! :)

**Comment by safwanrahman** [comment]
@NoahSUMO @turtleloveshoes I am concerned about the issue and I have made a fix for that in #3192
Hope it will be merged and get deployed soon.

**Comment by glogiotatidis** [comment]
Fix pushed to production. @turtleloveshoes can you please verify that this works for you?

**Comment by safwanrahman** [comment]
It seems to be fixed! https://support.mozilla.org/en-US/community/top-contributors/questions

The toppest contributor FredMcD is showing here, then others!
In support forum also! https://support.mozilla.org/en-US/questions/firefox
Thanks a lot @glogiotatidis for the review and deployment!

**Comment by glogiotatidis** [comment]
Thanks for fixing and verifying @safwanrahman
