### ISSUE TITLE
Add link to contribute to project

### ISSUE THREAD

**Issue by ryanleesipes** [mozilla/kitsune#3204]
Ryan here, I'm the Thunderbird Community Manager, and I was curious as to whether including a link to the Thunderbird product page labeled "Contribute to Thunderbird" would be accepted. I see how to do this, and could add it above the "Volunteer for Mozilla Support", but I wanted to ensure this was acceptable before I sent a pull request.

**Comment by madasan** [comment]
Hi @ryanleesipes

What is the desired outcome of this button? Is it to get people involved in Thunderbird development as a product or to get them involved in Thunderbird support?

We're in the process of setting up a full redesign for the site so we might be able to do something about it but first we need to understand what that link is supposed to do.

**Comment by ryanleesipes** [comment]
Get people involved in Thunderbird development.

**Comment by ryanleesipes** [comment]
@madasan did you see above? How long until the new site is implemented?

**Comment by ryanleesipes** [comment]
@madasan is there a way to do this just for Thunderbird? This is a request from my community and I'd like to see if it is possible. If not, please let me know.

**Comment by madasan** [comment]
@ryanleesipes sorry for the late reply, this went off my radar. Adding this only for Thunderbird would provide an inconsistent experience across the site (pplus we do not have the resources to investigate this in depth) so it is not an option at the moment.
