### ISSUE TITLE
Add Social Helpers icon to several pages

### ISSUE THREAD

**Issue by sgarrity** [mozilla/kitsune#3220]
Add Social Helpers icon on all the following pages:
https://support.mozilla.org/en-US/get-involved
https://support.mozilla.org/en-US/get-involved/questions
https://support.mozilla.org/en-US/get-involved/l10n
https://support.mozilla.org/en-US/get-involved/kb

**Comment by akatsoulas** [comment]
This issue is no longer relevant.
