### ISSUE TITLE
Investing adding an ORM level cache back to the site

### ISSUE THREAD

**Issue by pmac** [mozilla/kitsune#3228]
Kitsune used to use Django-Cache-Machine and it seems to have been somewhat engineered around the assumption that such a caching level would exist. Now that is has been removed we are noticing some of these inefficiencies that I believe were previously covered by this cache. This issue is to investigate the possibility of adding back such a cache at least in the short-term to relieve some of the stress of modest increases in traffic we sometimes see.  This would include:

1. Possibly moving the cache to a new memcached cluster in Elasticache instead of Redis for performance reasons and so that the task queue isn't impacted by increases in cache usage.
2. Which ORM cache library to use if any.

**Comment by pmac** [comment]
To be clear this may be a bad idea, but I did want to discuss it. It was removed in bugs [1113162](https://bugzilla.mozilla.org/show_bug.cgi?id=1113162) and [1164091](https://bugzilla.mozilla.org/show_bug.cgi?id=1164091).

**Comment by pmac** [comment]
For example, [django-cacheops](https://github.com/Suor/django-cacheops#readme) looks good and updated and popular.

**Comment by glogiotatidis** [comment]
I like the idea and I believe we would help the site a lot. FTR we use [django-cachalot](https://github.com/noripyt/django-cachalot) in snippets but I'm all for trying django-cacheops.

**Comment by pmac** [comment]
For the record I'd be happy with either `cacheops` or `cachalot`. If we're already using `cachalot` with some success then we should give that a try first IMO.

**Comment by akatsoulas** [comment]
Closing as stale.
