### ISSUE TITLE
Evaluate removal of surveygizmo integration

### ISSUE THREAD

**Issue by glogiotatidis** [mozilla/kitsune#3238]
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1416244

**Comment by pmac** [comment]
That bug is asking for the survey gizmos to be enabled again. I'm confused on what this issue is asking for.

**Comment by glogiotatidis** [comment]
In the bug the ask was to re-enable surveygizmo but it's 8 months ago, so I filed this issue to evaluate whether this is still needed or we can remove all related code. From the recent comments in the bug it appears this is still needed, so this issue is resolved: "Don't remove, make it work again"
