### ISSUE TITLE
Add product type and filtering to product cards on front page

### ISSUE THREAD

**Issue by sgarrity** [mozilla/kitsune#3246]
Products don't currently have a 'type' ("Browser", "Mobile", "TV", etc.). This should be added to enable filtering by type on the front page.

See mockup:

![image](https://user-images.githubusercontent.com/58062/41044227-22f22514-697c-11e8-8de9-6cecb5c0b4f4.png)

**Comment by akatsoulas** [comment]
This issue is no longer relevant.
