### ISSUE TITLE
Add popular shortcut links to topic cards

### ISSUE THREAD

**Issue by sgarrity** [mozilla/kitsune#3248]
![image](https://user-images.githubusercontent.com/58062/41351473-d773031c-6eec-11e8-86bf-8c0d73ee91b4.png)

**Comment by sgarrity** [comment]
ToDo on this:
• Determine how these three articles are selected (is it the first three, by popularity, by editorial choice, etc.).
• Build the database capabilities for whichever selection method is chosen
• Determine the design if there are only 1, 2, or 3 articles in that section (do we still show "See All >"?)

**Comment by akatsoulas** [comment]
This issue is no longer relevant.
