### ISSUE TITLE
Find a new WSGI server

### ISSUE THREAD

**Issue by pmac** [mozilla/kitsune#3266]
Meinheld is abandoned (no releases since Nov 2016). Issues like #3017 are due to poor spec implementation by Meinheld. We should find a well supported and active project to use for serving the site. 

## Candidates

* [Gunicorn](http://docs.gunicorn.org/en/latest/index.html) + Gevent
* [Gunicorn](http://docs.gunicorn.org/en/latest/index.html) + sync
* [uWSGI](https://uwsgi-docs.readthedocs.io/en/latest/)
* [mod_wsgi-express](https://pypi.org/project/mod_wsgi/)
* [cherrypy](https://github.com/cherrypy/cherrypy)
* [bjoern](https://github.com/jonashaag/bjoern)
* other??

**Comment by jgmize** [comment]
> Currently, meinheld maintenance is inactive and maintenance cost is very high.

from https://github.com/mopemope/meinheld/issues/92#issue-278320125

The other candidates may be more active from a maintenance standpoint, but none of the replacement candidates we've tested so far come close to matching meinheld's performance & reliability. The maintenance cost of meinheld may be high, but it may still be lower than replacing it, so we could consider taking over maintenance of the project instead. #3017 is the first issue that we've run into related to meinheld, and [the fix](https://github.com/mozilla/kitsune/pull/3267) didn't involve changing anything in meinheld itself.

**Comment by jgmize** [comment]
> [...] I think a full exploration of our options is a good idea at this time.

I agree. While you explore the existing alternatives, I'm going to explore https://github.com/jgmize/wsgi-ingress/issues/1 and do a little cost/benefit analysis on taking over maintenance of a mature but inactive project vs writing a replacement ourselves.

**Comment by pmac** [comment]
Hmm... That analysis you linked to is interesting. My take-away is actually more concern for the high error rates and latency with both Meinheld and Bjoern under load than with their speed (good as it was). The winner for me in that article for consistency, latency, and good-enough speed is mod_wsgi-express. Going to continue putting together a test for that one.

**Comment by akatsoulas** [comment]
Sumo has been migrated to Gunicorn + gevent
