### ISSUE TITLE
Fix live search "selected" UI

### ISSUE THREAD

**Issue by jpetto** [mozilla/kitsune#3268]
When using the live search on any page, the "selected" class applied to elements in the side bar or top bar is quoted twice, resulting in the class not being applied/UI not communicating which category is selected.

![screen shot 2018-07-10 at 9 50 58 am](https://user-images.githubusercontent.com/317532/42518233-fd4e380a-8426-11e8-9b7e-d01b826bda5d.png)

I believe this can be fixed relatively quickly (famous last words) in the [custom Nunjucks filter](https://github.com/mozilla/kitsune/blob/master/kitsune/sumo/static/sumo/js/nunjucks.js#L51).

**Comment by Deepikap1** [comment]
@jpetto I would like to work on this issue.

**Comment by jpetto** [comment]
@Deepikap1 Feel free to submit a PR!

**Comment by akatsoulas** [comment]
This should be fixed now. Please re-open if this is not the case.
