### ISSUE TITLE
Launch the redesign

### ISSUE THREAD

**Issue by sgarrity** [mozilla/kitsune#3269]
A visual update to the site has been done in the [may-2018-redesign](https://github.com/mozilla/kitsune/tree/may-2018-redesign) branch.

Items to address for/at launch:

- [ ] Update product images in `/admin` interface (the new images can be found in PR #3252)

**Comment by jpetto** [comment]
What are the steps to get this launched? Do we need QA/review from design?

**Comment by jpetto** [comment]
I've updated the product icons on the [dev site](https://dev.sumo.moz.works/).

**Comment by sgarrity** [comment]
> What are the steps to get this launched? Do we need QA/review from design?

@Dinodog can you let us know if anything else is required here? As far as I know, this should be ok to roll out (given that the product icons get updated in production at the time of deployment).


> @jpetto I noticed there might be some missing product images on the home page. e.g. Webmaker, Firefox OS and Other Mozilla Products. Not sure where to add the images so I added them here.

I think we've got all of the icons for products that are on the production support.mozilla.org site. Unless there are products that show up in other locales, but not in en-US?

**Comment by rtanglao** [comment]
Madalina and Patrick: We don't need Webmaker and Firefox OS am I right ?

**Comment by madasan** [comment]
Hi @sgarrity 

A few comments:

1. On the product documents page the article title links and body are almost indistinguishable on my Mac screen. The style for the links needs to be made more prominent.

![screenshot_2018-07-23 basic browsing firefox help](https://user-images.githubusercontent.com/10244340/43090767-f6e002a2-8eb0-11e8-9219-8c09dda5c934.png)


2.  The "These fine people helped write this article"  section on the bottom of the article sometimes seems to break the formatting. 

![screenshot_2018-07-23 use the search bar in firefox firefox help](https://user-images.githubusercontent.com/10244340/43090796-128a7d7a-8eb1-11e8-954a-495adab01128.png)


3. The article suggestions ("See also") links also need to be more prominent ^^

4. My impression was that we will keep Firefox for Enterprise as a tile and remove Webmaker similar to the mock-up here: https://github.com/mozilla/kitsune/pull/3252. Am I correct @Dinodog ?

**Comment by mlagace** [comment]
Thanks @madasan for the feedback! @madasan, @sgarrity I can look at those issues and make the changes.

**Comment by jonisavage** [comment]
Thanks for working on this! In addition to Madalina's feedback I noticed one other thing:

The header on the product page (after clicking on a product from the home page) seems to look broken (Firefox Focus and "Help Topics" run into each other): https://screenshots.firefox.com/6yanUVI5AtOlRcOl/dev.sumo.moz.works

**Comment by safwanrahman** [comment]
I have a feeling that the login allignment is broken
![image](https://user-images.githubusercontent.com/7114151/43107305-38b14f4a-8efe-11e8-8a99-56b14343371f.png)

**Comment by safwanrahman** [comment]
There used to be a `download firefox` button in the header if browse from Non Firefox browser which is not present at this moment.
![screen shot 2018-07-24 at 5 00 48 am](https://user-images.githubusercontent.com/7114151/43107407-ae7ae6c8-8efe-11e8-839d-96368e39bb7e.png)

**Comment by madasan** [comment]
@mlagace @sgarrity any updates on the feedback we gave? We have a few more things to add but I was wondering whether you managed to have a look on what we have reported already.

**Comment by sgarrity** [comment]
> @mlagace @sgarrity any updates on the feedback we gave? We have a few more things to add but I was wondering whether you managed to have a look on what we have reported already.

@madasan I'll take a look, thanks!

**Comment by sgarrity** [comment]
> There used to be a download firefox button in the header if browse from Non Firefox browser which is not present at this moment.

@safwanrahman The download button is included and should be showing up for non-Firefox browsers.  Is it not showing up for you? Which page and which browser? (thanks!)

**Comment by safwanrahman** [comment]
@sgarrity I am using chrome  It does not show anywhere.

**Comment by sgarrity** [comment]
> @sgarrity I am using chrome It does not show anywhere.

@safwanrahman Ah, I see it's not showing up on the front page, but does on other pages. I've filed an issue: https://github.com/mozilla/kitsune/issues/3281 Thanks for reporting!
