### ISSUE TITLE
Add download button for non-Firefox browsers on home page

### ISSUE THREAD

**Issue by sgarrity** [mozilla/kitsune#3281]
It appears the header Firefox download button (that only shows in non-Firefox browsers) is not appearing on the home page. It should!

From this comment: https://github.com/mozilla/kitsune/issues/3269#issuecomment-407227694

**Comment by sgarrity** [comment]
@madasan Can you help confirm the desired download button visible behavior across the site?

It appears the current rules apply on the live website:

Show Firefox download button in header on all pages EXCEPT:
 1. If the visitor is signed-in, do not show
 2. If the current page is the Firefox product page, do not show (as there is already a larger download button on that page)
3. If the visitor is already using Firefox (on any page)

I would propose the following for the redesign we drop the 2. exception, as the newly styled header download button is already quite large.

I think the header download button could replace the in-page download button on the Firefox product page. This screenshot shows both. I would propose we keep the top left button, but remove the 2nd button (right aligned, above the Help Topics heading):

![image](https://user-images.githubusercontent.com/58062/43524337-680c0f82-9575-11e8-8ff8-09117aa48b13.png)

**Comment by sgarrity** [comment]
@Dinodog @madasan and I spoke about this on the phone. The conclusion is that we'll show the header download button on ALL pages, including the home page.

**Comment by jpetto** [comment]
Additional detail in [this comment](https://github.com/mozilla/kitsune/pull/3312#issuecomment-421388773)

**Comment by jpetto** [comment]
To get the final requirements in this issue, copy/pasting from the [original comment](https://github.com/mozilla/kitsune/pull/3312#issuecomment-421388773):

> Show Firefox download button in header on all pages EXCEPT:
>
> - If the visitor is already using Firefox (on any page)
> - If the current page is the Firefox product page, do not show (as there is already a larger download button on that page). This includes all category and article pages under the Firefox product, that should all have the larger download button in the body of the page.

The [current logic](https://github.com/mozilla/kitsune/blob/master/kitsune/sumo/jinja2/base.html#L180) also includes a check for `user.is_authenticated()`, which, if true, will ensure the download button is _not_ shown.

@madasan Please confirm that user authentication status should be disregarded going forward.

Thanks!

**Comment by jpetto** [comment]
The logic for the in-page buttons is:

If the current product is Firefox, whether on the product page, the help topics page, or any specific article page, show the download button **UNLESS** the visitor is already using Firefox.
