### ISSUE TITLE
Fix alignment of headings on some article pages

### ISSUE THREAD

**Issue by sgarrity** [mozilla/kitsune#3282]
As described in this comment: https://github.com/mozilla/kitsune/issues/3269#issuecomment-407198550

**Comment by sgarrity** [comment]
![image](https://user-images.githubusercontent.com/58062/43526795-6c94d4ca-957b-11e8-8378-288f2e60bc97.png)

**Comment by navgurukul-shivani18** [comment]
Hi @sgarrity I would like to work on it can you help me getting issues and also please can your provide some more context about it . Its little unclear to me right now.
cc @turtlelovesshoes

**Comment by jpetto** [comment]
I believe this issue has been fixed.
