### ISSUE TITLE
Replace "Firefox Rocket" logo and copy with "Firefox Lite"

### ISSUE THREAD

**Issue by michaelmccombie** [mozilla/kitsune#3283]
The rebrand for Firefox Rocket has gone live. So we need to update the copy and the logos used to refer to this product on support.mozilla

[Link to Play Store](https://play.google.com/store/apps/details?id=org.mozilla.rocket)

![image](https://user-images.githubusercontent.com/5924575/43599098-59f3a33a-963b-11e8-8363-80d87a2f5616.png)

**Comment by michaelmccombie** [comment]
I added two images to that zip folder. One is the square image used in the play store, the other image is was resized to match the images on this redesign demo https://dev.sumo.moz.works/en-US/

**Comment by navgurukul-shivani18** [comment]
Hi @michaelmccombie I would like to work on it as my first bug , can you guide me please how to proceed? 

Thanks

**Comment by michaelmccombie** [comment]
@navgurukul-shivani18 I'm glad you are interested in helping! But I'm going to close this issue because the team that works on Firefox Rocket decided to go in a different direction with the name/ logo.
