### ISSUE TITLE
Update the Thunderbird logo on download buttons

### ISSUE THREAD

**Issue by pmac** [mozilla/kitsune#3293]
The Thunderbird logo was updated elsewhere on the site in [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1481621), but the logo on the download buttons still needs to be done. [This comment on the bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1481621#c10) details the issue.

Basically buttons like that on the right side green button at:

https://support.mozilla.org/en-US/products/thunderbird

@jpetto do you have any time to look at this?

**Comment by jpetto** [comment]
It shall be done.

**Comment by pmac** [comment]
Fixed in #3296

**Comment by pmac** [comment]
Looks good in prod! Thanks again 💯
