### ISSUE TITLE
Move from elasticutils to elasticsearch-dsl

### ISSUE THREAD

**Issue by pmac** [mozilla/kitsune#3294]
This will enable us to fix #3260 by supporting ESv6 and #3177 since elasticutils doesn't support recent Djangos.

**Comment by jgmize** [comment]
required for https://github.com/mozilla/kitsune/issues/2990 also

**Comment by akatsoulas** [comment]
This work is being tracked [here](https://github.com/mozilla/sumo-project/issues?q=is%3Aopen+is%3Aissue+milestone%3AElasticSearch7)
