### ISSUE TITLE
Optimize the /users/auth/ view 

### ISSUE THREAD

**Issue by pmac** [mozilla/kitsune#3305]
For some reason traffic to this URL can cause the site some strain. Let's figure out why and fix it.

**Comment by safwanrahman** [comment]
@pmac Can you point me to some New relic report?

**Comment by pmac** [comment]
I actually think we addressed this issue via another root cause in #3373. I believe that the data we saw pointing us to the auth view turned out not to be the issue after all. Closing this one.
