### ISSUE TITLE
monkeypatch_render should only be used in testing

### ISSUE THREAD

**Issue by jgmize** [mozilla/kitsune#3306]
https://github.com/mozilla/kitsune/blob/69253e763ada10422d3c88e681bcb4af00e1eb4f/kitsune/sumo/monkeypatch.py#L105 will always evaluate to True, so monkeypatch_render is always called by patch_all, but: https://github.com/mozilla/kitsune/blob/69253e763ada10422d3c88e681bcb4af00e1eb4f/kitsune/sumo/monkeypatch.py#L143

**Comment by teeshirtman88** [comment]
What should only be used in testing don't understand
