### ISSUE TITLE
Add Firefox Reality product to AAQ

### ISSUE THREAD

**Issue by pmac** [mozilla/kitsune#3310]
[Firefox Reality](https://bugzilla.mozilla.org/show_bug.cgi?id=1485760)

- [x] Create product
- [x] Create topics that match the topics in `questions.config` mark them visible and in aaq
- [x] Link `English` AAQ Locale 
- [x] Push code

See #3178 as an example of doing this

**Comment by pmac** [comment]
@glogiotatidis looks like you did this last. Do you have time soon to discuss this process with me?

**Comment by glogiotatidis** [comment]
> @glogiotatidis looks like you did this last. Do you have time soon to discuss this process with me?

invite sent! :mailbox:

**Comment by pmac** [comment]
Calling this one done. I'll open a new one for the Amazon stuff.
