### ISSUE TITLE
Modifying multiple About:Config Settings in one command/script?

### ISSUE THREAD

**Issue by NotaWindowsUser** [mozilla/kitsune#3311]
Is there a way to make a script that could modify about:config settings? Couldn't find a way to do this. 

Could this be a future feature?

**Comment by pmac** [comment]
I'm not sure I understand. Do you mean give the SUMO site the ability to modify the browser settings of a visitor? That would open some major security holes I think.

**Comment by NotaWindowsUser** [comment]
I agree with that would be a big security risk. lol But what I mean is way for the Firefox user to import a XML/cfg/w.e file with all prefers settings that would apply to the about:config settings of the current user.

**Comment by NotaWindowsUser** [comment]
I'm in the wrong repository what would this go under? @pmac ;-;

**Comment by pmac** [comment]
Oh. Yeah. For suggesting a Firefox feature you want [bugzilla](https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox). This repo is specifically for the support.mozilla.org website.
