### ISSUE TITLE
Add ability to attach a smaller product logo for product pages

### ISSUE THREAD

**Issue by jpetto** [mozilla/kitsune#3316]
[The PR that replaced the product logos with the "?" SVG](https://github.com/mozilla/kitsune/pull/3255) [appears to have done so on purpose](https://github.com/mozilla/kitsune/pull/3255/files#diff-9fb8e903b164ade55bd42033512b9b29R21).

Are there mockups showing what should be used in place of the "?" SVG?

[original comment](https://github.com/mozilla/kitsune/pull/3312#issuecomment-421391396)

**Comment by jpetto** [comment]
cc @madasan

**Comment by jpetto** [comment]
cc @grailean

**Comment by jpetto** [comment]
For reference, here's [a link to the dev server](https://dev.sumo.moz.works/en-US/products/firefox) showing an example of the missing(?) logo treatment.

**Comment by grailean** [comment]
@jpetto the ? icon was intentional, in my design is different arranged and the icon is grayish.

**Comment by teeshirtman88** [comment]
What does this mean and was this sent personally to me...

**Comment by jpetto** [comment]
> What does this mean and was this sent personally to me...

@teeshirtman88 looks like [you are following this repo](https://github.com/mozilla/kitsune/watchers?page=3), so by default I believe you get notifications on new issues. You can change your notifications on this repo by going to the "Watch" menu near the top right of the screen. Hope that helps!

**Comment by jpetto** [comment]
Archive of product icons sized for this specific layout:

https://www.dropbox.com/s/120m4nottujckq3/product_icons.zip?dl=0
