### ISSUE TITLE
Switch from NPM to Yarn for Node dependency installation

### ISSUE THREAD

**Issue by pmac** [mozilla/kitsune#3322]
Yarn will lock and cryptographically verify all dependencies so that we can get more repeatable deployments.

**Comment by jgmize** [comment]
https://mixmax.com/blog/to-yarn-and-back-again-npm is worth reading before moving to yarn.

**Comment by pmac** [comment]
Yarn has been working well for bedrock. Also the version of npm that comes with the latest version of Node that we can get to (`6.14.4` at present) is `3.10.10` and does not have the locking that npm 6 does. I think Yarn is our best way forward for the moment if we want repeatable deployments.

**Comment by pmac** [comment]
Seems like something to evaluate when we take a larger modernization step with our node stuff. I'm glad npm is good in 2018, but we can't use that version yet.
