### ISSUE TITLE
Localization: re-asses font

### ISSUE THREAD

**Issue by jpetto** [mozilla/kitsune#3326]
From the [original comment](https://github.com/mozilla/kitsune/pull/3312#issuecomment-422431299):

> Localization issue: the font used on the subpages of https://dev.sumo.moz.works/get-involved for locales that include diacritics does not render well and looks rather bad. Could we have another (full internationalized) font instead?

See original comment for screenshots.

**Comment by pierreneter** [comment]
Is there any progress?

**Comment by fitojb** [comment]
While the original problematic font has been removed by now, now there exists the same problem with Zilla Slab; specifically, its limited Latin character coverage means it is unusable for Kitsune locales like Vietnamese, which right now show a lot of replacement characters.

**Comment by akatsoulas** [comment]
The fonts have been updated in the site following Protocol's designs. I am closing this issue. Please file a new one if there are still issues with the fonts.

**Comment by pierreneter** [comment]
Can we reopen it? there are still issues with the fonts.

> https://support.mozilla.org/vi/get-involved

![FireShot Capture 055 - Mozilla Support - support mozilla org](https://user-images.githubusercontent.com/12815768/79414329-8a66ab00-7fd4-11ea-9002-8ae9bfcac18e.png)

**Comment by fitojb** [comment]
Yeah, neither Inter nor Zilla Slab support Vietnamese, and the latter font doesn’t include any characters for Greek and Cyrillic languages!

**Comment by LeoMcA** [comment]
Thanks for the reports both, I've opened an issue here for further discussion: https://github.com/mozilla/sumo-project/issues/369
