### ISSUE TITLE
Standardize case in/when using get_browser function

### ISSUE THREAD

**Issue by jpetto** [mozilla/kitsune#3330]
The [`get_browser` function](https://github.com/mozilla/kitsune/blob/69253e763ada10422d3c88e681bcb4af00e1eb4f/kitsune/sumo/utils.py#L334) matches ignoring case, but returns whatever case is present in the user agent string. To make this function more stable, we should return only lower case strings.

**Comment by LucianaMarques** [comment]
Hi! I just submitted a [pull request](https://github.com/mozilla/kitsune/pull/3395l)!

**Comment by akatsoulas** [comment]
Closing as stale.
