### ISSUE TITLE
JS error on login page

### ISSUE THREAD

**Issue by LunarTwilight** [mozilla/kitsune#3335]
Go to https://support.mozilla.com/en-US/users/auth and open the console
![image](https://user-images.githubusercontent.com/13520392/45989677-231b8b80-c029-11e8-818c-694dbcd82535.png)
(screenshot b/c it wouldn't let me copy the full message)

**Comment by navgurukul-shivani18** [comment]
Hi @LunarTwilight ,
I wasn't able to re-create this bug on FF Version 64.0b1 (64-bit)
But, was successful in re-creating on Google Chrome Version 72.0.3590.0 (Official Build) dev (64-bit)
I'll try to send a PR soon to fix this :)
Thanks

**Comment by suhailsinghbains** [comment]
Hi 
Is this bug still open, would love to work on this.

**Comment by LunarTwilight** [comment]
Won't this bug be no longer an issue once SUMO migrates to [FXA](https://support.mozilla.org/kb/firefox-accounts-mozilla-support-faq)?

**Comment by akatsoulas** [comment]
Thanks @LunarTwilight for flagging this. The duplicate id should be resolved now. I wasn't able to reproduce this neither in Firefox or Chrome.

**Comment by LunarTwilight** [comment]
@akatsoulas I'm still able to reproduce this?
