### ISSUE TITLE
Add fall-back stylesheet for cases where CDN assets fail to load

### ISSUE THREAD

**Issue by pmac** [mozilla/kitsune#3336]
The CSS, JS, and many images are hosted by the static asset CDN for SUMO. This uses a different domain and TLS cert than support.m.o, and therefore may fail to load in some cases when the HTML from support.m.o does (e.g. using IE in Windows XP, or if the DNS for the CDN domain fails to resolve). We should add some minimal default styling for this case that is loaded from the support.m.o domain that will reliably load and will add some minimal styling so that the content of the page is prominent and unimportant unstyled menus and whatnot are moved down or hidden. These styles should be either not loaded or overridden when the full stylesheets load. This would do a lot to support users in situations where they would otherwise have to sift through a bit of a mess to find the content they were after. 

See https://github.com/mozmeao/infra/issues/942

**Comment by jgmize** [comment]
See also https://github.com/mozilla/bedrock/pull/4143

**Comment by pmac** [comment]
@jgmize is there something specific about that PR that we should see? Looks like a big one with a lot of conversation.

**Comment by jgmize** [comment]
https://github.com/mozilla/bedrock/pull/4143/files#diff-ae461e40dbbb323955a43a43fa0822ab shows an example of sourcing an alternative minimal stylesheet for IE <= 8 in the base template. After reviewing that PR and searching the kitsune codebase, I found that we already use this technique in https://github.com/mozilla/kitsune/blob/master/kitsune/sumo/jinja2/base.html#L35-L40. I would advocate following bedrock's example in the PR above and applying the same minimal css to all IE <= 8, but that simplification isn't necessary to resolve this issue, only changing the domain that the stylesheet is loaded from.

**Comment by admbanking1** [comment]
> The CSS, JS, and many images are hosted by the static asset CDN for SUMO. This uses a different domain and TLS cert than support.m.o, and therefore may fail to load in some cases when the HTML from support.m.o does (e.g. using IE in Windows XP, or if the DNS for the CDN domain fails to resolve). We should add some minimal default styling for this case that is loaded from the support.m.o domain that will reliably load and will add some minimal styling so that the content of the page is prominent and unimportant unstyled menus and whatnot are moved down or hidden. These styles should be either not loaded or overridden when the full stylesheets load. This would do a lot to support users in situations where they would otherwise have to sift through a bit of a mess to find the content they were after.
> 
> See [mozmeao/infra#942](https://github.com/mozmeao/infra/issues/942)

LP[adm745](url)

**Comment by akatsoulas** [comment]
Closing as stale.
