### ISSUE TITLE
Search UX is jarring to some users

### ISSUE THREAD

**Issue by jpetto** [mozilla/kitsune#3346]
See the bug entitled _Trying to type in search window causes page to flash_: https://bugzilla.mozilla.org/show_bug.cgi?id=1495660

**Comment by MarjaE2** [comment]
Jarring and a migraine trigger.

**Comment by akatsoulas** [comment]
This page is redesigned as part of the [responsive redesign](https://github.com/mozilla/sumo-project/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Responsive+redesign%22) milestone.
