### ISSUE TITLE
Add UTM params to Firefox download buttons

### ISSUE THREAD

**Issue by bensternthal** [mozilla/kitsune#3347]
As reported in this https://bugzilla.mozilla.org/show_bug.cgi?id=1495841 UTM tracking is now missing from Kitsune.

Poking a little deeper I see the following github prs that looks to revert a lot of the custom JS tracking we had implemented as part of the SCL3 migration.  It looks like this was meant to be temporary but I do not see it being re-enabled (unless i am on the wrong branch).

https://github.com/mozilla/kitsune/pull/3138
https://github.com/mozilla/kitsune/pull/3137

**Comment by jpetto** [comment]
It appears all GTM JS is currently in place on production - on the whole, GTM/GA *should* be functional.

According to the bug, what appears to be missing (or what needs to be added) are `utm_` params on the Firefox download buttons.

**Comment by bensternthal** [comment]
Hmm, what I thought I saw in those two prs was all the custom tagging I did for analytics pros being reverted, and I do not think it was "remerged" post AWS migration.

**Comment by jpetto** [comment]
I see the initial GTM code (original commit: https://github.com/mozilla/kitsune/commit/33be297922ad64b5dcc10808752d6cd1896348d6, re-merge commit: https://github.com/mozilla/kitsune/commit/6ba4ae85dfb01806283c97465509c25291be4eb5) and the custom tagging code (original commit: https://github.com/mozilla/kitsune/commit/1331ca19fa8149d21e8031c5676545b13d32a9f2, re-merge commit: https://github.com/mozilla/kitsune/commit/e66debe9dc3c1df5173a7a8b09b072ecbcef76b6) currently in master (and spot checked on the site in prod). (Both original commits were in #3076.)

Are there other commits/PRs missing? The bug mentioned above [1495841](https://bugzilla.mozilla.org/show_bug.cgi?id=1495841) only asks for `utm_` params on the Firefox download buttons - was there a different bug detailing more missing tracking?

**Comment by bensternthal** [comment]
I think we are good. I'm not sure what I was looking at where the changes appeared to have not been remerged. Sorry for the wild 🦆 chase.
