### ISSUE TITLE
Fix Thunderbird download button UX

### ISSUE THREAD

**Issue by jpetto** [mozilla/kitsune#3354]
The download button breaks the header copy layout:

https://support.mozilla.org/en-US/products/thunderbird

<img width="852" alt="screen shot 2018-10-03 at 3 58 03 pm" src="https://user-images.githubusercontent.com/317532/46439057-24ce0900-c725-11e8-909f-558d851dbaf4.png">

**Comment by navgurukul-shivani18** [comment]
Hi , I would love to work on it , @jpetto can you guide me how to go ahead with it ?

Thanks

**Comment by jpetto** [comment]
Hi @navgurukul-shivani18! There is a pull request opened already (#3357, linked above), but we are awaiting feedback from the stakeholder. If changes are requested and you'd like to take over the branch, you are more than welcome!

Please watch the thread on the pull request for more information.

Thanks again!
