### ISSUE TITLE
Thunderbird unable to open message

### ISSUE THREAD

**Issue by bachmeil** [mozilla/kitsune#3361]
Thunderbird is unable to display an email message that others (Outlook and Fastmail) are able to display. This is true on 60.2.1 64-bit and 52.9.1 64-bit on Ubuntu 16.04.
[cantopen.txt](https://github.com/mozilla/kitsune/files/2452370/cantopen.txt)

That's an eml file but I was required to change the extension to attach it.

**Comment by pmac** [comment]
This repo is for development of support.mozilla.org. If you're having a problem with Thunderbird you should be able to find some help by asking your question here:

https://support.mozilla.org/en-US/products/thunderbird
