### ISSUE TITLE
Don't show any logo/icon if none is uploaded

### ISSUE THREAD

**Issue by jonichan** [mozilla/kitsune#3366]
We currently show a gear icon or a nurse icon by default for a topic or product if we don't have an image uploaded. There are cases when we don't need an icon, so we shouldn't show one if none is uploaded. 

For example, I had to upload an icons for "Firefox for Fire TV" and "Firefox for Echo Show" under the Firefox for Amazon Devices page just so we wouldn't show the gear icon.: https://support.mozilla.org/en-US/products/firefox-amazon-devices

**Comment by pmac** [comment]
The design does call for some kind of icon for those boxes. I do personally think that the gray box needs a little something more than words to make it clear it's an action. In this case you could just use the Firefox logo for all 3 much like the Firefox product does for the square page icon:

https://support.mozilla.org/en-US/products/firefox
