### ISSUE TITLE
Add "top contributors" back to the questions list pages

### ISSUE THREAD

**Issue by pmac** [mozilla/kitsune#3374]
In #3373 we removed the "top contributors" list from the questions list pages. In this issue we need to bring that feature back, but in a way that never has a cache miss. It should be pre-calculated on a schedule (daily should be fine) and always displayed using that data. We can bring back the old UI for now, but there is some interest in a better UI for this that is not hidden by default.

**Comment by pmac** [comment]
What we actually ended up doing is to change the "top contributors" hover list into a link to the full top-contributors page for that product. This is I think a good final solution. However, we can discuss here whether or not to add back to the questions list pages a list of top contributors there in addition to the link to the full list page.

**Comment by jyox007** [comment]
![bio](https://user-images.githubusercontent.com/42260543/47256137-7faf7200-d440-11e8-8ca7-dbc84262b025.jpg)

**Comment by akatsoulas** [comment]
The site has been redesigned and top contributors are back in the question list page for logged in users.
