### ISSUE TITLE
[Outreachy A/B testing] Enabling Optimize for Kitsune

### ISSUE THREAD

**Issue by turtlelovesshoes** [mozilla/kitsune#3388]
Hey there, 
Moving teams, looks like the tool used for A/B tests that may be needed for the OKRs on 2019 is Optimizely or Optimize. 

Looks like we need to use GA to initiate Optimize - is this possible? https://support.google.com/optimize/answer/6262084

@bensternthal @pmac @vesper-mozilla

**Comment by bensternthal** [comment]
Rachel:

Can you provide a link to or paste the A/B testing requirements here. With this information we can better advise on which A/B testing solution to implement.

**Comment by LucianaMarques** [comment]
Hey @turtlelovesshoes and @bensternthal !

I'd like to give this a try. Just to make sure, no one is already working on this right?
