### ISSUE TITLE
Fix: Timezone sync in accordance to Django's Timezone settings

### ISSUE THREAD

**Issue by omkar-dsd** [mozilla/kitsune#3412]
All the project level timezones should be in sync with the Timezone configuration defined in Django's settings. This allows to take control of datetime at a single place.

**Comment by SukhnandanMalhotra** [comment]
Hey,  I'd like to work on this, can I take this up?

**Comment by pmac** [comment]
Hi @SukhnandanMalhotra. Thanks for your interest, but @omkar-dsd has already submitted a pull-request (#3403) for this.
