### ISSUE TITLE
"Share this article" no longer shows up on articles

### ISSUE THREAD

**Issue by jonichan** [mozilla/kitsune#3418]
**Expected result:** When I used to write an article, a shortlink automatically gets generated and shows up at the bottom of the page: example:https://support.mozilla.org/en-US/kb/update-latest-version-firefox-android) [screenshot](https://screenshots.firefox.com/FpR6sHDz1oTD8Oii/support.mozilla.org)

**Actual result:** "Share this article: ______" shortlinks no longer show up.
Examples: 
- https://support.mozilla.org/en-US/kb/clear-cookies-and-site-data-firefox-fire-tv
- https://support.mozilla.org/en-US/kb/tracking-protection-focus-ios

Please have shortlinks automatically generate, but please use this format: mzl.la/support-xxx

**Comment by akatsoulas** [comment]
Closing as the site has been redesigned. Please file a new ticket if this functionality is not working or missing.
