### ISSUE TITLE
[prod] SUMO Reload Question Traffic Stats cron fails to finish running

### ISSUE THREAD

**Issue by metadave** [mozilla/kitsune#3425]
- [log output](https://gist.githubusercontent.com/metadave/2c36a482239e27d9f1dc5c1137df50be/raw/96f17d2dbe4b37202988af634d5710e01462c137/gistfile1.txt)

- https://github.com/mozilla/kitsune/blob/master/kitsune/sumo/googleanalytics.py#L229

**Comment by pmac** [comment]
I'm guessing GA access change or other credentials problem. Investigating.

**Comment by pmac** [comment]
Should also investigate if we use this data/feature anymore.
