### ISSUE TITLE
No email confirmation?

### ISSUE THREAD

**Issue by Songbird0** [mozilla/kitsune#3430]
Hi,

[This issue](https://github.com/mozilla/kitsune/issues/3128) seems to be already filed but it didn't work for me. After many resend, the email confirmation doesn't appear inside of my box (neither as spam).

Anyone have an idea?

**Comment by HackedDiane** [comment]
I received this after trying to message Ancestry DNA site. Relatives that work there didnt want me finding out family secrets in files

**Comment by akatsoulas** [comment]
Closing as stale.
