### ISSUE TITLE
Elasticsearch search terms for FF 62 and 63 Desktop 1st 3 weeks

### ISSUE THREAD

**Issue by pmac** [mozilla/kitsune#3432]
I received the following from @rtanglao:

> would it be possible for you to provide the search term data from 
> Kitsune's elastic search for the 1st 3 weeks of FF62 and 63: 
>
> 1. Firefox 62 September 5-September 25, 2018 
> 2. Firefox 63 October 23-November 12, 2018 

I've talked with some people and we're not sure yet whether our ES servers keep this kind of information. But we may be able to gather it either from our server logs of accessed URLs or from GA if that kind of thing is tracked there. I'll update here when I find out more.

/cc @metadave

**Comment by rtanglao** [comment]
happy new year @pmac ! any update on this appreciated!

**Comment by rtanglao** [comment]
Hi @pmac and @akatsoulas  

i) any update?
ii) we'd like this to extend this for the whole year if the data is available:
i.e. january 1, 2018 - december 31, 2018

**Comment by metadave** [comment]
@hmitsch is this something that your team could look into?

**Comment by hmitsch** [comment]
Hi @rtanglao, 

Let me try to play back the question to you to see if we agree on the thing you are looking for:

> For a set of defined time frames (5-25SEP, 23NOV-12DEC, 01JAN-31DEC) you would like to know _SUMO Search_ queries?

As we are new to SUMO, here are a few questions:
* This question is about _SUMO Search_, not search engine queries, right?
* Did you look for this type of information in the past? If yes, how did you get them answered?

Best regards,
   Henrik

**Comment by havardl** [comment]
Hi @hmitsch, 

I'm working with @rtanglao on this. I can't speak to if he's looked for this before, but we're interested in historical data of the specific search engine queries used at https://support.mozilla.org/

Best,
Håvard

**Comment by rtanglao** [comment]
@hmitsch:

1. SUMO search, not search engine queries, i.e. when folks visit support.mozilla.org what search terms did users enter?
2. We did not look at this information in the past as far as I know

**Comment by hmitsch** [comment]
Problem solved! 

Unsurprisingly, @pmac was right: SUMO Search queries are sent as **Events** to Google Analytics (of course, honoring the browser's DNT policy setting):

<img width="295" alt="image" src="https://user-images.githubusercontent.com/869692/53048449-13e42100-3495-11e9-926a-418c790dce92.png">


In Google Analytics, this can be accessed via `Behaviour > Events`:
* Event Category: `Instant Search`
* Event Action: `Exit Search`
* Event Label: `<search terms>`

Setting the filter to **exclude** `q=undefined` AND match the regex `.*q\=..............*\&format`, this is what the top 5 results for the last 7 days look like:
<img width="847" alt="image" src="https://user-images.githubusercontent.com/869692/53049402-498a0980-3497-11e9-91bc-f9deed884519.png">

There's a major caveat here: As you might see from the regex, GA events are fired for each _find as you type query_. This means we have a lot of garbage events we need to filter in a smart way. That regex is a solid example for sheer _brute force_.

Best regards,
   Henrik
