### ISSUE TITLE
Please make the "These fine people helped write this article" smaller

### ISSUE THREAD

**Issue by jonichan** [mozilla/kitsune#3433]
At the bottom of each SUMO article is "These fine people helped write this article." The font has gotten huge compared to the rest of the page and is the same size as the article title:

https://screenshots.firefox.com/wVlrTcJJWhTKLeX4/support.mozilla.org  

It should be smaller and more muted so it doesn't clash with the rest of the article.

**Comment by metadave** [comment]
@SukhnandanMalhotra sure!

**Comment by PrernaVerma** [comment]
@metadave  Hey , I have tried solving this issue and submitted a Pull Request.Please review. :)

**Comment by akatsoulas** [comment]
The site has been redesigned and probably this issue is no longer relevant. Please file a new one if there is a problem with the new design
