### ISSUE TITLE
New volunteers signup UX and design tweaks

### ISSUE THREAD

**Issue by atulsuresh** [mozilla/kitsune#3441]
I feel it's a bit difficult for a first-time volunteer to find the signup button. 
[https://support.mozilla.org/en-US/get-involved/questions](https://support.mozilla.org/en-US/get-involved/questions
)

My suggestion would be to place the signup button just after the hero text and also make sure the alignment and spacing is correct.
 
Current Page
<img width="1678" alt="screen shot 2019-01-09 at 2 54 00 pm" src="https://user-images.githubusercontent.com/6421963/50889719-ad440000-141e-11e9-8a62-07b2bee1b2e6.png">

My Suggestion.
<img width="1674" alt="screen shot 2019-01-09 at 2 29 09 pm" src="https://user-images.githubusercontent.com/6421963/50889746-bc2ab280-141e-11e9-96d5-322f22bd4157.png">
 

Would love to hear more suggestions to make it better.

**Comment by akatsoulas** [comment]
The site has been redesigned and this issue is not relevant any more.
