### ISSUE TITLE
CODE_OF_CONDUCT.md is missing

### ISSUE THREAD

**Issue by vesper-mozilla** [mozilla/kitsune#3447]
The new CoC file is a required standard for all of Mozilla's Github repos in 2019. Please add a local version of it to kitsune - thank you!

Example: https://github.com/mozilla/voice-web/blob/master/CODE_OF_CONDUCT.md

**Comment by metadave** [comment]
thanks @vesper-mozilla, we'll get this added. Where is the standard for Mozilla's github repos published?

**Comment by metadave** [comment]
https://github.com/mozilla/kitsune/pull/3449
