### ISSUE TITLE
GitHub repo description links to support.mozilla.com

### ISSUE THREAD

**Issue by jwhitlock** [mozilla/kitsune#3448]
The GitHub repo description includes a link to https://support.mozilla.com/. This is a redirect to https://support.mozilla.org. I think the repo description should be changed to link directly to support.mozilla.org.

![kitsune repo](https://user-images.githubusercontent.com/286017/51619437-f05da300-1ef5-11e9-87de-8f48ab187446.png)

**Comment by metadave** [comment]
fixed
