### ISSUE TITLE
Change text on product page

### ISSUE THREAD

**Issue by jonichan** [mozilla/kitsune#3461]
On every product page, this text is currently showing up: "Search and navigate easily with these essential features". This text doesn't make sense on the product page context.

I'd like to replace this text with "Explore the knowledge base". I don't see a way to do it in Django Admin.

Product pages where this appears (Under "Help topics"):
https://support.mozilla.org/en-US/products/firefox
https://support.mozilla.org/en-US/products/firefox-enterprise
https://support.mozilla.org/en-US/products/mobile
https://support.mozilla.org/en-US/products/ios
https://support.mozilla.org/en-US/products/focus-firefox
https://support.mozilla.org/en-US/products/firefox-amazon-devices
https://support.mozilla.org/en-US/products/firefox-lite
https://support.mozilla.org/en-US/products/firefox-reality
https://support.mozilla.org/en-US/products/screenshot-go
https://support.mozilla.org/en-US/products/thunderbird

**Comment by pmac** [comment]
I'm reviewing #3488 and just wanted you to be aware that "Explore the knowledge base." is not currently a translated string that we have, so it would be in English until it was translated widely. We do have "Explore more topics" in the current translations, but I don't know if that would work.

I'm happy to merge this change to be clear, just wanted you to be aware of the options and results.

**Comment by akatsoulas** [comment]
@jonisavage thoughts on this?

**Comment by jonisavage** [comment]
Let's go ahead and merge the change. We'll notify the L10N community so they can localize that string after the change is complete.

**Comment by jonichan** [comment]
Hi @akatsoulas This reverted back to the old copy. All the product pages say "Search and navigate easily with these essential features" again.

**Comment by akatsoulas** [comment]
This is deployed in prod.
