### ISSUE TITLE
Improve wikimetrics admin filters

### ISSUE THREAD

**Issue by nukeador** [mozilla/kitsune#3464]
In order to get accurate community stats I would need a few new filters to be added to the wikimetrics admin section

https://github.com/mozilla/kitsune/blob/master/kitsune/dashboards/admin.py

- Show the locale codes in a new column (since translated names are impossible for me to follow)
- Filter by top 50 localized (not just top 20 and top 100)
- Be able to filter by date (today stats is the most common thing I'm looking for)

**Comment by saadmk11** [comment]
> Filter by top 50 localized (not just top 20 and top 100)

@nukeador The `WikiMetric` model does not have a `top 50 localized` choice for `code` Field.

https://github.com/mozilla/kitsune/blob/cf5a912f0d9d97a723c6bc3178d66be29dd33d1e/kitsune/dashboards/models.py#L78-L88

We need to add a new choice for this. Is this what we want here?

**Comment by nukeador** [comment]
Hi,

I'm no longer involved in this work. @madasan will be able to comment on the current priorities for SUMO metrics.

Cheers.

**Comment by akatsoulas** [comment]
https://github.com/mozilla/kitsune/pull/5234
