### ISSUE TITLE
Top contributors page with internal server error

### ISSUE THREAD

**Issue by nukeador** [mozilla/kitsune#3465]
I found there is a page that generates a nice json with all data about contributors activity

https://github.com/mozilla/kitsune/blob/master/kitsune/community/views.py#L185

But the public page is giving Internal Server Error:

https://support.mozilla.org/community/top-contributors/l10n/new

Is it possible to know the full error for this page? It seems the code should be functional and having this json is super useful for me.

**Comment by nevadacons** [comment]
Unaware why the public page is giving you the internal [error](https://techisours.com/)

**Comment by akatsoulas** [comment]
This has been fixed [here](https://github.com/mozilla/sumo-project/issues/652) and it will be release along with the first release for the new search.
