### ISSUE TITLE
Expose translated locales on KB API

### ISSUE THREAD

**Issue by nukeador** [mozilla/kitsune#3484]
Hi,

In order to run some manual stats on different articles, I would need the KB API to expose the locale codes (not translated names) an article has been translated into.

Info that kitsune provides here: 

https://support.mozilla.org/en-US/kb/push-notifications-firefox/show_translations

API: https://support.mozilla.org/api/1/kb/push-notifications-firefox

Note: I don't really know what do we consider translated_locales, if also articles with a corresponding one in other language even if it's outdated.

If outdated articles are considered "translated" we should see if it's possible to expose translated and outdated as separate fields, since an outdated articles it's not really fully translated.

**Comment by nukeador** [comment]
My user case:

As a CM I want to be able to query individual articles to see which locales have already been translated, this will allow me to understand where to focus my time supporting communities.

I'll be using this script to extract the information I don't have to manually do it

https://github.com/nukeador/sumo-stats/

**Comment by akatsoulas** [comment]
There is already an initiative to expose more data through APIs. I am closing this specific issue.
