### ISSUE TITLE
banner shows as empty blue box in Firefox iOS, Chrome + Safari

### ISSUE THREAD

**Issue by metadave** [mozilla/kitsune#3504]
https://github.com/mozilla/kitsune/pull/3501

**Comment by metadave** [comment]
reported in https://bugzilla.mozilla.org/show_bug.cgi?id=1535689#c10

**Comment by pmac** [comment]
I think the JS isn't firing or isn't working. I see no JS errors, but if I manually add "chosen" and "visible" classes to one of the entries it looks right.

**Comment by pmac** [comment]
So yeah... I forgot. This is by design as requested in the [original bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1535689). I think we should just hide the blue bar for non-Fx as well.

**Comment by pmac** [comment]
I'll work on that
