### ISSUE TITLE
[FxA] Disable username/password login for users with a Firefox Account.

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/kitsune#3510]

**Comment by mcranston18** [comment]
If a user has an existing Firefox account, and they try to log in using an existing username and password (e.g. on screen below), they should be denied entry and a message will appear saying:
> Please use your Firefox account to log in instead

<img width="669" alt="Screen Shot 2019-04-25 at 10 51 29 AM" src="https://user-images.githubusercontent.com/1489696/56745307-1a6a6f80-6748-11e9-89a0-bad6d23f9a92.png">

**Comment by mcranston18** [comment]
As I begun to implement this ticket, it occurred to me that we probably do not want to "block" the log in for existing SUMO users; we probably want to let them log in, show a warning message that their account will be deprecated, and maybe block entry to the support section without a FF account.

Additionally, the design copy states that we will "soon" be deprecating the SUMO accounts.
