### ISSUE TITLE
Add new products to AAQ without python code changes

### ISSUE THREAD

**Issue by rtanglao** [mozilla/kitsune#3512]
Currently, adding new products to the AAQ (e.g. Firefox Reality for Desktop, Firefox Lockbox for Android, etc) requires python code changes (unlike adding new products to the SUMO KB which doesn't require python code changes). 

Given the fact that we will be adding lots of new products to the AAQ, it would be really nice to be able to do this without python code changes.

**Comment by akatsoulas** [comment]
Let's use this issue to scope the effort in order to expose this functionality to the admin interface.

**Comment by akatsoulas** [comment]
Although this would be nice to have, I am closing it for now as it's not a priority and the amount of time needed to add a new product to the AAQ is trivial. We will re-open it once there is time for this feature.
