### ISSUE TITLE
Restore selenium tests in the project.

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/kitsune#3513]

**Comment by jgmize** [comment]
There are some values in [tests/Jenkinsfile](https://github.com/mozilla/kitsune/blob/master/tests/Jenkinsfile) that will need to be replaced to ensure that no [erroneus emails](https://github.com/mozilla/kitsune/blob/master/tests/Jenkinsfile#L145-L148) get sent.

**Comment by akatsoulas** [comment]
cc @viorelaioia @rleitan

**Comment by akatsoulas** [comment]
Duplicate of #3548
