### ISSUE TITLE
Django 1.11 Update Fixes

### ISSUE THREAD

**Issue by pmac** [mozilla/kitsune#3515]
Hi @smileychris! After #3480 merged and was deployed we noticed a few things and I wanted to record them here.

* We see that scheduled tasks that use `django-cronjobs` all seem to be failing with the following message: `manage.py cron: error: unrecognized arguments: enqueue_lag_monitor_task`
* I saw hundreds of these warnings in the logs during the migrations run of deployment: `(urls.W002) Your URL pattern '^/search$' [name='community.search'] has a regex beginning with a '/'. Remove this slash as it is unnecessary. If this pattern is targeted in an include(), ensure the include() pattern has a trailing '/'.`

I'll update this issue if I find more things.

**Comment by pmac** [comment]
We've decided to ignore the warning messages for now as it may open a larger can of worms than we need right now. They may go away during the next upgrade (Django 2.2) anyway.

**Comment by pmac** [comment]
@SmileyChris I looked again at the 1.11 upgrade PR that has already merged and I don't see any conversion of the functions in `cron.py` files to real management commands. I did see that in the Bedrock 1.11 upgrade PR, so perhaps you were thinking of that. In any case, it doesn't look like any of the `cron.py` files were touched and so we should either do that conversion for kitsune, or fix/upgrade django-cronjobs to be 1.11+ compatible.

**Comment by SmileyChris** [comment]
Hrm, you're right. I think I was just getting confused between repositories :P I think the conversion to standard management commands is the best course of action.

**Comment by SmileyChris** [comment]
Ok, there's most of the work done. I'll test and do a pull request next week.

**Comment by pmac** [comment]
Thanks Chris!
