### ISSUE TITLE
[FxA] Update the navigation menu in the platform.

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/kitsune#3528]
The navigation menu will be updated to allow users to either sign in or register a new account through Firefox Accounts along with some other changes like:

* The login/signup button will be moved on the right side.
* The AAQ link will only be available to authenticated users
* The language selector will be moved to the right side too.
* Volunteer section will be in the left side.

@flekkowich can you update this issue with the designs?

**Comment by akatsoulas** [comment]
cc @kkellydesign

**Comment by mcranston18** [comment]
@akatsoulas Just want to confirm a few things:

- I see a few instances of the "AAQ link" throughout the site (e.g. "Get Community Supprt", "Ask a question"). I assume we want to hide all instances for non-authenticated users?

- Should we re-direct non-authenticated users to login/signup who try to access the URL at  `/questions/new`?

- As part of this ticket, should I remove "Register or Sign In" from the AAQ flow?

**Comment by akatsoulas** [comment]
I believe the answer is yes to all of these questions but we could tackle all of these points in #3541 and keep this ticket only for the nav menu.

**Comment by flekkowich** [comment]
Designs added, please use  option 2 in zeplin https://zpl.io/VKDjAp7

**Comment by flekkowich** [comment]
I know this is late, and you already are done, but just to ensure it is here: 

Designs https://zpl.io/VKDjAp7

**Comment by viorelaioia** [comment]
Navigation menu on the pages, when logged in and logged out, doesn't match the [designs]( https://zpl.io/VKDjAp7).

<img width="1267" alt="Screen Shot 2019-05-10 at 10 43 32" src="https://user-images.githubusercontent.com/5293100/57511355-c481f400-7311-11e9-8125-d6a5ae7803f3.png">
<img width="1267" alt="Screen Shot 2019-05-10 at 10 43 41" src="https://user-images.githubusercontent.com/5293100/57511360-c6e44e00-7311-11e9-96f5-85e2486c8c91.png">

**Comment by akatsoulas** [comment]
The designs will be updated to include the `Contributor Tools` link. Regarding the `Get Community Support` link, it will be available only for logged in users

**Comment by akatsoulas** [comment]
@viorelaioia is this ready to go?

**Comment by viorelaioia** [comment]
As per discussions in slack and conversation with @akatsoulas , there are still some updates needed in the nav. 
For the logged out view:
- remove "Get Community Support" menu item
- remove "Contributor Tools" menu item

For the logged in view:
- remove "Volunteer" menu item
- move "Inbox" menu item to the account drop down menu.

**Comment by mcranston18** [comment]
Will be fixed once https://github.com/mozilla/kitsune/pull/3636 is merged in

**Comment by viorelaioia** [comment]
"Volunteer" button should be available for logged out users. @akatsoulas , can you please confirm?

![volunteer](https://user-images.githubusercontent.com/5293100/57934682-e3abf300-78c8-11e9-969b-c398816a9d83.png)
