### ISSUE TITLE
[FxA] Update the product page to include more support options

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/kitsune#3531]
The landing product page should provide more support options according to the designs here:
https://zpl.io/2GGQeDY

**Comment by akatsoulas** [comment]
cc @kkellydesign

**Comment by mcranston18** [comment]
Will be fixed once #3636 is merged in

**Comment by flekkowich** [comment]
the Contact us should only be shown if users come from a premium service - we do not have any up now so there should be no Contact Us (see designs) https://zpl.io/aBRP0Op

**Comment by flekkowich** [comment]
@akatsoulas if this is too much work, this doesn't have to block FxA release (it is unlikely we will need Contact US before end of July)

**Comment by viorelaioia** [comment]
"Ask the Community" button is not available on "Firefox for enterprise" product page.
Pinging @madasan , to confirm if it should be available.

**Comment by flekkowich** [comment]
@viorelaioia yes the ask the community should be available on product pages.

**Comment by kkellydesign** [comment]
You can see an example of "Ask the Community" on the Firefox product page here: 

https://dev.sumo.moz.works/en-US/products/firefox

There's a single conditional around that, `{% if show_community_support %}` that is set by a "questions enabled" toggle on the product model. As far as template work goes, I think this ticket is all set.
