### ISSUE TITLE
[FxA] Use `suggest_username` for username suggestions.

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/kitsune#3536]
When a new account is created through Firefox Accounts authentication, we can use the existing `suggest_username` under the `utils.py` in the `users` app to create the username in the `User` model. This username can be editable by the user in the profile settings. The easiest way to achieve this is by using it as the algorithm in the oidc lib. Lib setting `OIDC_USERNAME_ALGO`

**Comment by viorelaioia** [comment]
@akatsoulas , do we still want this:
"This username can be editable by the user in the profile settings."?
From https://github.com/mozilla/kitsune/issues/3603, I understand that the username is not expected to be editable.

**Comment by viorelaioia** [comment]
As per today's discussion, username should not be editable. Closing the ticket.
