### ISSUE TITLE
[FxA] Disable registration of new profiles with username/password.

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/kitsune#3541]
New users should be created only through Firefox Accounts.

**Comment by akatsoulas** [comment]
The profile creation in the AAQ needs to be removed completely. In the first iteration only logged in users will be able to ask a question.

**Comment by akatsoulas** [comment]
This ticket should:
* Hide all the instances of the AAQ flow behind authentication. Users need to login first before asking a question
* If there is direct visit to the `/questions/new` url, user should be redirected to login first  
* The step that asks the user to create a new account in the AAQ flow needs to be removed
* Users should no longer have the option to create a new account with a username/password

@mcranston18 if there is anything missing feel free to add to the list

**Comment by mcranston18** [comment]
@akatsoulas This ticket is almost complete. In regards to AAQ links (e.g. screenshot below); should these links be hidden to a non-authenticated user? Or should they be visible and the non-authenticated user will be taken to the log in screen if they click it?

![Screen Shot 2019-04-26 at 8 49 33 AM](https://user-images.githubusercontent.com/1489696/56919969-faacb180-6a8f-11e9-82fc-fc902930cf42.png)

I spoke with Rina but she said to leave this decision for you. I think we should leave the links in the UI, and if non-authenticated user clicks on them, they will be sent to the log in.
