### ISSUE TITLE
[FxA] Redirect users to the edit profile page.

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/kitsune#3544]
**New** users or existing users that are logging in through Firefox Accounts for the first time should be redirected to the edit profile page to complete/update their profile. Users will have the option to skip this step if they wish to.

**Comment by viorelaioia** [comment]
Issue found: https://github.com/mozilla/kitsune/issues/3598

**Comment by akatsoulas** [comment]
Acceptance criteria:
For this issue we should only test if the user is redirected to the edit profile page based on the criteria in the description. Profile data will be handled in issue #3598
