### ISSUE TITLE
https://support.allizom.org returns Internal server error

### ISSUE THREAD

**Issue by rleitan** [mozilla/kitsune#3550]
The issue is intermittent.

Browser Console errors:
The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol. authcontributor
[Exception... "Favicon at "https://support.allizom.org/favicon.ico" failed to load: Internal Server Error."  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource:///modules/FaviconLoader.jsm :: onStopRequest :: line 199"  data: no]
    onStopRequest resource:///modules/FaviconLoader.jsm:199
    InterpretGeneratorResume self-hosted:1255
    next self-hosted:1210

**Comment by akatsoulas** [comment]
This is similar to #3571 - Closing
