### ISSUE TITLE
Error message displayed on https://support.allizom.org/en-US/questions/new/firefox-amazon-devices/firefox-fire-tv page

### ISSUE THREAD

**Issue by rleitan** [mozilla/kitsune#3551]
[STR]:
1. Go to https://support.allizom.org/en-US/questions/new/firefox-amazon-devices/firefox-fire-tv

[Actual result]:
An Error Occurred
<img width="884" alt="2019-04-24_15h32_03" src="https://user-images.githubusercontent.com/41474886/56659551-1ede4c00-66a6-11e9-8297-16cace12c5a6.png">

**Comment by akatsoulas** [comment]
Similar to #3571 - closing

**Comment by viorelaioia** [comment]
@akatsoulas , this is still happening

**Comment by akatsoulas** [comment]
The error message is `Product matching query does not exist.`
