### ISSUE TITLE
[staging] Extra section/banner displayed above the header 

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/kitsune#3552]
Homepage (https://support.allizom.org) has an extra banner displayed above the header section. Browser console shows "**Error: Error retrieving geoip data**" on all pages 

![extra banner](https://user-images.githubusercontent.com/5293100/56659290-631d1c80-66a5-11e9-9785-ef9104475429.png)

**Comment by viorelaioia** [comment]
This is still happening 
CC @akatsoulas

**Comment by rleitan** [comment]
I can reproduce the issue in production (az locale)
![2019-05-17_14h40_49](https://user-images.githubusercontent.com/41474886/57925731-ef3fef80-78b1-11e9-85e4-23d39a176d91.png)
