### ISSUE TITLE
[FxA] Navigation menu is broken for some locales

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/kitsune#3559]
Eg http://127.0.0.1:8000/ar/

**Comment by akatsoulas** [comment]
This is also happening to the updated product page.

**Comment by kkellydesign** [comment]
This fix will be attached to our next PR. 

https://github.com/lincolnloop/kitsune/commit/b04d978daeafda7650e6b3cb8326e1e187ccf7ef

<img width="1365" alt="Screen Shot 2019-04-30 at 2 02 15 PM" src="https://user-images.githubusercontent.com/202590/56983189-06ac7800-6b51-11e9-86dd-d746f9c37841.png">

**Comment by viorelaioia** [comment]
Found issues: https://github.com/mozilla/kitsune/issues/3625, https://github.com/mozilla/kitsune/issues/3626
