### ISSUE TITLE
Make the footer sticky to the bottom of the page.

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/kitsune#3563]

**Comment by akatsoulas** [comment]
@kkellydesign can you take a look at this when you have some time?

**Comment by kkellydesign** [comment]
This is fixed globally in the upcoming PR. 

<img width="1239" alt="Screen Shot 2019-05-15 at 11 08 11 AM" src="https://user-images.githubusercontent.com/202590/57786589-c11bad80-7701-11e9-95c1-c270b336a875.png">

**Comment by mcranston18** [comment]
Will be fixed once https://github.com/mozilla/kitsune/pull/3636 is merged in
