### ISSUE TITLE
[FxA] Mobile designs for the updated product page.

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/kitsune#3573]

**Comment by viorelaioia** [comment]
Responsive pages:
Landing page
Login/Sign Up page
User profile page
Edit profile page

**Comment by viorelaioia** [comment]
Issues logged:

- [ ] https://github.com/mozilla/kitsune/issues/3676

- [ ] https://github.com/mozilla/kitsune/issues/3678

- [ ] https://github.com/mozilla/kitsune/issues/3679

- [ ] https://github.com/mozilla/kitsune/issues/3677

- [ ] https://github.com/mozilla/kitsune/issues/3680

- [ ] https://github.com/mozilla/kitsune/issues/3674

- [ ] https://github.com/mozilla/kitsune/issues/3673
