### ISSUE TITLE
[staging] Search after " " (space) shows empty page

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/kitsune#3578]
STR:
Navigate to https://support.allizom.org/en-US/
In the search bow, enter " ", then hit enter

Expected:
"We couldn't find any results for in English." is displayed

Actual:
Empty page is shown

<img width="1265" alt="Screen Shot 2019-05-03 at 13 33 46" src="https://user-images.githubusercontent.com/5293100/57132539-94ce6b80-6da8-11e9-8e14-0467af60828c.png">

**Comment by rleitan** [comment]
The same behaviour for very long searched terms.

![2019-05-03_15h22_51](https://user-images.githubusercontent.com/41474886/57137054-53918800-6db7-11e9-8ebe-f3ad52797604.png)

**Comment by akatsoulas** [comment]
@viorelaioia @rleitan is this happening to prod too?
