### ISSUE TITLE
Error occurs when displaying an article history 

### ISSUE THREAD

**Issue by rtanglao** [mozilla/kitsune#3591]
**Steps to Reproduce**

1. Go to the history of any SUMO KB article e.g. https://support.mozilla.org/en-US/kb/add-ons-disabled-or-fail-to-install-firefox/history

**Expected Result** 

1. History of the article is displayed

**Actual Result**

1. Error page is displayed. See screenshot (Firefox 66.0.4, Windows 10, surface book 2 from the Mozilla Vancouver, Canada office):

![Screenshot_2019-05-06 An Error Occurred Mozilla Support](https://user-images.githubusercontent.com/45195/57258726-1412a800-7012-11e9-8523-5f2f77c99f97.png)
 
This is priority 2 (not P1)  I think because we need history to work to edit new articles, and modify and localize articles

**Comment by jonisavage** [comment]
This error is now also happening when I'm editing a page.

**Comment by jgmize** [comment]
Looking into this, I found an 11 instances (at the time of this writing)  of `kitsune.wiki.models:MultipleObjectsReturned` on `/en-US/kb/private-browsing-firefox-ios/history`: https://rpm.newrelic.com/accounts/1299394/applications/55558271/filterable_errors#/show/45469bab-7064-11e9-9af0-0242ac11000a_0_3724/stack_trace?top_facet=transactionUiName&primary_facet=error.class&barchart=barchart

Looking at the [source for the document_revisions view in the production branch](https://github.com/mozilla/kitsune/blob/production/kitsune/wiki/views.py#L560-L589) leads me to wonder if perhaps there are 2 documents matching the locale & document_slug for this URL. I will connect to the production DB next to determine if this is the case.

**Comment by jgmize** [comment]
Following up on the above, there is only one doc matching that locale and slug:

> [oregon-a](https://github.com/jgmize/dotfiles/blob/39acf8992df91c7f0871bfeb72d9ddfbb3f8affb/.bash_functions.d/k8s#L83-L87)
> [ns](https://github.com/jgmize/dotfiles/blob/39acf8992df91c7f0871bfeb72d9ddfbb3f8affb/.bash_functions.d/k8s#L21-L23) sumo-prod
> [k8s-bash](https://github.com/jgmize/dotfiles/blob/39acf8992df91c7f0871bfeb72d9ddfbb3f8affb/.bash_functions.d/k8s#L45-L55)
> [./manage.py shell_plus](https://django-extensions.readthedocs.io/en/latest/shell_plus.html)
> In [1]: Document.objects.filter(locale='en-US', slug='private-browsing-firefox-ios')
> Out[1]: [<Document: [en-US] Private Browsing in Firefox for iOS>]

**Comment by jgmize** [comment]
The issue is here: https://github.com/mozilla/kitsune/blob/production/kitsune/wiki/permissions.py#L110

Continuing the session from above:
```
In [2]: Locale.objects.get(locale='en-US')
---------------------------------------------------------------------------
MultipleObjectsReturned                   Traceback (most recent call last)
<ipython-input-2-a33468544431> in <module>()
----> 1 Locale.objects.get(locale='en-US')

/venv/lib/python2.7/site-packages/django/db/models/manager.pyc in manager_method(self, *args, **kwargs)
    125         def create_method(name, method):
    126             def manager_method(self, *args, **kwargs):
--> 127                 return getattr(self.get_queryset(), name)(*args, **kwargs)
    128             manager_method.__name__ = method.__name__
    129             manager_method.__doc__ = method.__doc__

/venv/lib/python2.7/site-packages/django/db/models/query.pyc in get(self, *args, **kwargs)
    336         raise self.model.MultipleObjectsReturned(
    337             "get() returned more than one %s -- it returned %s!" %
--> 338             (self.model._meta.object_name, num)
    339         )
    340

MultipleObjectsReturned: get() returned more than one Locale -- it returned 2!
```

**Comment by jgmize** [comment]
```
In [4]: Locale.objects.filter(locale='en-US').values()
Out[4]: [{'locale': u'en-US', u'id': 16L}, {'locale': u'en-US', u'id': 113L}]
```

**Comment by jgmize** [comment]
I'm not sure how we ended up with duplicate 'en-US' locales, but I think the simplest resolution will be to delete the newer one with the higher id, and we should follow up with a uniqueness constraint on the locales to prevent this from happening again.

**Comment by metadave** [comment]
there are also 2 `af` locales

**Comment by jgmize** [comment]
Continuing the session above:
```
In [5]: dupe = Locale.objects.get(id=113)

In [6]: dupe.delete()
```

**Comment by jgmize** [comment]
I'll go ahead and delete the higher id duplicate `af` locale that @metadave found.

**Comment by jgmize** [comment]
```
In [12]: Locale.objects.filter(locale='af').values()
Out[12]: [{'locale': u'af', u'id': 49L}, {'locale': u'af', u'id': 114L}]

In [13]: dupe_af = Locale.objects.get(id=114)

In [14]: dupe_af.delete()
```

**Comment by jgmize** [comment]
After deleting the duplicate locales https://support.mozilla.org/en-US/kb/add-ons-disabled-or-fail-to-install-firefox/history is working again

**Comment by rtanglao** [comment]
works for me! thanks! closing  we are good for ff66.0.5 sumo kb updates which should i think be required either tomorrow afternoon Berlin time or tomorrow morning Pacific!
