### ISSUE TITLE
White screen when publishing a new article

### ISSUE THREAD

**Issue by jonichan** [mozilla/kitsune#3592]
This has happened three times in the past week when I create a new article.

Steps:

1. Create a new article on https://support.mozilla.org/en-US/kb/new?
2. Click Submit for Review:

Expected result:
My article gets submitted and my revision shows up on the history log for review.

Actual result:
The page shows a white screen of death (see [screenshot](https://send.firefox.com/download/d4e4f61c0be4939d/#-wVp5JSR_YQxnMCiI8sBiQ)). Clicking the back button takes me to a blank form, losing all my work.

**Comment by rtanglao** [comment]
@jonisavage  i think this was fixed as part of issue #3591, please re-test! and then close if it's fixed!

**Comment by akatsoulas** [comment]
This should be fixed. I am closing it for now. Please re-open if the issue reappears.

**Comment by jonisavage** [comment]
This happened again today. I'm unable to reopen the bug. Can you re-open, @akatsoulas ?

**Comment by jonisavage** [comment]
This happened a second time today while submitting a revision to an existing article: https://support.mozilla.org/en-US/kb/common-forum-responses/edit/180791#preview
