### ISSUE TITLE
[fxa] Display name field from edit profile page is not pre-populated from fxa

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/kitsune#3598]
**STR:**
1. Create an fxa account
2. Add avatar and display name
3. Login to sumo with the fxa account created in step 1

**Expected:**
Edit profile page is returned, display name fields is pre-populated with the values added in step 2

**Actual:**
Display name fields is not pre-populated

![fields not pre-populated](https://user-images.githubusercontent.com/5293100/57296771-7af99500-70d6-11e9-9de9-50e348f51c79.png)

**Comment by mcranston18** [comment]
@viorelaioia We are now populating the display name from FXA to SUMO if the user does not already have a SUMO display name.

However, using the FXA avatar (and our new strategy) with avatars will require its own ticket.
