### ISSUE TITLE
[FxA] Unexpected error when change email preferences button is clicked

### ISSUE THREAD

**Issue by rleitan** [mozilla/kitsune#3599]
[Precondition]:
Create a FxA account through https://dev.sumo.moz.works/en-US/ page

[STR]:
1.Open https://stable.dev.lcip.org
2.Log in with the account from Precondition
3.Click "Change" button from "Email preferences" 

[Actual result]:
Unexpected error
![2019-05-07_14h44_55](https://user-images.githubusercontent.com/41474886/57296873-bac07c80-70d6-11e9-808f-ef77518044c1.png)

**Comment by akatsoulas** [comment]
This is related to Firefox Accounts and not to SUMO thus I am closing the bug. Please reach out via slack if you have any more questions on this.
