### ISSUE TITLE
[fxa] Edit profile for new users - email field has “Change” button available, which returns 404

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/kitsune#3600]
**STR:** 
Create an fxa account
Login to sumo with the fxa account created in step 1 => Edit profile page is returned

**Expected:**
Change email button is not available

**Actual:**
Change email button is available, clicking it returns a 404 page 

![image](https://user-images.githubusercontent.com/5293100/57297044-3de1d280-70d7-11e9-9519-6b000a113d57.png)

![image](https://user-images.githubusercontent.com/5293100/57297069-4cc88500-70d7-11e9-9d56-b463886679a8.png)

**Comment by akatsoulas** [comment]
This is the intended behavior. Also there is pr #3596 which hides the link. I will deploy this PR asap.
