### ISSUE TITLE
[fxa] "Sign me up" button returns old registration page

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/kitsune#3601]
**STR:**

1. Navigate to https://dev.sumo.moz.works/en-US/get-involved/kb (Also by clicking Volunteer -> Help write articles)
2. Click "Sign me up" button

**Expected:**
New sign up/sign in page is returned, with fxa available

**Actual:**
Old sumo registration page is returned 

**Note:**
"Sign me up" button that redirects to the old registration page is available on the following pages as well:
https://dev.sumo.moz.works/en-US/get-involved/questions
https://dev.sumo.moz.works/en-US/get-involved/l10n

**Comment by mcranston18** [comment]
Fixed now that #3616 is merged in
