### ISSUE TITLE
[fxa] No default avatar for new accounts on edit profile page 

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/kitsune#3602]
![default avatar](https://user-images.githubusercontent.com/5293100/57298831-c8c4cc00-70db-11e9-9778-bdf8f9f2f030.png)

**Comment by mcranston18** [comment]
Will be fixed once https://github.com/mozilla/kitsune/pull/3636 is merged in

**Comment by viorelaioia** [comment]
Avatar still doesn't look good. @akatsoulas , is the avatar from the [designs](https://app.zeplin.io/project/5c940ea1d154600581d4377b/screen/5cc0640f888a0b26783d7886) supposed to be the default one, when a user creates a new sumo profile? 
![avatar](https://user-images.githubusercontent.com/5293100/57930588-09cc9580-78bf-11e9-97ec-d6ff1cd55a5a.png)

**Comment by akatsoulas** [comment]
Acceptance criteria:

* SUMO accounts can either have gravatars or an uploaded photo
* Accounts migrated to the FxA auth method will use the avatar from Firefox Accounts
* The profile picture can only be changed through Firefox Accounts management page and not through SUMO.
* The new image is propagated throughout the site every time a user logs in
