### ISSUE TITLE
[FxA] Username is not editable

### ISSUE THREAD

**Issue by rleitan** [mozilla/kitsune#3603]
[STR]:
1.Create a new account through FxA

[Expected result]:
The username should be editable on https://dev.sumo.moz.works/en-US/users/edit page

[Actual result]:
No change button for username

![2019-05-07_15h25_44](https://user-images.githubusercontent.com/41474886/57299085-64563c80-70dc-11e9-82e5-44fec6acc110.png)

**Comment by flekkowich** [comment]
Correct, user can edit display name not username.

**Comment by rleitan** [comment]
It was confusing because the username field is not displayed on edit page (only display name) in the designs and I can see it on edit page (in dev env).

I confirm the display name can be edited and it's updated in the user's menu, instead of the username.
Also if I delete the display name, the username is re-displayed in the user's menu.

**Comment by kelimuttu** [comment]
May I suggest to reopen this issue again? At least I've heard several complaints from the users that they don't want their email address automatically set as their username for their profile. Several concerns about this: 
1. People weren't notified that their email address will be set as their default username and they won't be able to change it (display name is another thing). 
2. Privacy concern. Lots of people use their real name in their email address but they might don't want to use their real name as a username for their SUMO account.

**Comment by akatsoulas** [comment]
@kelimuttu could you please file a new issue for this?

**Comment by kelimuttu** [comment]
@akatsoulas done in #3896
