### ISSUE TITLE
Invalid `rel="canonical"` `href` value on all /kb and /questions pages

### ISSUE THREAD

**Issue by jpetto** [mozilla/kitsune#3607]
The `href` values in `<link rel="canonical" href="...">` on all `/kb` and `/questions` pages are relative URLs. These must be absolute URLs to function properly.

https://developers.google.com/web/tools/lighthouse/audits/canonical

**Comment by jpetto** [comment]
Additionally, the relative URLs currently generated include locale, which I don't think should be the case.

**Comment by akatsoulas** [comment]
@jpetto shall we close this issue?

**Comment by jpetto** [comment]
Ah, yep. Fixed in #3613.
