### ISSUE TITLE
[staging] No article suggested when results are not found

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/kitsune#3610]
**STR:**
Search after "full screen screenshot"
Filter the results to "Firefox Lite"

**Expected:**
"We couldn't find any results for full screen screenshot in English. Maybe one of these articles will be helpful?" message is displayed and there is at least 1 article suggested 

**Actual:**
"We couldn't find any results for full screen screenshot in English. Maybe one of these articles will be helpful?" message is displayed, but there are not articles suggested 

![no suggestions](https://user-images.githubusercontent.com/5293100/57362061-a0de7280-7186-11e9-84bf-2c2844d7a97e.png)

**Comment by akatsoulas** [comment]
This was happening only in stage because ES was not working/had no content. Is working properly in prod.
