### ISSUE TITLE
Help articles menu doesn't match prod's menu

### ISSUE THREAD

**Issue by rleitan** [mozilla/kitsune#3612]
[STR]:
1. Open https://support.allizom.org/en-US/
2. Go to the Help articles section

[Actual result]:
Help articles menu doesn't match prod's menu 

![2019-05-08_12h15_37](https://user-images.githubusercontent.com/41474886/57364051-03397200-718b-11e9-850c-b3c71e5ad66b.png)

**Comment by akatsoulas** [comment]
This is related to content. The staging environment does not have the latest copy of the db that prod is running.
