### ISSUE TITLE
[fxa] Error page returned when linking sumo account to an fxa with different email, user can still login with sumo user/password 

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/kitsune#3615]
**Preconditions:**
Have a user/password sumo account with a certain email address
Have an fxa account with an email different from the one used in the sumo account

**STR:**
1. Login to sumo with user/password, using the credentials from precondition
2. In edit page, click "Continue with firefox accounts" button from the banner
3. Enter the fxa credentials from precondition (email is different from the one used in step 1), then click "Sign in" button

**Expected:**
Profile page is returned, "Good news" banner is displayed.

**Actual:**
Error page is returned. If I navigate to profile page, the new email is displayed, so the migration seemed to happen. The "Heads Up" banner, asking to switch to fxa login is still present though.
If I logout, I am able to login again using the sumo account (user/password).

![link fxa - different emails](https://user-images.githubusercontent.com/5293100/57444164-2e3dc780-7258-11e9-80e3-3ad7ee4ae04b.png)
![image](https://user-images.githubusercontent.com/5293100/57444227-46ade200-7258-11e9-88da-397bfc379c35.jpeg)

**Comment by viorelaioia** [comment]
This issue allows me to have 2 accounts in sumo with the same email address, but different usernames, depending on the method I choose to select (fxa or user/password).
![m1](https://user-images.githubusercontent.com/5293100/57450719-e6bf3780-7267-11e9-9215-4f90eee1d771.png)
![m2](https://user-images.githubusercontent.com/5293100/57450720-e6bf3780-7267-11e9-9e27-be632c8b17f4.png)

**Comment by akatsoulas** [comment]
this should be fixed in #3627

**Comment by rleitan** [comment]
Looks good! the Good news banner is displayed as described in https://github.com/mozilla/kitsune/issues/3562
