### ISSUE TITLE
[FxA]: The FxA activation link received via email should redirect to SUMO account

### ISSUE THREAD

**Issue by rleitan** [mozilla/kitsune#3618]
[STR]:
1.Log in http://dev.sumo.moz.works with sumo account(existing one)
2.Click to link your FxA account
3.Create a fxa new account through fxa screen
4.Activate the newly created account via email

[Expected result]:
The activation link received via email should redirect to sumo account

[Actual result]:
Account verified
Success
You are now ready to use sumo_dev_cluster

If I go in sumo page I still see the Continue with Firefox Account banner

[Note]:
The linking is done only after I follow the flow with logging in FxA again

**Comment by akatsoulas** [comment]
This is the normal behavior as we cannot ensure that a user will be redirected to the sumo page/tab. This flow should work if the creation and verification of the FxA account happen within the same tab. Does this work?
