### ISSUE TITLE
Deploy Django upgrade to production

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/kitsune#3621]
Checklist:
- [x] Release latest master in stage
- [x] Final search QA
- [ ] Fix logout redirect #3581
- [x] Investigate issue #3585 
- [x] Fix indexing issue #3620
- [x] Add an announcement to notify users that site will be read-only for 30minutes
- [x] Release upgrade to production
- [x] Clear the cache
- [x] Update production branch with current master

**Comment by jgmize** [comment]
Per our discussion on zoom, we'll want to put the site in read only mode for ~30 min during the upgrade deployment. @akatsoulas what time works best for you?

**Comment by akatsoulas** [comment]
@jgmize we can keep the window that we have at 14:00 UTC

**Comment by akatsoulas** [comment]
@jgmize :beers:
