### ISSUE TITLE
[fxa] Header is different from the designs for some locals, when logged in

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/kitsune#3626]
**Env:**
mac 10.12, Safari and Chrome
ubuntu 16.04, Chrome
Windows 10, Chrome

**STR:**
Login to sumo dev
Switch the language to "Deutsch"

**Expected:**
Header looks like in the designs.

**Actual:**
Header looks different from the designs, as the menu options don't fit on one line. 
Hovering over the second option shows the menu cut off.

**Note:**
This also happens for "Nederlands" and "HSB".

<img width="1269" alt="Screen Shot 2019-05-10 at 13 23 14" src="https://user-images.githubusercontent.com/5293100/57528135-27878100-733a-11e9-9369-2cfee22bd908.png">

<img width="1248" alt="Screen Shot 2019-05-10 at 15 42 31" src="https://user-images.githubusercontent.com/5293100/57528191-59004c80-733a-11e9-94d0-17324408fd3f.png">

**Comment by kkellydesign** [comment]
I've made some improvements on this, but I'm not sure how best to avoid wrapping when some of the menu items are so long. Here's the current status: 

* When everything can fit on one line, it does. On some languages when wrapping is inevitable, the dropdowns still work and are never hidden. 
* When the browser width is smaller than 960px wide, the mobile navigation is enabled. 

Once this is updated, please let me know if you have any ideas for a more elegant solution with these longer languages. I'm happy to make further revisions. Here's an example from the upcoming PR: 

<img width="1030" alt="Screen Shot 2019-05-20 at 11 41 36 AM" src="https://user-images.githubusercontent.com/202590/58034289-3fa68f80-7af4-11e9-9b01-b6746a3ee68e.png">

**Comment by viorelaioia** [comment]
>     * When the browser width is smaller than 960px wide, the mobile navigation is enabled.

This behavior is not consistent across all pages. E.g: [Contributors forums page](https://dev.sumo.moz.works/en-US/forums) or [Aaq page](https://dev.sumo.moz.works/en-US/products/firefox/protect-your-privacy)
<img width="1028" alt="Screenshot 2019-05-22 at 15 57 09" src="https://user-images.githubusercontent.com/5293100/58176295-a7064000-7caa-11e9-9817-1940f2e5eb0d.png">

**Comment by kkellydesign** [comment]
This is in https://github.com/mozilla/kitsune/pull/3711

> This behavior is not consistent across all pages.

I just made the header and footer responsive across all pages. I've done enough global work with the grid to be confident that these changes aren't going to adversely affect the forums and other parts of the app that are outside the scope of this project. There's still a lot of work to be done to make the entire app mobile-first and responsive, but at least now we don't have two separate navigation behaviors depending on which page you're on.

**Comment by viorelaioia** [comment]
There are still a lot of pages where the drop-down is not displayed entirely on the page.
Easy way to reproduce this in Safari: 

1. Navigate to [homepage](https://support-dev.allizom.org/en-US/)
2. Reduce your browser window, until the header menu items are displayed on 2 rows
3. Hover over the "Contributor Tools" menu item
4. Switch language and repeat steps 1-3 

Example:
English:
<img width="1251" alt="Screen Shot 2019-06-11 at 17 29 32" src="https://user-images.githubusercontent.com/5293100/59281730-6c237680-8c70-11e9-9832-18d3cde7a69f.png">

French:
<img width="1280" alt="Screen Shot 2019-06-11 at 17 30 46" src="https://user-images.githubusercontent.com/5293100/59281760-79d8fc00-8c70-11e9-8125-526ca2b5c5e5.png">

**Comment by kkellydesign** [comment]
I just changed the dropdown on the left-aligned menus to be aligned with the left side of the parent item. This changes the design a bit, but it solves 100% of the issues mentioned here without relying on javascript to catch whether items are hidden off-canvas. This is tucked in with the PR that I opened this morning, https://github.com/mozilla/kitsune/pull/3733

Here's a screenshot – let me know what you think. 

<img width="762" alt="Screen Shot 2019-06-11 at 2 13 52 PM" src="https://user-images.githubusercontent.com/202590/59296335-b34f3e80-8c53-11e9-8b52-6a1e0a156bed.png">

**Comment by rleitan** [comment]
I can reproduce the issue described by Viorela, on Safari with FA locale(RTL languages).

<img width="975" alt="Screenshot 2019-06-19 at 13 40 06" src="https://user-images.githubusercontent.com/41474886/59759007-d69f6c80-9297-11e9-9609-244dc71e21dc.png">

@kkellydesign

**Comment by kkellydesign** [comment]
Dropdowns are fixed in RTL dropdowns, in https://github.com/mozilla/kitsune/pull/3742

<img width="567" alt="Screen Shot 2019-06-21 at 12 20 55 PM" src="https://user-images.githubusercontent.com/202590/59936945-32e0c880-941f-11e9-9a13-7fd7f4d1b082.png">
<img width="295" alt="Screen Shot 2019-06-21 at 12 20 59 PM" src="https://user-images.githubusercontent.com/202590/59936946-32e0c880-941f-11e9-9b86-9d1534cd3bd8.png">
