### ISSUE TITLE
Profile picture not displayed: the server responded with a status of 404 () when opening a profile page in Chrome

### ISSUE THREAD

**Issue by rleitan** [mozilla/kitsune#3628]
[Environment]:
Windows 10, Mac 10.14 - Chrome
the error is not reproducible on Firefox, but the profile picture is not fully loaded

[
[STR]:
1.Open https://dev.sumo.moz.works/en-US/user/roxana_leitan

[Expected result]:
The profile picture should be displayed

[Actual result]:
The profile picture is not displayed
Browser Console errors:
i0.wp.com/dev-cdn.sumo.mozilla.net/https%3A/stable.dev.lcip.org/profile/a/00000000000000000000000000000000?ssl=1:1 Failed to load resource: the server responded with a status of 404 ()
roxana_leitan:1 Access to XMLHttpRequest at 'https://location.services.mozilla.com/v1/country?key=fa6d7fc9-e091-4be1-b6c1-5ada5815ae9d' from origin 'https://dev.sumo.moz.works' has been blocked by CORS policy: Request header field x-csrftoken is not allowed by Access-Control-Allow-Headers in preflight response.

<img width="1414" alt="Screenshot 2019-05-10 at 16 30 00" src="https://user-images.githubusercontent.com/41474886/57531701-bb5d4b00-7342-11e9-8ddf-87af72d8570a.png">

**Comment by akatsoulas** [comment]
Similar to #3684
