### ISSUE TITLE
Localized announcement does not display in selected locale

### ISSUE THREAD

**Issue by madasan** [mozilla/kitsune#3629]
**STR**:
1. Log in to support.mozilla.org/admin
2. Create an announcement and set it to display only in 1 locale (pt-BR in this case)

**Expected results**
Banner should be displayed when accessing SUMO in that specific locale (https://support.mozilla.org/pt-BR/)

**Actual results**
English banner is displayed 9currently a second banner is running set to display in all locales).

**Comment by akatsoulas** [comment]
The announcement functionality will be updated. New tickets will follow to track the work.
