### ISSUE TITLE
Ability to export/import full article content (read and edit API)

### ISSUE THREAD

**Issue by nukeador** [mozilla/kitsune#3635]
In order to experiment with new ways to localize articles and probably other projects as well, we would need a way to fully export all editable article fields (including title, description and body markup) and also being able to input it back.

Bonus: 
-Being able to create a new translation of an article that doesn't exist.
-Being able to identify paragraphs that need update from English version.

**Comment by akatsoulas** [comment]
This will be part of ML translation. Closing this issue for now.
