### ISSUE TITLE
[FxA]: The Contributor Tools menu is not opened in RTL position 

### ISSUE THREAD

**Issue by rleitan** [mozilla/kitsune#3644]
[Environment]:
Mac 10.14, Windows 10 - Safari, Firefox, Chrome

[Precondition]:
Log in https://dev.sumo.moz.works/fa/

[STR]:
1. Open https://dev.sumo.moz.works/fa/locales#
2.Hover using the mouse over the Contributor Tools from header

[Expected result]:
The Contributor Tools menu should be displayed

[Actual result]:
The Contributor Tools menu should be positioned RTL

![Screenshot 2019-05-17 at 15 28 34](https://user-images.githubusercontent.com/41474886/57928385-341b5480-78b9-11e9-8b68-3dcaf8be0b84.png)

@mcranston18 @kkellydesign

**Comment by akatsoulas** [comment]
cc @kkellydesign

**Comment by kkellydesign** [comment]
This will be fixed when https://github.com/mozilla/kitsune/pull/3660 is deployed.

<img width="489" alt="Screen Shot 2019-05-20 at 2 25 50 PM" src="https://user-images.githubusercontent.com/202590/58043537-6de39980-7b0b-11e9-8262-622cdc21715f.png">
<img width="294" alt="Screen Shot 2019-05-20 at 2 25 58 PM" src="https://user-images.githubusercontent.com/202590/58043538-6de39980-7b0b-11e9-9aad-c651edca954b.png">
