### ISSUE TITLE
[FxA] User menu is displayed under navigation bar

### ISSUE THREAD

**Issue by rleitan** [mozilla/kitsune#3645]
[Environment]:
Mac 10.14, Windows 10 - Firefox, Safari, Chrome

[Precondition]:
Log in with a valid account

[STR]:
1.Open https://dev.sumo.moz.works/en-US/products/firefox
2.Drag the browser's window margin to minimize it until the language and user menu are displayed on the second row
3.Hover over the user menu

[Actual result]:
User menu is displayed under navigation bar

<img width="750" alt="Screenshot 2019-05-17 at 15 28 34" src="https://user-images.githubusercontent.com/41474886/57932156-ec012f80-78c2-11e9-8189-586c008c29a1.png">

@mcranston18 @kkellydesign

**Comment by akatsoulas** [comment]
cc @kkellydesign

**Comment by kkellydesign** [comment]
On the occasions where wrapping happens, the user navbar now sits above the breadcrumbs as expected. 

<img width="464" alt="Screen Shot 2019-05-20 at 1 43 13 PM" src="https://user-images.githubusercontent.com/202590/58041113-438edd80-7b05-11e9-98c6-93d1c5cfd904.png">
