### ISSUE TITLE
Mobile view not available

### ISSUE THREAD

**Issue by SeburoSUMO** [mozilla/kitsune#3646]
On opening Kitsune on a mobile device, the desktop view is used, not mobile view.

Normally, the mobile view is the default on a mobile device, but currently, only the desktop view is seen.

Even after clearing history, the desktop view is used.  Desktop view is also the default on Firefox Preview.

**Comment by akatsoulas** [comment]
Thanks @SeburoSUMO for submitting this issue. It should be fixed after #3653 . Please reopen if this not the case.
