### ISSUE TITLE
Broken layout for Search page

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/kitsune#3654]
https://dev.sumo.moz.works/en-US/search

![image](https://user-images.githubusercontent.com/5293100/58026416-1ea76400-7b1f-11e9-82f8-78e87a671881.png)

**Comment by akatsoulas** [comment]
cc @kkellydesign

**Comment by kkellydesign** [comment]
This will be fixed when https://github.com/mozilla/kitsune/pull/3660 is merged in. 

<img width="819" alt="Screen Shot 2019-05-20 at 1 35 39 PM" src="https://user-images.githubusercontent.com/202590/58040772-5359f200-7b04-11e9-87db-a7121ad685ec.png">

**Comment by viorelaioia** [comment]
The size of the search field in dev is different from staging/prod. @akatsoulas , do we want to update that as well?
Dev: 
![image](https://user-images.githubusercontent.com/5293100/58093712-c2ece180-7bd7-11e9-9949-00756b33827f.png)
Staging:
![image](https://user-images.githubusercontent.com/5293100/58093769-e1eb7380-7bd7-11e9-805c-91bc769573e9.png)

**Comment by akatsoulas** [comment]
I would say that dev is the correct one
