### ISSUE TITLE
Same logo is shown for several products on questions page 

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/kitsune#3668]
**STR:**
1. Login to sumo dev
2. Click "Get Community Support" link from the header

**Expected results:**
Each product has a different logo

**Actual results:**
Almost all products have the same logo 

![questions new](https://user-images.githubusercontent.com/5293100/58104695-dc008d00-7bed-11e9-8629-d8c721eb8d56.png)

**Comment by akatsoulas** [comment]
This is the default logo used if the product has no other image. It's not a regression from the FxA work but rather the default behavior. Thanks for filing this.
