### ISSUE TITLE
[fxa] Broken layout on different pages

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/kitsune#3669]
- [x] Advanced Search [Page](https://dev.sumo.moz.works/en-US/search/advanced) - Support Questions and Discussion Forums pages

![search advanced](https://user-images.githubusercontent.com/5293100/58105532-54b41900-7bef-11e9-9324-1800940451b1.png)
- [x] Homepage - after adding a search term in the search box 
![image](https://user-images.githubusercontent.com/5293100/58105959-005d6900-7bf0-11e9-817b-b3ba847d8b95.png)
- [x] Add a question page
![image](https://user-images.githubusercontent.com/5293100/58106329-a4dfab00-7bf0-11e9-957b-e943d4eaa88b.png)
- [x] [Recent revisions page ](https://dev.sumo.moz.works/en-US/kb/revisions?locale=&users=&start=&end=)
Stage:
![image](https://user-images.githubusercontent.com/5293100/58232745-00ba4900-7d43-11e9-84e9-8b16e6793b49.png)
Dev:
![image](https://user-images.githubusercontent.com/5293100/58232767-0ca60b00-7d43-11e9-966e-b1e7761636c5.png)

**Comment by akatsoulas** [comment]
cc @kkellydesign

**Comment by kkellydesign** [comment]
This is in https://github.com/mozilla/kitsune/pull/3711

advanced search fixed: 
<img width="761" alt="Screen Shot 2019-06-04 at 11 21 55 AM" src="https://user-images.githubusercontent.com/202590/58891718-0573eb00-86bb-11e9-9f2f-d86aae081fdb.png">
<img width="759" alt="Screen Shot 2019-06-04 at 11 22 01 AM" src="https://user-images.githubusercontent.com/202590/58891725-086edb80-86bb-11e9-8a4a-4f84bf9e3870.png">
<img width="509" alt="Screen Shot 2019-06-04 at 12 44 29 PM" src="https://user-images.githubusercontent.com/202590/58897545-8ab0cd00-86c6-11e9-9e6f-373ed4ba464c.png">

homepage fixed: 
<img width="1060" alt="Screen Shot 2019-06-04 at 10 46 43 AM" src="https://user-images.githubusercontent.com/202590/58889305-af04ad80-86b6-11e9-9cee-169d4e6a7b11.png">

ask a question fixed: 
<img width="1029" alt="Screen Shot 2019-06-04 at 1 25 42 PM" src="https://user-images.githubusercontent.com/202590/58900176-a9b25d80-86cc-11e9-9d17-4a6133ead836.png">

recent revisions page: 
<img width="974" alt="Screen Shot 2019-06-04 at 1 36 08 PM" src="https://user-images.githubusercontent.com/202590/58900772-cac77e00-86cd-11e9-904e-620d4337a3a5.png">

**Comment by rleitan** [comment]
Some of the reported issues are still reproducible 
![2019-06-18_18h25_50](https://user-images.githubusercontent.com/41474886/59697451-81f7e500-91f6-11e9-9e41-60e845b50d45.png)

There are 2 calendars displayed on [revisions page](https://dev.sumo.moz.works/en-US/kb/revisions?locale=de&users=&start=2019-06-06&end=2019-06-21)
<img width="627" alt="Screenshot 2019-06-18 at 18 33 25" src="https://user-images.githubusercontent.com/41474886/59698224-e798a100-91f7-11e9-83d0-be596b490c74.png">

@kkellydesign

**Comment by kkellydesign** [comment]
Hi @rleitan – 
You're looking at the wrong dev site – @akatsoulas just posted a different one in slack:

https://support-dev.allizom.org/en-US/search/advanced

<img width="841" alt="Screen Shot 2019-06-18 at 11 47 07 AM" src="https://user-images.githubusercontent.com/202590/59699100-f4e56980-91be-11e9-8c08-978ef281f432.png">

**Comment by kkellydesign** [comment]
@rleitan I'm seeing the two calendar widgets as well, but I'm also seeing that on the production site: 

https://support.mozilla.org/en-US/kb/revisions?locale=de&users=&start=03%2F01%2F2018&end=06%2F14%2F2019

<img width="1123" alt="Screen Shot 2019-06-18 at 11 55 53 AM" src="https://user-images.githubusercontent.com/202590/59699724-1004a900-91c0-11e9-939d-b509886f5607.png">

Would it be ok if we tackle this one when we dig into the next phase of the project?

**Comment by rleitan** [comment]
@kkellydesign yes, I'll file a different bug for the calendar issue.
But, there's still a problem with the https://support-dev.allizom.org/en-US/search/advanced page, as is not correctly displayed on android

![Screenshot_20190618-191104](https://user-images.githubusercontent.com/41474886/59701313-08fc8b80-91fe-11e9-946d-d0200885bd01.png)

**Comment by kkellydesign** [comment]
@akatsoulas Can you take a look at the user agent for this? We're getting the old mobile templates on the advanced search page.
