### ISSUE TITLE
Error page returned when trying to create a sumo fxa account through the aaq flow

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/kitsune#3672]
**STR:**
1. Navigate to Get involved [page](https://dev.sumo.moz.works/en-US/get-involved)
2. Click "Ask a question"
3. Click "Continue with Firefox Accounts" and create a new fxa account
4. Login to your email and activate you firefox account

**Expected:**
User is successfully registered, homepage is returned

**Actual:**
Error page is returned
![image](https://user-images.githubusercontent.com/5293100/58155231-2af50380-7c7c-11e9-9730-16143f0c8037.png)

**Comment by akatsoulas** [comment]
After talking with @viorelaioia this is not reproducible with any of the accounts that we both tried. Closing for now
