### ISSUE TITLE
[fxa] Burger menu doesn't match exactly the designs

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/kitsune#3673]
**Env:**
Android P, Firefox
iOS 12.2, Firefox and Safari
 
Burger menu doesn't match exactly the designs - no option to "Switch to desktop site" + too much space between "Volunteer" and Languages. Same for logged in version.
![photo_2019-05-22_15-28-00](https://user-images.githubusercontent.com/5293100/58174306-437a1380-7ca6-11e9-919c-46f95a6568f8.jpg)
![photo_2019-05-22_15-33-02](https://user-images.githubusercontent.com/5293100/58174694-2560e300-7ca7-11e9-8c80-cd921449c235.jpg)

CC @kkellydesign

**Comment by kkellydesign** [comment]
I fixed the margin issues here, so there's no extra space between items anymore. And there should be no more "Switch to desktop site", as there's only one site on the pages with this type of navigation. I think this one is good to close.

**Comment by rleitan** [comment]
Verified as fixed!
