### ISSUE TITLE
[FxA]: A long searched term overlaps the magnifying glass icon

### ISSUE THREAD

**Issue by rleitan** [mozilla/kitsune#3676]
[Environment]:
Firefox for Android

[STR]:
1.Open http://dev.sumo.moz.works
2.Type a long text in the search bar

[Expected result]:
The entered term should be fitted in the search field and should not overlap the magnifying glass icon

[Actual result]:
The entered text overlaps the magnifying glass icon
![Screenshot_20190523-114046](https://user-images.githubusercontent.com/41474886/58252603-2eb58280-7d6f-11e9-9e1c-f5bf54e9ae36.png)

[Note]:
The issue is not reproducible if the search bar is displayed in the header

**Comment by kkellydesign** [comment]
This is in https://github.com/mozilla/kitsune/pull/3711

<img width="297" alt="Screen Shot 2019-06-04 at 3 53 47 PM" src="https://user-images.githubusercontent.com/202590/58909484-3e26bb00-86e1-11e9-9a8d-a1576bc6b96a.png">

**Comment by rleitan** [comment]
Verified as fixed!
