### ISSUE TITLE
[fxa] iOS: Page body is scrollable when user menu is opened

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/kitsune#3677]
**Env:**
iPhone 7, iOS 12.3, Firefox, Safari, Chrome

**STR:**

1. Navigate to sumo homepage dev version
2. Click the 3 dots from the right top side, in order to open the user menu
3. Scroll down on the page

**Expected:**
Page doesn't scroll, user needs to close the user menu in order to scroll the page

**Actual:**
Page scrolls in the background when user menu is opened. See [video](https://vimeo.com/338020666)

**Comment by rleitan** [comment]
The page is scrolled behind the header: https://drive.google.com/file/d/16u3sNPEYg3N4mjJaZwDbXHN7DVcsKxT-/view?usp=sharing

**Comment by kkellydesign** [comment]
This is in https://github.com/mozilla/kitsune/pull/3711
