### ISSUE TITLE
[FxA]: Search suggestion position is moved after scrolling the page

### ISSUE THREAD

**Issue by rleitan** [mozilla/kitsune#3678]
[Environment]:
Firefox for Android

[Precondition]:
Have a search suggestion list

[STR]:
1.Open https://dev.sumo.moz.works/en-US/
2.Tap the search bar
3.Scroll the page down

[Expected result]:
The search suggestion should be displayed below the search bar and should be not visible if the page is scrolled enough

[Actual result]:
The search suggestion list is moved to the top of the page

![60750037_433801080767888_5964344878350467072_n](https://user-images.githubusercontent.com/41474886/58261451-05055700-7d81-11e9-90df-f6ed61d6f609.jpg)

**Comment by kkellydesign** [comment]
@rleitan This is a default browser feature, not in our codebase. To my knowlege there's no way to alter this behavior.

**Comment by rleitan** [comment]
> @rleitan This is a default browser feature, not in our codebase. To my knowlege there's no way to alter this behavior.

@flekkowich, any thought?

**Comment by flekkowich** [comment]
@rleitan what browser is this in? Does it behave as expected in other browsers?

**Comment by rleitan** [comment]
It has the same behaviour in Chrome

**Comment by kkellydesign** [comment]
The browser-default autocomplete has been disabled for search fields. [See further explanation here.](https://github.com/mozilla/kitsune/issues/3726#issuecomment-501334297)
