### ISSUE TITLE
[FxA]The search bar margins are changing

### ISSUE THREAD

**Issue by rleitan** [mozilla/kitsune#3679]
[Environment]:
iOS - Firefox

[STR]:
1.Open https://dev.sumo.moz.works/en-US/
2.Tap the Search bar and start typing

[Actual result]:
The search bar margins are changing ( please see the attached screencast)
https://drive.google.com/file/d/1rIAg7psvuNVqft1-SPJUxaX9rtMS7xhV/view

[Note]:
The issue is not reproducible on Android

**Comment by kkellydesign** [comment]
This is in https://github.com/mozilla/kitsune/pull/3711

**Comment by rleitan** [comment]
the issue is verified fixed!
