### ISSUE TITLE
[fxa] No default avatar for sumo non migrated profiles 

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/kitsune#3685]
![image](https://user-images.githubusercontent.com/5293100/58334250-d69e7f00-7e47-11e9-8380-c99898fcdf4e.png)

**Comment by flekkowich** [comment]
@akatsoulas what is status on this? 

I also wonder why we are not using the avatar from FxA as default to align the experience?

**Comment by akatsoulas** [comment]
This is no longer valid.
