### ISSUE TITLE
[FxA] Design issues Banner

### ISSUE THREAD

**Issue by flekkowich** [mozilla/kitsune#3692]
1. Support logo is not centered (height top 20px, height bottom 29px)
2. Padding between grouped nav items should be 20px (currently differs)
3. Padding between Globe and EN should be 10px
4. Size of logo should be 112x48px
5. size of buttons should be 170 x 32px
6. size of globe icon should be 22x22px
7. EN size should be 18pt. 

[See documentation](https://paper.dropbox.com/doc/SUMO-to-FxA-Design-Log--AeA6Z4O4OzGpkViZPWcuYUIDAQ-1FIaChDu7KC0JlWv9ir0D)

**Comment by kkellydesign** [comment]
This is included in https://github.com/mozilla/kitsune/pull/3711

<img width="1227" alt="Screen Shot 2019-06-03 at 9 29 17 AM" src="https://user-images.githubusercontent.com/202590/58806270-d2aaf380-85e3-11e9-99eb-fc72c1c33495.png">

**Comment by viorelaioia** [comment]
Most of the items are fixed, except for these 2:
- [ ] Padding between grouped nav items (Download Firefox button, globe, etc)  should be 20px (it currently differs)
- [ ] Padding between Globe and EN should be 10px (it's currently 9)
