### ISSUE TITLE
[FxA] Log in form design issues

### ISSUE THREAD

**Issue by flekkowich** [mozilla/kitsune#3693]
1. button size should be 350 x60 px
2. Font size of normal text 14pt
3. Padding between top text and button should be 30 px
4. Padding between button and link should be 15px
5. Padding between link to next text section should be 30 px
6. Padding on top white space and bottom should be 110px
[See page 3 ](https://www.dropbox.com/s/17btqpxoprjphg7/Mozilla%20Design%20Review.pdf?dl=0)

**Comment by kkellydesign** [comment]
This is included in https://github.com/mozilla/kitsune/pull/3711

<img width="982" alt="Screen Shot 2019-06-03 at 9 47 07 AM" src="https://user-images.githubusercontent.com/202590/58806659-a93e9780-85e4-11e9-9ff7-16a554ed0d47.png">
