### ISSUE TITLE
[FxA] Design issues Log in form - SUMO account

### ISSUE THREAD

**Issue by flekkowich** [mozilla/kitsune#3694]
1. White space padding top/bottom 46px
2. Padding between sections 30px
3. Font size 14pt
4. Button size should be 120 x 40px. Font size should be 16 pt. Recommended color is HEX #000000. Hover color is HEX #1C1C1C
5. Notice text: Font size should be 11 pt with 16 line height
6. Login problems: font size 16 pt
7. Login problems links: font size 14pt. line height 16 pt. Visited link color is different. Recommended color is HEX #629FF4

[See page 3](https://www.dropbox.com/s/17btqpxoprjphg7/Mozilla%20Design%20Review.pdf?dl=0)

**Comment by kkellydesign** [comment]
This ticket will be included in https://github.com/mozilla/kitsune/pull/3711

<img width="982" alt="Screen Shot 2019-06-03 at 11 07 49 AM" src="https://user-images.githubusercontent.com/202590/58812461-f07e5580-85ef-11e9-8cc6-655fededf599.png">
