### ISSUE TITLE
[FxA] Design Issues - Mobile Menu / Nav

### ISSUE THREAD

**Issue by flekkowich** [mozilla/kitsune#3695]
1. Menu open - change padding to 30 px between all menu options. 
2. Footer divider missed.

**Comment by kkellydesign** [comment]
These items are addressed in https://github.com/mozilla/kitsune/pull/3711

<img width="512" alt="Screen Shot 2019-06-03 at 1 51 56 PM" src="https://user-images.githubusercontent.com/202590/58823094-e9af0d00-8606-11e9-88d1-c084ea61b56f.png">
<img width="581" alt="Screen Shot 2019-06-03 at 1 52 23 PM" src="https://user-images.githubusercontent.com/202590/58823096-e9af0d00-8606-11e9-88f1-4207d720532d.png">

**Comment by rleitan** [comment]
There are things that are not addressed - highlighted in [designs](https://www.dropbox.com/s/17btqpxoprjphg7/Mozilla%20Design%20Review.pdf?dl=0) - page 12.

Also, I can see an extra down arrow after I opened/closed the Contributor Tools menu 
![Screenshot_20190618-164320](https://user-images.githubusercontent.com/41474886/59689707-cd0afb80-91e8-11e9-85ba-2ef921770ca1.png)

@kkellydesign

**Comment by kkellydesign** [comment]
The pip appearing on hover issue is fixed here: 
https://github.com/mozilla/kitsune/issues/3744

https://github.com/mozilla/kitsune/commit/e6df0dfa255ed5b56f680ee14e5b451bdd06e615

These fixes appear in https://github.com/mozilla/kitsune/pull/3742

Lines have been added between nav items. 
The username and avatar has been replaced with "My Profile". 
text-underline has been removed on hover. 

<img width="410" alt="Screen Shot 2019-06-21 at 9 25 30 AM" src="https://user-images.githubusercontent.com/202590/59926297-053c5500-9408-11e9-8255-38f01e24432a.png">

**Comment by rleitan** [comment]
![Screenshot_20190625-120638](https://user-images.githubusercontent.com/41474886/60085550-2d96bd00-9742-11e9-9c65-d8cc2b5b7691.png)

"My profile" should be bold? @flekkowich
