### ISSUE TITLE
[FxA] Mobile Login in form - Design issues.

### ISSUE THREAD

**Issue by flekkowich** [mozilla/kitsune#3696]
1. Button size should be 280 x 44 px.Font size should be 16 pt
2. Font size of normal text and links 14 pt w/ 22 pt line height. 
3. Font size of notice and legal links 12pt

[See page 6](https://www.dropbox.com/s/17btqpxoprjphg7/Mozilla%20Design%20Review.pdf?dl=0)

**Comment by kkellydesign** [comment]
This is in https://github.com/mozilla/kitsune/pull/3711

<img width="408" alt="Screen Shot 2019-06-03 at 3 57 24 PM" src="https://user-images.githubusercontent.com/202590/58830428-4d8e0180-8618-11e9-8a7f-60fd6ede50e3.png">
