### ISSUE TITLE
[FxA] Design Issues - Edit profile view 

### ISSUE THREAD

**Issue by flekkowich** [mozilla/kitsune#3698]
1. All labels of the inputs should be 14 pt
2. Text:  Font size should be 12 pt.
3. FxA button size should be 248 x 40 px. Font size should be 16 pt.

[See page 8](https://www.dropbox.com/s/17btqpxoprjphg7/Mozilla%20Design%20Review.pdf?dl=0)

4. Button size should be 190 x 40 px.Font size should be 16 pt.
5. Cancel should be 12 pt
6. Close account link - Underline is missed

[See Page 9](https://www.dropbox.com/s/17btqpxoprjphg7/Mozilla%20Design%20Review.pdf?dl=0)

Note: if we will be pulling avatar from FxA I recommend we move the Avatar up to the FxA section to make this clear?  cc @akatsoulas what do you think?

**Comment by kkellydesign** [comment]
This is in here: https://github.com/mozilla/kitsune/pull/3711

<img width="677" alt="Screen Shot 2019-06-03 at 4 58 28 PM" src="https://user-images.githubusercontent.com/202590/58834244-d6a93680-8620-11e9-8211-b84ea48c3500.png">

<img width="729" alt="Screen Shot 2019-06-03 at 4 57 33 PM" src="https://user-images.githubusercontent.com/202590/58834228-cabd7480-8620-11e9-9643-78e1890a4994.png">

**Comment by rleitan** [comment]
![2019-06-25_16h35_30](https://user-images.githubusercontent.com/41474886/60102897-41a0e580-9767-11e9-8626-ed8440d07303.png)

There are still design issues with 12pt font size for help text 

@kkellydesign @flekkowich

**Comment by kkellydesign** [comment]
I just submitted a PR that will make this more closely match the designs. There's an issue with the units in the design though – points (12pt) are not often used in CSS, so throughout these designs I've interpreted those directions to mean pixel units (12px) instead. For the most part, that has been accurate, as the point values specified line up with the pixel dimensions that have been requested for buttons and other boxes where pixels have been specified. In this particular case though, if you zoom in on you the design you can see that the text under the e-mail address (that starts “you can change your email..”) is smaller and grey, where the text under the "Edit Profile" headline that starts "tell users a bit" is larger and black. 

There are two text sizes in question here. One is for "help text", which lives under form fields, and another for normal body copy. In the previous PR, I had made both of these areas use the smaller "help text" style, which you can see in the screenshot above. In this PR, I've just changed the text under "Edit Profile" to use the normal style, which better matches the design document. 

Note though that I'm still not using point units, so when @rleitan looks for that again in devtools, she still won't find it. `12pt` is equal to `16px`, which is the default size of the text. The help text is set to `12px`, which if it were converted to points, would be `9pt`. 

I hope that clears things up a little – if you have any other questions on this, let me know. 
<img width="756" alt="Screen Shot 2019-06-25 at 2 13 39 PM" src="https://user-images.githubusercontent.com/202590/60123790-43ae7880-9756-11e9-9abd-f4b61848699f.png">
