### ISSUE TITLE
[FxA] Design issues mobile profile view

### ISSUE THREAD

**Issue by flekkowich** [mozilla/kitsune#3699]
1. Close account underline missing.
2. Add 30 px indent between logo and search.
3. Update profile button should be centered w/ Cancel underneath centered. 

[See page 13](https://www.dropbox.com/s/17btqpxoprjphg7/Mozilla%20Design%20Review.pdf?dl=0)

**Comment by kkellydesign** [comment]
This is in https://github.com/mozilla/kitsune/pull/3711

<img width="458" alt="Screen Shot 2019-06-03 at 5 22 17 PM" src="https://user-images.githubusercontent.com/202590/58835511-2a694f00-8624-11e9-8385-644e34e0b1a4.png">
