### ISSUE TITLE
[FxA] Design issue - Mobile drop down menu

### ISSUE THREAD

**Issue by flekkowich** [mozilla/kitsune#3700]
1.  Shadow parameters:
x: 0
y: 0
Blur: 31 Spread: -12

[See page 14](https://www.dropbox.com/s/17btqpxoprjphg7/Mozilla%20Design%20Review.pdf?dl=0)

**Comment by kkellydesign** [comment]
This is in https://github.com/mozilla/kitsune/pull/3711 

<img width="1072" alt="Screen Shot 2019-06-04 at 7 34 45 AM" src="https://user-images.githubusercontent.com/202590/58876162-465c0780-869b-11e9-9fd1-42b631ff6dd9.png">
