### ISSUE TITLE
The account deleted from UI should be removed from the database

### ISSUE THREAD

**Issue by rleitan** [mozilla/kitsune#3702]
[Precondition]
Log in with an existing account
[STR]:
1.Open https://dev.sumo.moz.works/en-US/user/username/edit
2.Click "Close account and delete all profile information" from the bottom of the page
3.Type your username to confirm then click "Delete my account" button

[Expected result]:
The account should be deleted from the backend too

[Actual result]:
The user is still displayed in the admin interface

**Comment by akatsoulas** [comment]
The accounts in kitsune are closed/deactivated and not deleted. All the profile information are cleared and the user email is replaced with a non existing one. The username remains in case there are questions/answers associated with the user. All other identifiable information are being removed.
