### ISSUE TITLE
[infra] Cannot upload image to new question

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/kitsune#3706]
**STR:**

1. Login to the new prod env
2. Navigate to new question [page](https://prod-tp.sumo.mozit.cloud/en-US/questions/new)
3. Select a product
4. Select a category
5. Add a test question and click "Ask this" button
6. Click "Provide more details" button
7. Upload an image in the "Add images" section

**Expected:**
Image upload is successful

**Actual:**
Image upload is not working, error is shown in browser console

![upload image](https://user-images.githubusercontent.com/5293100/58694899-c6812500-839c-11e9-9945-d540c9799e18.png)

**Comment by akatsoulas** [comment]
This is working now. @viorelaioia can you also verify this?

**Comment by viorelaioia** [comment]
@akatsoulas , I confirm that this issue is not happening anymore.
