### ISSUE TITLE
Remove Webmaker from the AAQ.

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/kitsune#3713]

**Comment by akatsoulas** [comment]
Addressed in #3714

**Comment by rtanglao** [comment]
the equivalent bugzilla bug is:
* https://bugzilla.mozilla.org/show_bug.cgi?id=1506278 (i linked to this github issue from bug 1506278)

**Comment by akatsoulas** [comment]
This is deployed in stage. Pending deployment to prod

**Comment by akatsoulas** [comment]
Deployed to prod.
