### ISSUE TITLE
Timezone and preferred language is automatically set when a new account is created

### ISSUE THREAD

**Issue by rleitan** [mozilla/kitsune#3728]
[STR]:
1.Create SUMO account with fxA

[Expected result]:
Timezone and preferred language should not be auto-filled

[Actual result]:
Timezone is automatically set to US/Pacific and  preferred language to Afrikaans

@akatsoulas

**Comment by akatsoulas** [comment]
The default timezone is the US/Pacific as defined here:
https://github.com/mozilla/kitsune/blob/master/kitsune/users/models.py#L62
