### ISSUE TITLE
[infra][dev] Search is not working for the dev instance. 

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/kitsune#3729]
Sentry error
https://sentry.prod.mozaws.net/operations/sumo-dev-sp/issues/5927227/?query=is:unresolved

cc @ziegeer @kfferrando

**Comment by ziegeer** [comment]
Digging in to this, we realized we had never put the correct credentials on the dev site.  I fixed that with the correct creds and redeployed.  Verified ES works now in dev.  For future reference, every environment in Frankfurt uses the same "failover-prod" ES deployment.
