### ISSUE TITLE
Cannot login with firefox accounts in the dev instance

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/kitsune#3730]
**STR:**
1. Navigate to https://support-dev.allizom.org
2. Click "Log In / Sign Up" button
3. Click "Continue with Firefox Accounts" button

**Expected:**
User is redirected to Firefox accounts login/sign up window

**Actual:**
"The page isn’t redirecting properly" message is displayed, user is redirected to page with [this](https://support-dev.allizom.org/en-US/fxa/authenticate/?scope=openid+email+profile&state=UtDKZsqrLkjEheKHoCZMUV83o1ww9WXU&redirect_uri=https%3A%2F%2Fsupport-dev.allizom.org%2Ffxa%2Fcallback%2F&response_type=code&client_id=) url.
![Screenshot from 2019-06-11 12-28-40](https://user-images.githubusercontent.com/5293100/59260789-eb9b5080-8c44-11e9-96cf-7f3ae1b2bfcd.png)

**Comment by akatsoulas** [comment]
This is now fixed. It was due to a server configuration error. Please reopen if the  problem reappears.
