### ISSUE TITLE
Cannot enter text in the search field

### ISSUE THREAD

**Issue by rleitan** [mozilla/kitsune#3732]
[Environment]:
Firefox for Android

[STR]:
1.Open https://support-dev.allizom.org/en-US/
2.Focus the search bar 
3.Scroll the page up/down multiple times

[Actual result]:
The search field becomes red and the entered text is not displayed

[Note]:
The issue is intermittent

@kkellydesign

**Comment by nicolaslara** [comment]
@rleitan This seems to be an issue in the existing code and not related to the FxA changes (can be replicated on production). I would consider it out-of-scope for the FxA work, but it would make sense to tackle it as part of the redesign (which turns the site responsive)
