### ISSUE TITLE
Firefox Preview articles not staying in the category

### ISSUE THREAD

**Issue by jonichan** [mozilla/kitsune#3734]
STR:
1. Go to edit mode in any Firefox Preview article (example: https://support.mozilla.org/en-US/kb/collections-firefox-preview)
2. Scroll down to "Relevant to" and put a checkbox next to "Firefox Preview"
3. Click Save Description.
4. Go to edit mode again.

Expected result:
The "Firefox Preview" checkbox should still be selected.

Actual result:
The Firefox Preview checkbox is not selected.

**Comment by madasan** [comment]
@akatsoulas we need this by June 25, let's add it to next week's sprint

**Comment by akatsoulas** [comment]
This is now fixed in prod.
