### ISSUE TITLE
Extra scrollbar and down arrow displayed on user menu

### ISSUE THREAD

**Issue by rleitan** [mozilla/kitsune#3744]
[Environment]:
Windows 10 - Firefox release 

[STR]:
1.Open https://support-dev.allizom.org/en-US/
2.Minimize the browser's margins
3.Open the profile menu
4.Hover the username 
5.Hover the Contributor tools

[Actual result]
An unnecessary scrollbar is displayed when hovering over the username
A down arrow is displayed when hovering over the Contributor tools

https://drive.google.com/file/d/1Kfz0JQXlwOvF2lEqcN_rxbEJDLwQ2NPL/view

@kkellydesign

**Comment by kkellydesign** [comment]
This is fixed in https://github.com/mozilla/kitsune/pull/3742

https://github.com/mozilla/kitsune/commit/d6493ad25160244024149bebea328e2b566f73c1

**Comment by rleitan** [comment]
Horizontal scrollbar is displayed after the fix, on My profile and Contributor Tools menu
![2019-06-25_11h54_33](https://user-images.githubusercontent.com/41474886/60084355-05a65a00-9740-11e9-8139-52f3fe9a1666.png)

@kkellydesign

**Comment by kkellydesign** [comment]
confirmed and fixed. 

https://github.com/mozilla/kitsune/commit/5f5e4e64f7c903077044d03b73ac74f96f3cadf5

<img width="556" alt="Screen Shot 2019-06-25 at 3 45 25 PM" src="https://user-images.githubusercontent.com/202590/60128393-8aa16b80-9760-11e9-9925-d7563263dffd.png">
