### ISSUE TITLE
User cannot go back to sumo after clicking the "Manage Firefox Account" button

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/kitsune#3745]
**Preconditions:**
Have a sumo account migrated to firefox accounts.

**STR:**

1. Login to sumo dev using the account from preconditions
2. Navigate to "Edit Profile" page
3. Click "Manage Firefox Account" button => fxa login page is returned
4. Click browser Back button

**Expected:**
User is redirected back to sumo

**Actual:**
Clicking Back has no effect. User cannot navigate back to sumo, unless he/she types the url. 

**Note:**
Another suggestion to fix this is by opening a new tab when the user clicks the "Manage Firefox Account" button

**Comment by akatsoulas** [comment]
This is working properly for me with Firefox nightly.

**Comment by viorelaioia** [comment]
@akatsoulas, It works if you login to accounts.firefox.com, so if after step 3 from STR, you enter your fxa credentials and hit login. If you just get to the page and click Back, then you cannot go back to your sumo profile.

@flekkowich, what do you think about the suggestion to open a new tab when the user clicks "Manage Firefox Account" button from sumo and it's redirected to firefox accounts?

**Comment by akatsoulas** [comment]
@viorelaioia, @flekkowich I am closing this issue since it's not actively worked on. Please reopen in case we want to use a new tab for the management of FxA.

**Comment by flekkowich** [comment]
hi @akatsoulas 

Don't think I can reopen but I like the suggestion of new tab for manage firefox accounts - should be an easy fix :) 

Thanks for the suggestion @viorelaioia
