### ISSUE TITLE
[FxA] Two buttons are displayed in search results.

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/kitsune#3753]
The results page in both simple and advanced search displays the search bar and button two times.

![image](https://user-images.githubusercontent.com/900565/60107987-88470d80-9770-11e9-88d5-d8c6f5e7bb92.png)

**Comment by kkellydesign** [comment]
this is fixed – it appears on the bottom, just like the old design.

https://github.com/mozilla/kitsune/commit/dbb748837953efcd7df68f6e6f5177143351d024
https://github.com/mozilla/kitsune/pull/3756

<img width="1057" alt="Screen Shot 2019-06-25 at 4 08 30 PM" src="https://user-images.githubusercontent.com/202590/60129705-9d696f80-9763-11e9-8edf-5aa87b1fc924.png">
