### ISSUE TITLE
[fxa]: Breadcrumb menu items are not clickable for any product topic page 

### ISSUE THREAD

**Issue by rleitan** [mozilla/kitsune#3761]
[STR]:
1.Open https://support-dev.allizom.org/en-US/products/ios/basic-browsing-firefox-ios
2.Click "Privacy" or "Sync, save and share" options

[Expected result]:
Breadcrumb menu items ("Home, "Firefox for iOS") are clickable

[Actual result]:
Breadcrumb menu items are not highlighted on mouse hover and they are not clickable

@akatsoulas

**Comment by rleitan** [comment]
![2019-06-26_18h20_34](https://user-images.githubusercontent.com/41474886/60192771-1f7a9680-983f-11e9-98c2-fa9a09ab9edf.png)
The Home and Help other users options are not clickable

**Comment by viorelaioia** [comment]
This is also happening on all topics pages, where your get from products. 

Steps to reproduce this:
1. Navigate to https://support-dev.allizom.org/en-US/products/firefox/basic-browsing-firefox
2. Click the title of any subtopic, except the first one (e.g: "Tips and tricks" or "Search suggestions in Firefox")

Expected: 
The subtopics are clickable, user is navigated to new page.

Actual:
Clicking the subtopics has no effect. 

Note:
I cannot either select or copy any text from the subtopics section.
Also, clicking any options from the left menu (e.g: "Sync and Save") has same behavior (nothing happens).

**Comment by kkellydesign** [comment]
This is fixed, and in here: https://github.com/mozilla/kitsune/pull/3764
