### ISSUE TITLE
[fxa] "Translate help to your languages" link's position is not aligned with the rest links

### ISSUE THREAD

**Issue by rleitan** [mozilla/kitsune#3762]
[STR[:
1.Open https://support-dev.allizom.org/en-US/get-involved

[Actual result]:
 "Translate help to your languages" link's position is not aligned with the rest links
![2019-06-26_18h15_12](https://user-images.githubusercontent.com/41474886/60192332-58fed200-983e-11e9-8b4f-9291ad44194b.png)

@kkellydesign

**Comment by kkellydesign** [comment]
https://github.com/mozilla/kitsune/commit/ea6f7ae9696c86b23bc69a31b12af34fb7341f89
https://github.com/mozilla/kitsune/pull/3764

<img width="1086" alt="Screen Shot 2019-06-26 at 1 21 40 PM" src="https://user-images.githubusercontent.com/202590/60201098-88e5af80-9815-11e9-982d-a234a6d64df0.png">
