### ISSUE TITLE
[fxa] Options on "Get Involved" page are not aligned

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/kitsune#3765]
https://support-dev.allizom.org/en-US/get-involved

![Screenshot_2019-06-27 Mozilla Support](https://user-images.githubusercontent.com/5293100/60266645-19dd8900-98f1-11e9-97dd-3b94783d871e.png)

**Comment by kkellydesign** [comment]
This is a duplication of https://github.com/mozilla/kitsune/issues/3762, and was just merged in https://github.com/mozilla/kitsune/pull/3764
