### ISSUE TITLE
Firefox Preview logo is distorted on home page

### ISSUE THREAD

**Issue by jonichan** [mozilla/kitsune#3767]
The logo looks tilted on https://support.mozilla.org/en-US/ but the image itself has the right specs. 

<a href="https://ibb.co/B43HXYT"><img src="https://i.ibb.co/B43HXYT/Screen-Shot-2019-06-27-at-10-05-26-AM.png" alt="Screen-Shot-2019-06-27-at-10-05-26-AM" border="0"></a>

**Comment by akatsoulas** [comment]
This is fixed.
