### ISSUE TITLE
[fxa] Upon minimizing window of get involved page - image overlaps text. 

### ISSUE THREAD

**Issue by flekkowich** [mozilla/kitsune#3774]
reproduce
visit https://support-dev.allizom.org/en-US/get-involved
Minimize window to half screensize (13 inch)

expected behaviour
image should minimize as per https://support.mozilla.org/en-US/get-involved

**Comment by viorelaioia** [comment]
This still looks bad, when resizing the browser window to a certain size. 
For example, for 963 X 662 px, the page looks like this:
<img width="956" alt="Screen Shot 2019-07-02 at 12 31 59" src="https://user-images.githubusercontent.com/5293100/60502115-d5256980-9cc5-11e9-8ad4-a871ffaa54b5.png">

**Comment by kkellydesign** [comment]
fix is in here: https://github.com/mozilla/kitsune/pull/3788

<img width="1023" alt="Screen Shot 2019-07-02 at 8 25 05 AM" src="https://user-images.githubusercontent.com/202590/60512584-ef018500-9ca2-11e9-8398-71b5148a665f.png">
