### ISSUE TITLE
SecurityError when uploading images in Ask a question flow

### ISSUE THREAD

**Issue by rleitan** [mozilla/kitsune#3780]
[STR]:
1.Log in https://support.allizom.org/
2.Go to https://support.allizom.org/en-US/questions/new page
3.Select a product/category, ask a question then click "Provide more details" button (e.g. https://support.allizom.org/en-US/questions/new/mobile/customize?search=a#summarize-question)
4.Click "Browse" button to Add image
5.Select an image from your computer

[Actual result]:
Infinite spinning on the Uploaded images section
Browser console: 
SecurityError: Permission denied to access property "document" on cross-origin object questions-min.7eb39c985142.js:2
 
@akatsoulas

**Comment by akatsoulas** [comment]
I was able to upload an image when asking a new question.
https://support.allizom.org/en-US/questions/1206994
