### ISSUE TITLE
Survey prompt is not correctly displayed 

### ISSUE THREAD

**Issue by rleitan** [mozilla/kitsune#3786]
[Environment]:
Firefox for Android 

[STR]:
1.Open https://support.allizom.org/en-US/

[Expected result]:
The survey prompt should be displayed

[Actual result]:
The survey prompt is displayed on the right side and it's not fully visible

![Screenshot_20190702-114101](https://user-images.githubusercontent.com/41474886/60509784-79afa780-9cd6-11e9-8c7f-7e8f75d77517.png)

@kkellydesign

**Comment by kkellydesign** [comment]
ok, I got the survey to load on your dev site, enough to try and find the code. There is a `surveygizmo.js` file in this project that has a few settings, but it doesn't have any style data associated with it. All of the markup and CSS for this component is loaded from the surveygizmo third party service. 

Further, classes from this service appear to be generated dynamically, so there's no way that I can override any of this CSS from our codebase. I'm not familiar with surveygizmo.com, but I assume there is some access to settings there, or the ability to choose an updated template for your modal that is responsive.

**Comment by akatsoulas** [comment]
The modal has been replaced by a top level banner.
