### ISSUE TITLE
Navigation menu is not displayed on certain browser size  

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/kitsune#3787]
**STR:**
1. Navigate to support.allizom.org
2. Resize your browser window to the point where it should switch from desktop view to mobile view
(e.g:  861 X 870)

**Actual:**
There is a view between desktop and mobile, where the navigation menu is not available at all. 
See https://vimeo.com/345672399

![user menu](https://user-images.githubusercontent.com/5293100/60511068-c21c9480-9cd9-11e9-9ba0-ad8da801a3c4.png)

**Comment by viorelaioia** [comment]
CC: @kkellydesign

**Comment by kkellydesign** [comment]
fixes in https://github.com/mozilla/kitsune/pull/3788

https://www.dropbox.com/preview/nav-bug-fix-070219.webm
