### ISSUE TITLE
(2) Missing user-upload images generating 404s

### ISSUE THREAD

**Issue by kfferrando** [mozilla/kitsune#3793]
We started getting alerts on an increase in 404 responses in CloudFront, upon further investigation, it appears to be from a single web page [0]:

```
$ grep 'uploads/gallery/images/' E2PGHLX595ILKF*|egrep '404\s+http'|cut -d$'\t' -f8|sort|uniq -c |sort -rn                                                          130 ↵
    792 /uploads/gallery/images/2019-06-02-13-01-29-99920a.png
    768 /uploads/gallery/images/2019-06-02-12-58-29-1a0a85.png
```

[0] - https://support.mozilla.org/pt-BR/kb/atualize-o-firefox

**Comment by kfferrando** [comment]
Note: Hitting this page via curl on Linux, iOS and Firefox Stable/Nightly on Windows duplicates the behavior,  Safari/Nightly in MacOS rendered a valid image.

**Comment by akatsoulas** [comment]
this should be fixed now. Please reopen if this is not the case.
