### ISSUE TITLE
 Translate view has shrunk in width

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/kitsune#3796]
Bugzilla entry
https://bugzilla.mozilla.org/show_bug.cgi?id=1563192

**Comment by akatsoulas** [comment]
@kkellydesign could you please take a look at this?

**Comment by rleitan** [comment]
On Mac 10.14 - Safari, the page is grayed out. Not reproducible on Firefox and Chrome

<img width="1440" alt="Screenshot 2019-07-08 at 12 24 24" src="https://user-images.githubusercontent.com/41474886/60799737-68eeae00-a17c-11e9-8fd0-b61371d069a7.png">

@akatsoulas

**Comment by kkellydesign** [comment]
Please provide a URL to recreate the issue. This looks fine for me on this page: https://support.allizom.org/el/kb/import-bookmarks-google-chrome/edit

And your screenshot shows SL, but the URL above gives me a 404 error if I just try to switch out 'el' for 'sl'. 

If it's something specific to my account, please give kasey.kelly@gmail.com the proper account access to see the page, as my account doesn't work on /admin on your dev server.

<img width="1780" alt="Screen Shot 2019-07-08 at 8 06 58 AM" src="https://user-images.githubusercontent.com/202590/60809014-a12fc580-a157-11e9-859e-8d1d370b27c6.png">

**Comment by rleitan** [comment]
I cannot reproduce it anymore. Also tried on other pages and locales. 
@kkellydesign

**Comment by kkellydesign** [comment]
I just ran Google Translate on that warning dialog at the top of your screenshot, and it says "Warning: This page is being edited by [username]." and the button says "Edit it anyway." 

So I'm willing to bet that being greyed out is on purpose, and it would be cross-browser if you could get that error message again.
