### ISSUE TITLE
Get a list of all SUMO pages (content audit)

### ISSUE THREAD

**Issue by jonichan** [mozilla/kitsune#3810]
I'm trying to do a content audit of all KB content and articles so we can reorganize them with our new information architecture. I'd like a list of pages so I can reference them in one place.

I'm told this is possible through a site crawl.

Requirements:
- Title
- Link 
-Search summary (optional, but bonus)

Right now, the only way I can view a list of articles is through https://support.mozilla.org/admin/wiki/document/ (which doesn't have links) or by doing individual searches for them. It This is really time-consuming.

**Comment by rraue** [comment]
It took way longer than I though, as I underestimated the extremly high number of urls I had to crawl, but I got finally to an end with a strong confidence that I crawled most indexed pages.

All indexable pages with url, title, h1, GA and search console data: https://docs.google.com/spreadsheets/d/12HdOh2TVz773hmCQkt0yn6xEldBdhnpl/edit#gid=2046579246

All urls I crawled (2.6 million) as a csv: https://drive.google.com/file/d/13s4Uzy5WuN76M87xQ1LXjGg5q_OXWljf/view?usp=sharing

**Comment by akatsoulas** [comment]
This looks like it's complete. Please re-open if this is not the case.
