### ISSUE TITLE
Sidebar pushes search results outside of the viewport

### ISSUE THREAD

**Issue by callahad** [mozilla/kitsune#3826]
Hi! Twenty minutes before filing this bug, I  was seeing the following on both Firefox and Chrome, with fresh profiles. On both Linux and macOS.

![Screen Shot 2019-07-15 at 17 20 01](https://user-images.githubusercontent.com/24193/61233033-82b56580-a727-11e9-93f0-ad679095ee87.png)

Notice that the sidebar pushes the search results off of the visible page. If the viewport was slightly shorter, it would appear that search was not working at all.

STR:

1. Visit https://support.mozilla.org/en-US/products/firefox
2. Type anything in the search box

However, upon double-checking, I do *not* see this right now. Did something change? Could we have a stale resource on a CDN?

**Comment by akatsoulas** [comment]
@kkellydesign could you take a look into this?

**Comment by kkellydesign** [comment]
@akatsoulas I was able to reproduce and fix the error. It was happening intermittently, but I found the issue. 

https://github.com/mozilla/kitsune/pull/3829

<img width="1078" alt="Screen Shot 2019-07-16 at 10 53 16 AM" src="https://user-images.githubusercontent.com/202590/61305089-35cd9f80-a7b8-11e9-81a0-5ebe6332e4a7.png">

**Comment by akatsoulas** [comment]
The patch has been released to prod.
