### ISSUE TITLE
Search sidebar is displayed in the left side on RTL locale

### ISSUE THREAD

**Issue by rleitan** [mozilla/kitsune#3831]
[STR]:
1.Open https://support.allizom.org/fa/
2.Type something in the search bar

[Expected result]:
Search sidebar should be displayed in the right side on RTL locale and in the left side for LTR locales
@akatsoulas, can you please confirm?

[Actual result]:
Search sidebar is displayed in the left side on RTL locale

<img width="1016" alt="Screenshot 2019-07-17 at 14 56 40" src="https://user-images.githubusercontent.com/41474886/61373685-1eb7ac00-a8a3-11e9-9dd6-bf1be38aebf6.png">

**Comment by akatsoulas** [comment]
Probably this is a question best answered by @flekkowich.

**Comment by flekkowich** [comment]
@rleitan what do we do on other areas of the site? I wonder if we have a set rule in place?

**Comment by rleitan** [comment]
the elements position from the header and footer are switched to RTL. Also the products position is switched
<img width="1437" alt="Screenshot 2019-07-22 at 16 04 54" src="https://user-images.githubusercontent.com/41474886/61638853-8ce0e200-ac9a-11e9-8d68-706e8ab5522f.png">

 @flekkowich

**Comment by flekkowich** [comment]
Then agreed, we should stick to the RTL rules already set on the site. Thanks for checking!

**Comment by akatsoulas** [comment]
The UI is getting updated as part of the responsive redesign so this bug is no longer valid.
