### ISSUE TITLE
"Find help" input field is not displayed correctly on RTL locales

### ISSUE THREAD

**Issue by rleitan** [mozilla/kitsune#3832]
[STR]:
1.Open https://support.allizom.org/ar/
2.Scroll the page down until the "find help" input field is displayed in the header

[Expected result]:
The magnifying glass should be displayed in the left side and "Find help" text should be displayed in the left side of the field

[Actual result]:
The magnifying glass overlaps the "Find help" text in the right side
<img width="630" alt="Screenshot 2019-07-22 at 15 47 05" src="https://user-images.githubusercontent.com/41474886/61638296-640c1d00-ac99-11e9-960c-e92ae9b1df11.png">

**Comment by akatsoulas** [comment]
The UI is getting updated as part of the responsive redesign so this bug is no longer valid.
