### ISSUE TITLE
[FxA] Update login screens w/ new visual identity

### ISSUE THREAD

**Issue by flekkowich** [mozilla/kitsune#3842]
[FxA] Update login screens w/ new visual identity

we need an update on the visual identity to fit the new logo:

Log in screens (desktop / mobile): 
https://app.zeplin.io/project/5c940ea1d154600581d4377b?seid=5cbef4ed7600b94c1d7679cf

**Comment by akatsoulas** [comment]
Closing this since it's already implemented in the Responsive Redesign
