### ISSUE TITLE
Merge locales bn-BD and bn-IN to single locale bn

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/kitsune#3846]
See https://github.com/mozilla-l10n/sumo-l10n/issues/6

**Comment by safwanrahman** [comment]
Thats really needed migration. @akatsoulas have you started working on it?

**Comment by akatsoulas** [comment]
Not yet. I am planning to start working on it tomorrow. Are you interested to work on this?

**Comment by safwanrahman** [comment]
Yes. I am interested to work on this. Will work on this in this weekend.

**Comment by akatsoulas** [comment]
Sounds great! Please let me know if you need anything or have any questions.

**Comment by akatsoulas** [comment]
PR opened on the l10n repo [0]. We need to make the necessary changes here too and start releasing to all the environments.

[0] https://github.com/mozilla-l10n/sumo-l10n/pull/7

**Comment by akatsoulas** [comment]
This is released in prod.

**Comment by rraue** [comment]
If I am not mistaken, these redirect are permanent, but I found a 302. If we do not plan to reverse this soon, we must use a 301.
