### ISSUE TITLE
*find in page* is not working

### ISSUE THREAD

**Issue by Dynamo14324** [mozilla/kitsune#3879]
In firefox application the find in page(search engine) is not working properly.
This is the measure problem which is ongoing from last version of Firefox.
When we search something there should be give a result from the serach engine (find in page search bar).
But it is not working properly.
In last version it was affected but after that it is going properly which you guys update it that red bar if there is not any keywords which is in your search bar and tells that there is nothing in on the page.
But still now it is not working properly it is not showing perfect results.
Though I thought it is a bug which is affecting the Firefox android application which is not showing the perfect results..
For production of bug you have to do is view source again and again from any website and after that you have to do is the open from menu bar the find in page option which will give you the search bar below and again and again search something 10-15 times and it will stuck over there and after that it not show you single word from the search bar which you enter..
Also I tried to open a account for the bug report to the Mozilla bug bounty program but it is not opening they have lot off password security policies...

**Comment by Dynamo14324** [comment]
If this is bug then please give me the findings of bug bounty

**Comment by madasan** [comment]
Hi Dynamo14324,

This repo is for support.mozilla.org website only, unfortunately we don't deal with Firefox bugs. To file a bug report related to Firefox please use bugzilla.mozilla.org

Thanks!
