### ISSUE TITLE
Re-use work from `es_upgrade` branch

### ISSUE THREAD

**Issue by johngian** [mozilla/kitsune#3905]
After briefing @safwanrahman into the search v2 plans and going through the decision document and the old branch we figured out that:

* There are some stuff from the old upgrade branch that we can port to native `elasticsearch-dsl-py`
* We are not gonna touch the changes on the views codebase
* Cleanup and use elasticsearch7

A good starting point would be to:

* Take the `DocType` definitions from the old branch
* Cleanup the `django-elasticsearch-dsl` specific code and some unused code that we identified with @safwanrahman 
* Introduce the new `Document` classes in the new `upgrade-es7` branch

**Comment by johngian** [comment]
@safwanrahman, @akatsoulas thoughts ?

**Comment by akatsoulas** [comment]
We decided in various meeting that we are going to use the work that @safwanrahman already did with a few tweaks in the Search refactoring/rewrite. Since this is the case I am closing this issue.
