### ISSUE TITLE
Question posted time in the FE doesn't match the API creation time

### ISSUE THREAD

**Issue by viorelaioia** [mozilla/kitsune#3915]
**STR:**
1. Login to Sumo staging
2. Navigate to Add a new question page (/questions/new)
3. Fill in the required fields and post a question

**Expected:**
Question posted time is expressed in UTC, it matches the question API creation time value 

**Actual:**
Question posted time is expressed in PST, it is different from the question API creation time value 

![Screenshot_2019-10-08 https support allizom org](https://user-images.githubusercontent.com/5293100/66382575-224f6080-e9c4-11e9-9a36-4c5e065e570f.png)

![Screenshot_2019-10-08 What should I do here Firefox Lockwise Support Forum Mozilla Support](https://user-images.githubusercontent.com/5293100/66382576-224f6080-e9c4-11e9-995d-4d2ce924bb11.png)

**Comment by viorelaioia** [comment]
One more suggestion: we should also add "UTC" at the end, so that people know what is the timezone.

**Comment by jscher2000** [comment]
Hi, I think it is the problem discussed here:

https://support.mozilla.org/forums/contributors/713659

Possibly it will be addressed by another issue (pending deployment):

https://github.com/mozilla/kitsune/issues/3922

**Comment by akatsoulas** [comment]
We are going to stick with the PST timezone and also make it timezone aware in the timestamps. This issue will go away with the pending deployment.
