### ISSUE TITLE
Update favicon with Firefox logo

### ISSUE THREAD

**Issue by jonichan** [mozilla/kitsune#3948]
The favicon on SUMO needs to be updated to reflect the new logo. Please see the new favicons here: https://github.com/mozilla/bedrock/tree/master/media/img/favicons/firefox/browser

**Comment by rtanglao** [comment]
see also: https://bugzilla.mozilla.org/show_bug.cgi?id=1589790

**Comment by akatsoulas** [comment]
This is live in prod.

**Comment by rtanglao** [comment]
verified! thanks!
