### ISSUE TITLE
An error occured when opening "get community support" for Firefox for Amazon devices

### ISSUE THREAD

**Issue by rleitan** [mozilla/kitsune#3957]
[STR]:
1.Open https://support.allizom.org/en-US/questions/new/firefox-amazon-devices/firefox-echo-show

[Actual result]:
"An Error Occurred" error is displayed
![2019-10-24_15h00_04](https://user-images.githubusercontent.com/41474886/67483762-28556a80-f66f-11e9-9357-f554ca6df3eb.png)

[Note]:
Not reproducible for other products e.g: https://support.allizom.org/en-US/questions/new/firefox-lite/get-started
@akatsoulas

**Comment by akatsoulas** [comment]
This is specific to the staging environment as it does not have the product configured.
