### ISSUE TITLE
does not respond to font size changes in Preferences/Preferences/Display

### ISSUE THREAD

**Issue by lhomegit** [mozilla/kitsune#3958]
In Debian Testing with dpi 160 Thunderbird default fonts are too small and it does not respond to font size changes in Preferences/Preferences/Display

Name | Thunderbird
-- | --
60.9.0
20190911203427
Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Thunderbird/60.9.0
Linux 5.2.0-3-amd64

**Comment by fitojb** [comment]
You are filing this bug in the wrong place. This is the repository for the Kitsune support platform and as such, its bugs are related to Kitsune itself, not any other product it might mention in its content. 

For bugs in Thunderbird, please go to bugzilla.mozilla.org
