### ISSUE TITLE
1st AAQ question of the day in UTC time has the wrong time in the question web page

### ISSUE THREAD

**Issue by rtanglao** [mozilla/kitsune#3961]
the test script is [test-time-question-1271141.rb](https://github.com/rtanglao/rt-kits-api2/blob/master/test-time-question-1271141.rb)
```bash
./test-time-question-1271141.rb >./test-time-question-1271141-stdout.txt
```
* [created time in the API](https://github.com/rtanglao/rt-kits-api2/blob/master/test-time-question-1271141-stdout.txt) is: `
  * `"created" => "2019-10-23T00:02:46Z`
  * but the web page shows `Posted 10/22/19, 5:02 PM`: 
![wrong-website-time-question-1271141](https://user-images.githubusercontent.com/45195/67738752-16582c80-f9cd-11e9-907c-f463f88c3f17.png)

  * If the API time is in UTC and correct,  shouldn't the web page show `Posted 10/22/19, 7:46 PM` if [the web page is in Pacific](https://www.worldtimebuddy.com/utc-to-pst-converter?qm=1&lid=100,8,6174041&h=100&date=2019-10-29&sln=2.5-3)?

Perhaps this has something to do with #3922  or #3686 ?

**Comment by akatsoulas** [comment]
Closing this b/c we are reverting back to UTC

**Comment by rtanglao** [comment]
* Tested this  and confirmed, all is well, everything is in PST
* the test script is [test-time-question-1271141.rb](https://github.com/rtanglao/rt-kits-api2/blob/master/test-time-question-1271141.rb)

```bash
./test-time-question-1271141.rb > 11november2019-test-time-question-1271141-stdout.txt
```
* [created time in the API](https://github.com/rtanglao/rt-kits-api2/blob/master/11november2019-test-time-question-1271141-stdout.txt) is: `
  * `"created" => "2019-10-22T17:02:46Z`#PST not Z aka UTC
  * and the [web page for question 1271141](https://support.mozilla.org/en-US/questions/1271141) shows `Posted 10/22/19, 5:02 PM`: 
![11november2019-kitsune-issue-3946-timestamps=in-pacific](https://user-images.githubusercontent.com/45195/68602500-4c7cbe00-045b-11ea-8149-e4ca1d098692.png)
