### ISSUE TITLE
User review

### ISSUE THREAD

**Issue by Audionysos** [mozilla/kitsune#3990]
Hi 
I've read some article and I decided to give a try to your app, as a calendar/task manger.
At the start I created a file and started to note my thoughts on the fly as I was trying to handle it.
Although, this only contains criticism, there all many things I like in the app but I didn't noted those.
I didn't edited it at the end so it is as it is. I don't expect any of this points to be answered but I thought it might be useful to you. 
Happy coding :)

### Thunderbird 68.2.2, Windows 7, 9.11.2019r.

- Well, it's email client after all, but I've wanted to try advertised tasks/calendar capabilities, it  would be nice to not ask me for setting up email account at program start.
- Not sure how this works basically. Do I have a local account to which I add my emails and stuff. It's seams there is not such concept and program installation is itself "local account". What if I had a wife that I share my computer with?   
- After I do "Create new calendar" it confirms that It was created but I don't see any change. I expected a calendar entry to appear under the button.
- I've chosen to create calendar on my computer, but I have no idea where it is stored. I like to know where data/content I create is stored on my hard drive. 
- Can't find general program options. Are there any?
- It's hard to find options button if "Today Pane" is opened and it sits somewhere in the middle of a screen.
- Changing options right from nested context menu is just a tragedy. This may only seem convenient if you know program inside out and know exactly what you want to change. If I want to just check what an option actually do and need to navigate to this again, just to turn it back and than navigate again to check another option man... who really thinks it's a good idea?! 

#### Tasks

- Quick "add new task" text field is hard to notice
- Can't see a way I can put multiple tags on tasks
- Can't see when the task was added
- Don't know how to set default calendar for new task
- Setting date/time is annoying. Why can't I just drag a day/hour on list item?
- Opening task view takes ages , even if it only have a title, like 2-3 seconds - that's HORRIBLE!
- Task deletion don't require confirmation and I cannot undo it.

#### Calendar

- On the first look I don't like how you need to scroll to see a whole date.
- I feel overall little confused by the views, not sure why
- In "Multiweek" view it's had to tell what month I'm in. In a bar above, it always shows "November 4-10" and I don't know why, obviously this is not the part of the year that I'm looking at. It's hard to tell at first glance where the month ends, and it took me a while why some titles have marked month on them while others don't.
- It seem that only difference in "Month" view is that it grays out other moths, but it's still confusing at which moth I'm looking. It's even more confusing when the year is changing.
- I've made so orange strip on a day title and I don't know what is this or how to get rid of it. After a while it's seam like it's a graphics bug made when you try to grab the event over the calendar.
-  I can't drop tasks from "Today Pane" to the calendar, that's sad.
- I'm surprised that task are not integrated with the calendar and I can only convert them and changing one, don't changes the other. I hoped that would be best benefit for using Thunderbird 
- When I try to expand the event to whole day (by mouse dragging) it turns to 15 min event from 0:00
- It's confusing how to confirm time in "Edit Event" view. Why do I need to pick minute if I only what to change the hour?
- I see no way of creating an event which spans across week period form calendar views.
- When multiple categories are chosen, color label is only visible for one of them.

#### Common

- Big missing functionality that I don't see is some easy way of templating tasks/events. Every time I add new similar item, I need to copy it, open, change name, change time... this take lot of time. If you want to for example create shopping list for renovation, with lots of small items, it's not feasible :(
- When I add a category in "edit ..." view. It's not displayed in options with other categories to edit.  

- Can't change properties of multiple items at a time. When I selected all and clicked "open" a separate window was opened for each. Thank god I had only 4 items.
- Can't add icons to items or even categories.
- Cant customize the look of calendar/task view - there are some color blind people out there...
- When exporting, I have not way to specify what to export - events and task are exported together

**Comment by akatsoulas** [comment]
Hi @Audionysos, this repository is only for the site of Mozilla Support and not the products. Because of this I am closing this issue. Thank you for taking the time to give feedback though!
