### ISSUE TITLE
Issues in user experience from paid products to Support.mozilla.org

### ISSUE THREAD

**Issue by flekkowich** [mozilla/kitsune#4058]
Today:

**User open VPN**
-> settings
-> get Help
-> Help & Support  --> Links to https://support.mozilla.org/en-US/products/firefox-private-network-vpn
-> User can't see contact us as user is not logged in
-> User goes to log in, is then sent to profile page instead of back to page where user logged in from. 

**Interim solution:**
User open VPN
-> settings
-> get Help
-> Help & Support  --> Links to https://support.mozilla.org/en-US/products/firefox-private-network-vpn
-> user logs in 
-> User stays on  https://support.mozilla.org/en-US/products/firefox-private-network-vpn

**Ideal solution:**
User open VPN
-> settings
-> get Help
-> Help & Support  --> Links to https://support.mozilla.org/en-US/products/firefox-private-network-vpn
User is logged automaticallu and can see Contact Us.

cc @akatsoulas @jess-cook03 @madasan

**Comment by akatsoulas** [comment]
PR for the interim solution
https://github.com/mozilla/kitsune/pull/4087

**Comment by akatsoulas** [comment]
The interim solution has been deployed to production. The ideal solution is tracked here https://github.com/mozilla/sumo-project/issues/12
