### ISSUE TITLE
Blank notification bar

### ISSUE THREAD

**Issue by finn0** [mozilla/kitsune#4096]
**Type:** Bug

### Description
On every https://support.mozilla.org page, there is a blank notification bar present at top of the page with a close icon.

![support](https://user-images.githubusercontent.com/28824347/71501965-3c7f3900-2865-11ea-9475-36f72e538ca4.png)

### Steps to reproduce
- Open any support page (for ex: https://support.mozilla.org).
- See at top of the page.

If you didn't see any notification bar present at the top of the page, try to open support page in a new profile (about:profiles).

### Expected Behavior
No notification bar, if message is empty.

### Actual Behavior
Blank notification bar.

Edit:
Cannot reproduce it on staging site (https://support.allizom.org/). Should I close this issue?

**Comment by ektaarora3501** [comment]
Hi , I am new to codebase .. Can you tell more about this issue ?

**Comment by finn0** [comment]
Hi, @ektaarora3501 I'm also unfamiliar with codebase.

> Can you tell more about this issue ?

Could you be more specific? If you've any query regarding codebase, you can ping maintainers.

**Comment by ektaarora3501** [comment]
Hey @finn0  I was looking to contribute to this issue ..

**Comment by finn0** [comment]
@ektaarora3501, probably most of the developers are on vacation, but you can find some people on  Mozilla community channel like MozNet, Discourse etc, who can answer your all questions.

And one more thing, I'm not sure about whether this bug exist on current code base or not, because I can't reproduce it on staging site (https://support.allizom.org/).

**Comment by finn0** [comment]
Since I can't reproduce this issue, on newer version of SUMO; I'm closing this issue.

But, I notice one thing, their is still a blank notification pop-up at top bar of the page, which automatically disappears as soon as page loaded. I can reproduce this behavior on both production (https://support.mozilla.org) and staging (https://support.allizom.org) site.

### Steps to reproduce:
- Open a support site (https://support.mozilla.org) in new session.
- Look closely at top bar of the page. You'll notice a blank notification at bar of page, which will automatically disappear.

![mozilla cleaned](https://user-images.githubusercontent.com/28824347/81489518-f18b1e80-9265-11ea-8a1b-25ceb1764c9f.png)
**Fig1:** Screenshot of https://support.mozilla.org


![allizom cleaned](https://user-images.githubusercontent.com/28824347/81489526-010a6780-9266-11ea-876c-f11f9ed19fe4.png)
**Fig2:** Screenshot of https://support.allizom.org

### Expected output
There shouldn't be any blank notification present at top bar of the page.
