### ISSUE TITLE
Blocked chat on *.clona.ru

### ISSUE THREAD

**Issue by slavserver** [mozilla/kitsune#4121]
Hello, I'm the admin resource manager for clona.ru. The new version of your browser blocks some of the content on the * .clona.ru pages. Built-in chat (https://www.cbox.ws/), is blocked on all pages *.clona.ru
eth.clona.ru
etc.clona.ru
clo.clona.ru
exp.clona.ru
ubiq.clona.ru
pirl.clona.ru
ella.clona.ru
aka.clona.ru
nilu.clona.ru
reosc.clona.ru
moac.clona.ru
dbix.clona.ru

Please add to  *.cbox.ws exception for *.clona.ru sites

![Снимок экрана от 2020-01-16 10-59-21](https://user-images.githubusercontent.com/20759703/72504654-4803c580-384f-11ea-8d47-848ee45a833d.png)
![Снимок экрана от 2020-01-16 10-58-48](https://user-images.githubusercontent.com/20759703/72504666-4d611000-384f-11ea-91fd-8c1e84474606.png)

**Comment by akatsoulas** [comment]
Hi @slavserver. This repository is for the platform that runs the support site and not for the browser. If you want to report a bug in Firefox, you should use [Bugzilla](https://bugzilla.mozilla.org/home). Thanks for taking the time to file this issue.
