### ISSUE TITLE
Remove Firefox OS and FireTV from product selection

### ISSUE THREAD

**Issue by kelimuttu** [mozilla/kitsune#4160]
Bugzilla entry: [https://bugzilla.mozilla.org/show_bug.cgi?id=1613321](https://bugzilla.mozilla.org/show_bug.cgi?id=1613321)

**Comment by ritwickraj78** [comment]
@kelimuttu Can I take up this issue?

**Comment by kelimuttu** [comment]
I think you can. Go for it @ritwickraj78

**Comment by akatsoulas** [comment]
We can track this issue in Bugzilla. I am closing the ticket here.
