### ISSUE TITLE
Copyright symbol

### ISSUE THREAD

**Issue by finn0** [mozilla/kitsune#4369]
Isn't it a good idea to use copyright symbol instead of simple `c.` symbol at footer of page (i.e c.1998-2019)?

![copyright](https://user-images.githubusercontent.com/28824347/81497430-01c6ec00-92ae-11ea-9923-602c8d627a69.png)

Also update copyright year from 1998-2020.

**Comment by finn0** [comment]
I thing only replacing `c.` with `&copy;` would be enough at these places, https://github.com/mozilla/kitsune/blob/7c3585c4ff4382e340734419da39527a3ee098b9/kitsune/sumo/jinja2/base.html#L334 and https://github.com/mozilla/kitsune/blob/7c3585c4ff4382e340734419da39527a3ee098b9/styleguide/styleguide-examples/footer.njk#L105

**Comment by nileshdas** [comment]
Taking up this issue

**Comment by finn0** [comment]
@nileshdas If you don't mind, I've kept this issue for myself. I opened this issue to discuss with developers, whether they like a original copyright symbol or no? If you haven't created a pull request, I would like by myself to make a PR.

**Comment by nileshdas** [comment]
Oh sorry! Sure, go ahead!
