### ISSUE TITLE
Wrong sort order

### ISSUE THREAD

**Issue by bardware** [mozilla/kitsune#4377]
I have my mails sorted by `Date received` descending grouped by sort order. Still they are shown sorted ascending within the group.
Is this indented behaviour?

![grafik](https://user-images.githubusercontent.com/802702/81739947-7fe8e580-949c-11ea-8ca0-ba0beb076249.png)

Where do I best ask this question?

**Comment by LeoMcA** [comment]
Hey @bardware this seems to be a question about Thunderbird, please ask it here: https://support.mozilla.org/en-US/questions/new/thunderbird
