### ISSUE TITLE
disable picture in picture (via code) not working

### ISSUE THREAD

**Issue by Offbeatmammal** [mozilla/kitsune#4393]
unlike Chromium, it looks like the option to disable pip via javascript isn't working.
I thought it had worked when I posted [this answer](https://stackoverflow.com/a/54469523/1569675), but recent comments indicate that while it's working in Chrome, it's not working in Firefox (at least on macOS and Ubuntu)

    <html>
    <body>
    <video id="vid" controls muted>
      <source src="https://www.w3schools.com/html/mov_bbb.mp4">
    </video>
    <script>
      vid=document.getElementById("vid")
      vid.disablePictureInPicture = true
    </script>
    </body>
</html>

**Comment by LeoMcA** [comment]
Thanks for reporting this, but unfortunately it's in the wrong place: you'll want to report it on Bugzilla instead: https://bugzilla.mozilla.org/home
