### ISSUE TITLE
Forum Reply code drops returns when submitted.

### ISSUE THREAD

**Issue by MadMattAu** [mozilla/kitsune#4454]
Reply in the forum results in enter presses to force paragraphs being removed.  This has always occurred in Blockquote situations which is annoying in itself as a quote is not really a quote if you reformat it.  But recently, some three months ago, this behaviour has re-emerged in the user forum.

References https://bugzilla.mozilla.org/show_bug.cgi?id=1630036
https://support.mozilla.org/en-US/forums/contributors/714315?last=79039

This appears to be a regression as the same issue was fixed in https://bugzilla.mozilla.org/show_bug.cgi?id=1111809

**Comment by LeoMcA** [comment]
Thanks for the report, and pointing out this happens in blockquotes as well. Please follow the bugzilla report for updates.
