### ISSUE TITLE
update 79 broke hardware accel 

### ISSUE THREAD

**Issue by kinshakov** [mozilla/kitsune#4489]
Archlinux
Wayland.
USER.JS
user_pref("widget.wayland-dmabuf-vaapi.enabled", true);
user_pref("media.ffvpx.enabled", false);
MOZ_WEBRENDER=1
Before updating it was ok. After update the the same settings give video stuttering. Swithing to software accel helps - video getting smooth, but software.

**Comment by akatsoulas** [comment]
Thank you for filing this issue.
This repository is used for the Mozilla Support site and not for Firefox.
If you would like to report a bug for Firefox, please use the following Bugzilla link.
https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox
