### ISSUE TITLE
Deleted user files toghether with firefox profile files.

### ISSUE THREAD

**Issue by kosturanovk** [mozilla/kitsune#4490]
Hi,
Recently i have encountered a very strange, dangerous and unaccepted behaviour while working (precisely deleting) a firefox profile. 
Namely using ver. 79. 0 on Win 10 i have created a new profile randomly saving its files on my Desktop.
I have accomplished the task I was supposed to do with the new firefox profile and wanted to get rid of it.
From about:profiles i have deleted the profile by clicking the option delete profile and discard files.
Unfortunately this option deleted almost all the files on my desktop together with the files of the profile...

Could you please check this issue and provide me a feedback? 
Being the case that the PC was my work computer, i lost valuable files and a lot of nerves for making a restore .....

In case you need further information or details on how to replicate the issue feel free to ask.
looking forward to a feedback
thanks,
Kiro

**Comment by akatsoulas** [comment]
Thank you for filing this issue.
This repository is used for the Mozilla Support site and not for Firefox.
If you would like to report a bug for Firefox, please use the following Bugzilla link.
https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox
