### ISSUE TITLE
TB taking 268GB of ram -- I thing there is a major memory leak in TB98 of Jul 27 2020 .  

### ISSUE THREAD

**Issue by dvandusen** [mozilla/kitsune#4491]
TB taking 268GB of ram (Mac v 10.15,6 wi 40GMB of ram)  -- I think there is a major memory leak in TB98 of Jul 27 2020 .  Rather than mere hardware acceleration missing, I see that the memory leak may be root cause.)

I consistently get the error after reboot, and it may be that a restart of TB (no change of version) will then work.

Is there a rollback version that goes back one beta version?  It is very hard to find rollback versions that will work on the same profile.

**Comment by akatsoulas** [comment]
Thank you for filing this issue.
This repository is used for the Mozilla Support site and not for Thunderbird.
If you would like to report a bug for Thunderbird, please use the following Bugzilla link.

https://bugzilla.mozilla.org/enter_bug.cgi?product=Thunderbird
