### ISSUE TITLE
Importing ABC directly from collections has been deprecated and will be removed in Python 3.10

### ISSUE THREAD

**Issue by tirkarthi** [mozilla/kitsune#4500]
Use `collections` for Python 2 and `collections.abc` for Python 3.4+

https://github.com/mozilla/kitsune/blob/db42cf7841b75ff0d4b6d3b21ac2524636110429/kitsune/wiki/widgets.py#L34

**Comment by Metropass** [comment]
I'll take a look at this, and create a PR :)
