### ISSUE TITLE
Black ruins git blame

### ISSUE THREAD

**Issue by etanot** [mozilla/kitsune#4539]
When we're making commits which strictly contains formatting or style changes, it ruins the git blame and make things harder when we're trying to figure out why certain change has done which is overwritten by black, especially when we're chasing a bug. It would be nice, if would support [git blame ignore revs](https://github.com/psf/black#migrating-your-code-style-without-ruining-git-blame). We could you use [this](https://github.com/ipython/ipython/pull/12091) commit of https://github.com/ipython/ipython/ project as a reference.

Can I make a pull request for this?

/cc @LeoMcA @akatsoulas

**Comment by LeoMcA** [comment]
Yes please! This has been on my to-do list for a while.

> We could you use this commit of https://github.com/ipython/ipython/ project as a reference.

I think the shell scripts to configure git are a bit excessive, but I like the format of the `.git-blame-ignore-revs` file. Let's do something like that, and add some documentation explaining the purpose, how to enable it, and pointing to git's documentation.

**Comment by finn0** [comment]
> add some documentation explaining the purpose

I'm thinking about adding this documentation just after [install sample data](https://kitsune.readthedocs.io/en/latest/hacking_howto.html#install-sample-data) section. @LeoMcA Is it sounds good to you?

**Comment by finn0** [comment]
And one more thing, can you help me in collecting commits for `.git-blame-ignore-revs` file? Here, I've collected some, please correct me if I've listed some wrong commits.

- [black: missed bits #4477](https://github.com/mozilla/kitsune/pull/4477)
- [black: m-w #4476](https://github.com/mozilla/kitsune/pull/4476)
- [Black formatting - community app #4475](https://github.com/mozilla/kitsune/pull/4475)
- [update black to 20.8b1 #4525](https://github.com/mozilla/kitsune/pull/4525)
- [Do not ignore W504 in flake8. #4485](https://github.com/mozilla/kitsune/pull/4485)

**Comment by LeoMcA** [comment]
> I'm thinking about adding this documentation just after install sample data section. @LeoMcA Is it sounds good to you?

I'd add it within the https://kitsune.readthedocs.io/en/latest/conventions.html#git-conventions section

> Here, I've collected some, please correct me if I've listed some wrong commits.

Yep these look good. I think there's one from about 3 years ago with some JavaScript re-indentation, but if we can't find it now we can always add to the ignore file as we go along and discover new commits.

**Comment by akatsoulas** [comment]
This is not a priority so I am closing this issue. A pr will be more than accepted though :)
