### ISSUE TITLE
Broken PDF rendering

### ISSUE THREAD

**Issue by 8FordPrefect8** [mozilla/kitsune#4542]
I found the PDF rendering to be broken.
I have detailed information on the gitlab page of the poppler project, since a similar problem is existing with poppler Cairo.
Please see this link for further information.
https://gitlab.freedesktop.org/poppler/poppler/-/issues/965

**Comment by LeoMcA** [comment]
Hi @8FordPrefect8, please file bugs with Firefox in Bugzilla: https://bugzilla.mozilla.org/
