### ISSUE TITLE
Default version of Thunderbird ignored

### ISSUE THREAD

**Issue by chrisilias** [mozilla/kitsune#4547]
According to Joni, the default version of Thunderbird the KB should be displaying is set to version 78.

When I test it, the version that gets displayed is 68.

<img width="1069" alt="2020-10-05_18-34-08" src="https://user-images.githubusercontent.com/21164976/95276421-28fff600-0819-11eb-91e8-8da664040e88.png">

**Comment by LeoMcA** [comment]
@jonichan it looks like both version 78 and 68 are set as default, is that intentional?

**Comment by chrisilias** [comment]
I've pinged Joni on Slack, who has now removed 68 as a default. Everything thing looks good now.
