### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by Aman-Codes** [mozilla/kitsune#4570]
The google play store link to Install Firefox Reality present on [this](https://support.mozilla.org/en-US/kb/install-firefox-reality) page is broken.

**Comment by akatsoulas** [comment]
Thank you @Aman-Codes for submitting this issue!
I filed it in [Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1673301) where bugs for Knowledge Base are tracked.
