### ISSUE TITLE
Make PGP error message more helpful

### ISSUE THREAD

**Issue by Wurzelkoch** [mozilla/kitsune#4601]
If I
1. Import a public PGP key to Thunderbird 78.4
2. Compose a Mail to its owner and tell thunderbird to encrypt it and
3. Hit send

I get an error message that `there are problems with the key`. I hit `OK` there and get prompted a window that is apparently designed to manage keys for the recipient(s) of the mail, but it only says `no key`.
I then 

4. go to the generic key management window of thunderbird, find the key there and set a higher trust level.

Afterwards, the email sends without problems. 

 So I conclude that Thunderbird says `no key` when it means `no trusted key`.

I think it should
a) say clearly, that a key exists in the keyring but is not trusted AND
b) offer to set the trust level from the sort-of-key-management-window that opens after the error message.

**Comment by LeoMcA** [comment]
This is the issue tracker for the software which powers support.mozilla.org. Please report Thunderbird bugs on bugzilla: https://bugzilla.mozilla.org/home
