### ISSUE TITLE
color change

### ISSUE THREAD

**Issue by Akhil170500** [mozilla/kitsune#4662]
Dark color instead of light would be a better experience to our new user and would be better to change blue color on button after hover with any other color. Can make home page more interactive.

**Comment by jwhitlock** [comment]
I'm not sure what you are suggesting. Could you add a screenshot of the page you are suggesting to change? A marked-up screenshot or an image of the proposed change would be even more helpful.

**Comment by KarenRhode** [comment]
Yeah good

**Comment by akatsoulas** [comment]
There's already a linked issue for a dark theme. Closing
