### ISSUE TITLE
Trusted Contributor no longer exempted from the spam filter

### ISSUE THREAD

**Issue by kelimuttu** [mozilla/kitsune#4717]
The contributors are talking about how the [Trusted Contributor group is no longer exempted from the spam filter](https://support.mozilla.org/en-US/forums/contributors/714933?last=80873). I think [this change](https://github.com/mozilla/kitsune/pull/4697/commits/0e56b36af56fcfff58c9524df006e277aa7e597d#diff-8cf7a374752730605a0c7e05cc0c9dc1fe7553088f2cbe953920aeca7e530f6eL34) might've caused this. 

Can we include the Trusted Contributor group on the TRUSTED_GROUPS as well?

**Comment by akatsoulas** [comment]
Thanks @kelimuttu . This is already tracked here and we are currently working on a fix
https://github.com/mozilla/sumo-project/issues/804
