### ISSUE TITLE
Bring back hard coded login form

### ISSUE THREAD

**Issue by mahdi-cll** [mozilla/kitsune#4725]
Practically with web based sync login form you should trust Mozilla site that everytime and everywhere deliver a honest form code that would not sent password to site. But with a offline (hard-coded) login form you are assured that you have a signed version of it downloaded (included in Firefox installer file) and later you can compare its checksum from other sources

**Comment by akatsoulas** [comment]
This is the issue tracker for the software which powers support.mozilla.org. For requests related to Firefox please use bugzilla: https://bugzilla.mozilla.org/home
