### ISSUE TITLE
[Cybersecurity] Need better privacy protection mechanism

### ISSUE THREAD

**Issue by dragon28** [mozilla/kitsune#4727]
Hello Developers,

Referring to the following articles:
 
https://thehackernews.com/2021/03/new-browser-attack-allows-tracking.html

https://arxiv.org/abs/2103.04952

We need a better privacy protection mechanism to prevent us being tracked.

Thanks

**Comment by LeoMcA** [comment]
This is the repository for support.mozilla.org, please file issues with Firefox on bugzilla.mozilla.org, thanks.

**Comment by hbeck2017** [comment]
- [ ]
