### ISSUE TITLE
Admin articles showing up in search

### ISSUE THREAD

**Issue by fabiLpz** [mozilla/kitsune#4748]
I created a new article and put it in the Administration category so that it doesn't show up in the SUMO search, but it keeps showing. How can I fix this?

Thanks.

**Comment by akatsoulas** [comment]
Thanks @fabiLpz for filing this. Is this related to the new search or the old one? 
For the former I opened a PR to remedy that and it will go live in a few days.

**Comment by akatsoulas** [comment]
Closing as fixed
