### ISSUE TITLE
security.webauth.webauthn_enable_softtoken not working

### ISSUE THREAD

**Issue by Dr-Sommer** [mozilla/kitsune#4753]
### Steps to reproduce the issue
Open Config with about:config
set security.webauth.webauthn_enable_usbtoken to FALSE
Set security.webauth.webauthn_enable_softtoken to TRUE
Set security.webauth.u2f to TRUE
Restart Firefox
Open Site with Webauth Authentication, for Example Joomla

### Expected result
Authenticate without Hardware Key

### Actual result
On setting a new Authenticator, Windows Security still wants a USB Security Hardware Key

### System information (as much as possible)
Win 10 Ver. 20H2
Firefox  87
Firefox  88.0b8 
Joomla 4

**Comment by LeoMcA** [comment]
Please file issues with Firefox at bugzilla.mozilla.org, thanks.
