### ISSUE TITLE
UI issue with firefox on Android

### ISSUE THREAD

**Issue by TimBullas** [mozilla/kitsune#4816]
I've discovered an issue with firefox on Android.
The "close tab" button is coverd by the "add new tab" button when you have 6 or more tabs open.
I appologise if this is the wrong place to post this issue, I clicked on the source code link on this page: https://support.mozilla.org/en-US/products/mobile?as=u&utm_source=inproduct
and it brought me to this project page.

I can supply a screen shot of the issue, I just can't seem to get the image button to work on the issue editor screen.

**Comment by lawpac10** [comment]
I never authorized any change ...just ignore this message

**Comment by akatsoulas** [comment]
Thanks @TimBullas for reporting this issue. This repository though is for Mozilla's Support site. You can file bugs relevant to Firefox in [bugzilla](https://bugzilla.mozilla.org/)
