### ISSUE TITLE
Add Translator to Firefox

### ISSUE THREAD

**Issue by mhp2011** [mozilla/kitsune#4933]
Hi
I am a Persian speaker
Please add a translator using Chrome and Edge browsers to Firefox so that I and other Persian speakers can read non-Persian articles with Firefox.
Otherwise we have to use other browsers!
You do not want us to use other browsers
So add this very useful feature
Thankful
An Iranian

**Comment by LeoMcA** [comment]
Hi, this is the wrong place for Firefox feature requests like this.

Features can be suggested here: https://mozilla.crowdicity.com/

And you might find an add-on which helps with what you want here: https://addons.mozilla.org/firefox/search/?q=translate
