### ISSUE TITLE
Disk space recovery options can not be modified before being enabled

### ISSUE THREAD

**Issue by arbourp** [mozilla/kitsune#5006]
In the "Synchronization & Storage" configuration page for email accounts there exists an option for 
"To recover disk space, old messagers can be permanently deleted, both local copies and originals on the remote server."

There are three options 
"Don't delete any messages"
"Delete all but the most recent"
"Delete messages more than"

The boxes allowing the selection of the number of messages and the number of days old are not modifiable until they are enabled.

By changing them, because there is no way to delay the application of this setting, the system will immediately begin purging messages when those boxes are checked.

A dialogue box appears asking to confirm the change, but there is no way to adjust the values for these attributes without first applying them.

The proper functionality should allow for the modification of the message count and the number of days without having to enable those options.

**Comment by LeoMcA** [comment]
Please report bugs with Thunderbird on Bugzilla: https://bugzilla.mozilla.org/enter_bug.cgi?product=Thunderbird
