### ISSUE TITLE
id_ff_alert still mentions Lockwise

### ISSUE THREAD

**Issue by cadeyrn** [mozilla/kitsune#5038]
The banner with the ID "id_ff_alert", for example on https://support.mozilla.org/de/kb/wechsel-von-pocket-zu-firefox-konten, still mentions Lockwise. The Lockwise reference should be removed. You could mention Mozilla VPN or Firefox Relay instead.

https://github.com/mozilla/kitsune/blob/59ddb253fec95649a7357a06f9763fd00406e495/kitsune/wiki/jinja2/wiki/document.html#L77-L84

**Comment by akatsoulas** [comment]
Thanks @cadeyrn for opening this issue. This should be addressed.
