### ISSUE TITLE
Firefox stops responding when there are problems attaching files 

### ISSUE THREAD

**Issue by Castanhari** [mozilla/kitsune#5040]
I use macbook and have files stored on Microsoft Onedrive Files On-Demand. Usually, when a file is only in the cloud and I need it, Onedrive (installed in the computer, not the website) downloads it on demand. On Gmail, when OneDrive is OFF, or its sync is PAUSED, trying to attach files that is in the cloud (what will not be downloaded), firefox crashes, Gmail and all tabs stop responding.

**Comment by LeoMcA** [comment]
For help with Firefox please go to https://support.mozilla.org/en-US/questions/new/desktop
