### ISSUE TITLE
Flagged Content Pending Moderation page is down

### ISSUE THREAD

**Issue by feer56** [mozilla/kitsune#5083]
Moderators use https://support.mozilla.org/flagged to review flagged items on SUMO. The page is currently unavailable with the following error:

"An Error Occurred

Oh, no! It looks like an unexpected error occurred. We've already notified the site administrators. Please try again now, or in a few minutes."

Verified by other mods/admins: https://support.mozilla.org/en-US/forums/forum-moderators/715682

Also reported on Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1762524

**Comment by akatsoulas** [comment]
This was caused by malformed, spammy content. I deleted the question and the queue is back. I will open a new issue to fix the underlying problem with the tracebacks from sentry
