### ISSUE TITLE
Atom migrated to using customElements from document.registerElement. Due

### ISSUE THREAD

**Issue by caseyMFRyan** [mozilla/kitsune#5198]
Atom migrated to using customElements from document.registerElement. Due
to this move, now there is need to attach some elements to the DOM on
some specs.

_オリジナルは @sadick254 が https://github.com/atom/tree-view/pull/1392 にポスト_

_オリジナルは @caseyMFRyan が https://github.com/caseyMFRyan/pritchettcassandra8-gmil.com/issues/3 にポスト_

**Comment by escattone** [comment]
@caseyMFRyan I don't see how this affects kitsune, so I'm going to close this. However, if you can explain how it does, I'll be happ to re-open it.
