### ISSUE TITLE
Add ability to select specific reviewers

### ISSUE THREAD

**Issue by dannycolin** [mozilla/kitsune#5253]
Sometimes we need someone in particular to validate part of a KB page and being able to prevent the revision from being merged without their approval would be very useful.

**Comment by kelimuttu** [comment]
+1000 to this idea! There are a bunch of times I have to ask someone to review through PM or chat. This will make things easier for contributors to do this and I'm sure will help shorten the time we need to get a revision reviewed.

**Comment by plwt** [comment]
I like the idea of this triggering a message over Kitsune to the selected reviewer with a link to the article.  Possibly better to do it this way than to start setting up separate dashboards.

**Comment by dannycolin** [comment]
> I like the idea of this triggering a message over Kitsune to the selected reviewer with a link to the article.

Sounds like a good idea to send a private message on behalf of the user you asked a review. Something like: "[username] is requesting a review for [article link]".

**Comment by AliceWyman** [comment]
You wrote (quote) Sometimes we need someone in particular to validate part of a KB page and being able to prevent the revision from being merged without their approval would be very useful.

What do you mean by, ''prevent the revision from being merged without their approval'' ?

**Comment by AliceWyman** [comment]
Related bug report: https://bugzilla.mozilla.org/show_bug.cgi?id=1839436

**Comment by kelimuttu** [comment]
@akatsoulas @escattone Can you close this one now that @dannycolin filed the same issue in Bugzilla?

**Comment by dannycolin** [comment]
Moved to bugzilla :)
