### ISSUE TITLE
[Bug]: The context menu in the "Delete Folder" bookmarks does not request confirmation for deletion

### ISSUE THREAD

**Issue by budarin** [mozilla/kitsune#5321]
Firstly, this menu item is located in a dangerous area and leads to accidental clicks on it

Secondly - it does not require confirmation of deletion!
I have already twice accidentally permanently deleted folders that I have been collecting for several years!

**Comment by RasstAdonai** [comment]
> Firstly, this menu item is located in a dangerous area and leads to accidental clicks on it
> 
> Secondly - it does not require confirmation of deletion!
> I have already twice accidentally permanently deleted folders that I have been collecting for several years!

Closed

**Comment by escattone** [comment]
@budarin This repo is only for the Mozilla support website itself, not for issues with any one of Mozilla's products. I'm not sure what Mozilla product you're referring to. I suspect you're referring to Firefox or Thunderbird?
