### ISSUE TITLE
no "new message" button, drag and drop absent, mouse in the dialogues, automatic select of the messages

### ISSUE THREAD

**Issue by Ericounet** [mozilla/kitsune#5379]
HI,

playing with the nightly build, I didn't find anywhere a "new message" button. I have the official Debian aside, so I can compare what is working and what is not anymore.

And it's not available in the "personalization" part.

Where did you put it?

Other problems:

1) no Drag And Drop between the messages and the folders.

2) when deleting a message, it goes to the following message, but it's not selected: you have to click the message to be able to delete it for example.

3) filters: the mouse is "not working" in the filter dialogues.

**Comment by escattone** [comment]
@Ericounet The issues in this repo are only for issues with the https://support.mozilla.org website itself, not for getting support for Mozilla's products. Did you want support for Firefox? If so, you can start [here](https://support.mozilla.org/en-US/products/firefox).
