### ISSUE TITLE
Buttons in the message window are not working

### ISSUE THREAD

**Issue by Ericounet** [mozilla/kitsune#5380]
hi,

the buttons in the message window don't work .

Eric

**Comment by escattone** [comment]
@Ericounet What application are you using? Please be more specific (add URLs visited, screenshots, etc.)?

**Comment by Ericounet** [comment]
hi,

thunderbird nightly, version: 111.0a1 (2023-01-26) (64 bits)
Debian testing (12)

1) delete button not working in the message window 
2) mouse not working in the transfer dialog (you have to scroll down and select with the arrows)
3) no "new message" anywhere): only available in the main menu.
4) no DragandDrop beween the messages pane and the folders.

5) not a bug, but something which doesn't look super nice: there are 3 ways of displaying the messages/folders with different densities. It doesn't look super nice; it's either too compact, or too loose.

I have the old thunderbird (the one with Debian 12) and everything is working fine. Just the nightly has a lot of UI problems
I'll post the other problems as I find them.

Best regards and thanks for the hard work. 

PS:  I post this for improvements, not to complain. I use thunderbird since the first time it was launched (on Linux), around 20 years or more (on Linux Debian since 1993)

**Comment by Ericounet** [comment]
sorry, it looks like it is the wrong place (I just read your emails)

Eric

**Comment by escattone** [comment]
@Ericounet Yes, this repo is only for work related to the https://support.mozilla.org website itself. You probably already know this, but you can go to https://www.thunderbird.net/en-US/contact/ to see how to get the support you need for Thunderbird.
