### ISSUE TITLE
Disappearing kb elements in Firefox Reader Mode

### ISSUE THREAD

**Issue by evictor** [mozilla/kitsune#5542]
# Preamble/environment

I don't know the extent of this bug—it's possible it may affect many more browsers, versions, and/or pages on this site. But here are my specifics which may be necessary to at least some extent (e.g. browser may matter):

* Browser: Firefox 91.0.2 (64-bit)
* OS: 13.4 (22F66)
* Document width/height: 1792&times;988

# Steps to reproduce

1. Visit https://support.mozilla.org/en-US/kb/dns-over-https?as=u&utm_source=inproduct#w_configure-doh-protection-settings
    <details><summary>Details</summary>
    <p>The URL hash zips you to the section of interest, <strong>Configure DoH protection settings</strong>.</p>
    </details> 
2. Take note of these visible `.menu` items (not semantically great CSS class name but that's for another internal issue :wink:) that appear as highlighted words in their respective sentences:
    <img width="771" alt="image" src="https://github.com/mozilla/kitsune/assets/1620156/7ba4e2e1-2692-4437-9f0f-dbfe33a1b39f">

3. Enter Firefox _Reader Mode_:
    <img width="741" alt="image" src="https://github.com/mozilla/kitsune/assets/1620156/373f80cf-f33b-415d-b189-18d89de5b22e">

4. Look for those `.menu` highlighted parts...

# Expected

The `.menu` highlighted words should still be there.

# Actual

They've vanished.

<img width="1179" alt="image" src="https://github.com/mozilla/kitsune/assets/1620156/07b9ec88-0dda-4e3c-b5f3-b2d4fddb72b0">

**Comment by smithellis** [comment]
We should decide if we want to eliminate the `.menu` as a class that can be used in our wiki markup, file a bug with FF for readability mode aggression or move the issue out as a low impact/low priority. @akatsoulas @escattone I can confirm that the issue happens to items in documents classed with `menu`.

**Comment by smithellis** [comment]
I believe @emilghittasv is/will open a FF bug.  I'll leave this in backlog until we see the outcome.

**Comment by emilghittasv** [comment]
Filled under https://bugzilla.mozilla.org/show_bug.cgi?id=1847925

**Comment by akatsoulas** [comment]
This is now tracked in Firefox and it's not related to SuMo. Thanks @evictor for catching and filing this!
