### ISSUE TITLE
Issue with option `Add To Home Screen`

### ISSUE THREAD

**Issue by i-santosh** [mozilla/kitsune#5553]

**Comment by i-santosh** [comment]
There is an issue with option `Add To Home Sceen` in Firefox Browser in Android 8.1 . To identify issue, i install the another browser which is `Firefox Focus - No Fuss Browser` , and this browser easily create `Home Screen Shortcuts`. While inspecting the files, i noticed that the one common difference between Both Browser which is about `install shortcut` permission. I think, that's why there is an issue with this option in Firefox browser.

Hope you will fix it soon.

**Comment by escattone** [comment]
@i-santosh The issues in this repository are not for Firefox products but for the code that runs the website `support.mozilla.org`. You can start your support journey for the Firefox Android product at https://support.mozilla.org/en-US/products/mobile.
