### ISSUE TITLE
Usability Changes for Document Editing

### ISSUE THREAD

**Issue by smithellis** [mozilla/kitsune#5566]
We should make two usability fixes after 1234 is pushed:

- When editing document metadata, give the user the choice to 'Save and Continue Editing" or "Save"  - the first takes you back to the same edit page, the second takes you to the article itself. Alternately, just have "Save" but have it go to the article.
- The 'Needs change' checkbox has a 'Comment' field below it that is for adding a comment upon selecting the box, but the box is always there - and confusingly aligned. The comment box should be right sized, and show/hide upon checkbox click.

**Comment by emilghittasv** [comment]
I can confirm that the "Edit Article Metadata" form has only the "Save description" button (as a way to save the edit progress) and it redirects the user back to the article content when clicked.

I can also confirm that the "Needs change", alongside with the "Comment" textarea works as expected:
- Verified that the "Comment" textarea is hidden by default and toggling the "Needs change" checkbox displays or hides the textarea back.
- Verified that metadata description can be edited by using the "Needs change" checkbox (in both stages: checked or unchecked) without introducing any text inside the "Comment" textarea and the "Needs Update" status from the KB dashboard (https://support.allizom.org/en-US/contributors) updates accordingly.
- Same as above but verified while having some text introduced inside the "Comment" textarea. Can confirm that the entered text and the "Needs Update" status is successfully displayed/reflected inside the KB dashboard (https://support.allizom.org/en-US/contributors)


Testing was performed on:
OS: Windows 10 and macOS 11 (for desktop) and Huawei P40Pro (for mobile)
Browsers: Firefox, Chrome and Safari

Moving this ticket inside the "Release" column.
