### ISSUE TITLE
KB article URL always modified to URL#

### ISSUE THREAD

**Issue by jscher2000** [mozilla/kitsune#5602]
This is somewhat annoying for contributors copying the URL for pasting elsewhere.

I think it might be caused by setting

window.location.hash = "";

in the load event handler at

https://github.com/mozilla/kitsune/blob/main/kitsune/sumo/static/sumo/js/document.js#L24

which seems to have been introduced in recent weeks by 

https://github.com/mozilla/kitsune/commit/e6e3a1852f6d7d3d704c2aa235b2647522a461e5

There's a Firefox bug which leaves a pointless # at the end of the URL in that scenario: 

https://bugzilla.mozilla.org/show_bug.cgi?id=1544428

Could you test for an existing hash first before setting it as a way to work around this problem?

Thanks.

Ref. https://support.mozilla.org/forums/contributors/716468

**Comment by emilghittasv** [comment]
I can confirm that this is verified fixed on stage using Firefox 116.0.2, Firefox 117.0b4, Chrome and Safari on both Windows 10 and macOS 11.

The hash is no longer added at the end of the KB article URL.

Moving this ticket inside the "Release" column.
