### ISSUE TITLE
Improve search results for device migration page

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/kitsune#5772]
I was looking for the [device migration page](https://support.mozilla.org/en-US/kb/switching-devices) on sumo and found that it was hard to get it to appear for some potentially typical searches you might expect for the page to appear.

For example the following searches:

- “How do I move firefox to a new device?”
- “Install firefox on a new device”
- “move firefox to a new computer”
- “migrate to new computer”

Don’t seem to show up the [device migration wizard](https://support.mozilla.org/en-US/kb/switching-devices) in the search.

- Whereas “Backup firefox” does.

Looking at search engine results pages (SERPs) the same problem occurs. 

Because of this, it could be good to think how we can include these questions (and any others we think might be used) more organically so that both the SUMO index and SERPs benefit at the same time.

**Comment by akatsoulas** [comment]
The content team is working on updating the KB article and providing more metadata for internal search.

**Comment by akatsoulas** [comment]
The content team updated this article which in turn improved search relevance. @muffinresearch please re-open if we need to tune this more.
