### ISSUE TITLE
Confirmation mails do not arrive

### ISSUE THREAD

**Issue by cadeyrn** [mozilla/kitsune#5807]
To report a bug to the Pocket team, I have sent a support request via https://support.mozilla.org/en-US/questions/new/pocket/form. After I sent the request, a message appeared saying that a confirmation email had been sent to me:

<img width="742" alt="sumo" src="https://github.com/mozilla/kitsune/assets/1100614/6f46fcaa-0680-46c8-b8ff-89cd61199f87">

But I did not receive an email, neither in the inbox nor in the spam folder.

**Comment by Ammumk** [comment]
happy

**Comment by emilghittasv** [comment]
This was a Zendesk config issue. 

This issue is now fixed and the confirmation email is successfully sent.
