### ISSUE TITLE
Removal of pinned tabs

### ISSUE THREAD

**Issue by babininja** [mozilla/kitsune#5824]
Hi,
I am using firefox but i have a problem with that.
if i have pinned tabs and i open a private window then close common window with tabs and open it again. all my pinned tabs will remove and if i close both windows they never return. why is this happening?

**Comment by escattone** [comment]
@babininja This repo is only for the code that powers the Mozilla support website, not for getting support for Mozilla's products. For Firefox support, you can go to https://support.mozilla.org/en-US/questions/new/desktop, where you can search for an article that may address your question or ask the community for help.
