### ISSUE TITLE
firefox doesn't start after latest update

### ISSUE THREAD

**Issue by itmehr** [mozilla/kitsune#5927]
firefox doesn't start after latest update
![2024-03-24_090646](https://github.com/mozilla/kitsune/assets/24986586/95b3df58-aa14-4688-b68b-02960651ca6f)
![2024-03-24_090704](https://github.com/mozilla/kitsune/assets/24986586/9ca3b5f4-fc05-4f41-aeec-c81aa0738bc9)

**Comment by escattone** [comment]
@itmehr This repository is only for the code that powers the Mozilla support website, not for Firefox itself. For Firefox support, you might want to start at https://support.mozilla.org/en-US/products/, select the kind of Firefox you're running (desktop, iOS, or Android), and then either find an existing article or question/answer that helps you, or ask your question directly in the community forum.
