### ISSUE TITLE
Firefox 124.2 Android 

### ISSUE THREAD

**Issue by juanpc2018** [mozilla/kitsune#5953]
Firefox Android lacks the codec:
AOMedia AV1
Example:
https://odysee.com/@sanjin:e/zager-evans-in-the-year-2525:8

Youtube version transcoded, works ok on Firefox.
Chrome Android has AOMedia support, works ok.

Click Download,
VLC player Android:
![Screenshot_2024-04-13-21-06-23](https://github.com/mozilla/kitsune/assets/33388902/1ffa5c30-1da5-46e4-8086-6dbe864b3b2b)

**Comment by juanpc2018** [comment]
![Capture+_2024-04-13-21-16-24](https://github.com/mozilla/kitsune/assets/33388902/4108bfcc-db94-4ef0-943b-df4384ea686d)

**Comment by escattone** [comment]
@juanpc2018 This repository is only for the Mozilla support website itself, not for Mozilla's products like Firefox for Android. If you'd like support for Firefox for Android, you might want to look at any or all of the following options:

- Search for an existing article or question at https://support.mozilla.org/en-US/products/mobile.
- Ask a question at https://support.mozilla.org/en-US/questions/new/mobile/form
- File a bug at https://bugzilla.mozilla.org/describecomponents.cgi?product=Fenix
