### ISSUE TITLE
Gmail oauth2 fails when local web server is running

### ISSUE THREAD

**Issue by hackwin** [mozilla/kitsune#5965]
Thunderbird email for Gmail stopped working.  Thunderbird loaded a web pop-up (oauth2) asking to re-authorize Gmail and Thunderbird.  I clicked Authorize and the connection to imap.gmail.com failed right afterwards.  When you look at the oauth2 prompt, the email is "tb-google-oauth@googlegroups.com" and the redirect to is "http://localhost/".  

I was running a web server to test something else at the time.  Closing the localhost webserver made it work again.  If Thunderbird requires running a web server to finish oauth2 authentication, it should at least show an error if those ports are already in use (port 80 or port 443).  It just fails and the user has no idea why.

**Comment by escattone** [comment]
@hackwin This repository is only for the Mozilla support website itself. It's not for posting issues with any of the products like Thunderbird. You might want go to https://support.mozilla.org/en-US/questions/new/thunderbird and either search for an article or question related to your issue or submit a new question.
