### ISSUE TITLE
Existing Mozilla accounts taken as unexistent

### ISSUE THREAD

**Issue by jmontano** [mozilla/kitsune#5995]
Hi, I forgot the password to my mozilla account jmontano@gmail.com.
When trying to Sign in I get asked for a new password and it says the account already exists.
![image](https://github.com/mozilla/kitsune/assets/67191/c2c67abd-fb06-497f-b098-73ba108f36be)

When doing password recovery I get the message: "Unknown account"
This issue won't let me access my paid pocket suscription :(
![image](https://github.com/mozilla/kitsune/assets/67191/d3582188-9805-4a98-a42f-dda4c56d9e32)

**Comment by kelimuttu** [comment]
Hey @jmontano, you may want to submit a support ticket through [this contact form ](https://support.mozilla.org/questions/new/mozilla-account/form)to get help with your Mozilla account issue. I understand that lose access to your Mozilla account atm, but this is a special contact form in which you don't need an account to submit a question. 

Hope that helps!

**Comment by akatsoulas** [comment]
This repository is related to the Mozilla Support website. Please follow the process that @kelimuttu shared in the comment above if you need help with your account.
