### ISSUE TITLE
Cannot actually enter RegEx for Subject (RegEx) etc. matches for Message Filters

### ISSUE THREAD

**Issue by Gnurrf** [mozilla/kitsune#6068]
When switching to any RegEx match, e.g., on Subject, the entry field into which the search string (in this case a RegEx) should be entered just vanishes (see screenshot attached).

**Comment by escattone** [comment]
@Gnurrf Can you provide more context on what this refers to?

**Comment by Gnurrf** [comment]
Apologies for the strangely embarassing title, now the typos are fixed. It refers to the Message Filter entry dialog, specifically the table at the bottom where individual filters are entered into separate rows. The rows for RegEx-based filters appear to be broken, as the actual text entry field, where the RegEx would be entered, is missing.

I did upload a screenshot of this, but have no idea how to get it displayed. TB is 115.11.1 running on MacOS 15.4 on M3.

**Comment by escattone** [comment]
@Gnurrf Oh, so this is related to Thunderbird? You'll want to post your bug report to the proper place starting from https://bugzilla.mozilla.org/describecomponents.cgi?product=Thunderbird. This repo is only for the code that powers Mozilla's support website, not for Mozilla's products themselves. I'm going to close this issue, but feel free to re-open if I'm mistaken. Cheers.
