### ISSUE TITLE
Please add shortcut AI in browser

### ISSUE THREAD

**Issue by MR-d3R** [mozilla/kitsune#6182]
The AI in sidebar looks good, but it would be really awesome if you add a shortcut for more usability. Clicking by mouse every time to open chat is very uncomfortable and takes long time!

**Comment by escattone** [comment]
@MR-d3R Thanks for sharing, but this repository is not for Firefox. It's only for the code that powers support.mozilla.org. You might want to make your suggestion via https://connect.mozilla.org/. Cheers.
