### ISSUE TITLE
Oulook Webmail Notifications Stopped Working with version 129.0.1

### ISSUE THREAD

**Issue by hahntech** [mozilla/kitsune#6188]
Prior to the update published on 8/13/24, the outlook webmail application was able to post notifications in the upper right-hand corner of the browser and play a sound when each new email arrived. This is no long working in version 129.0.1. 

Attempts to correct this issue on my end:
I have turned off the notifications settings, removed the entry for outlook.office.com from the FireFox notifications rules. Then I closed FireFox and reopened it. Then I followed all the steps to reactive those notifications. However they still do not work. 

Specifications:
Using macOS version 14.6.1 and FireFox for Mac verion 129.0.1

I was going to rollback to a previous version of FireFox to make sure that latest update actaully created this issue. However I was advised against this due to security concerns of running a previous version of FireFox.

Please advise steps to correct this issue.

Thanks!

**Comment by escattone** [comment]
@hahntech This repository is only for the code that runs the Mozilla support website (https://support.mozilla.org), so to report your Firefox issue, please use [Bugzilla](https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox) instead. Cheers.
